open_system('gm_Subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay1', 'user1');
annotate_port('gm_Subsystem/Unit Delay1', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay4', 'user1');
annotate_port('gm_Subsystem/Unit Delay4', 1, 1, 'cp : 100.11 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Product', 'user2');
annotate_port('gm_Subsystem/Product', 0, 1, 'cp : 10.716 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Product8', 'user2');
annotate_port('gm_Subsystem/Product8', 0, 1, 'cp : 68.572 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Sum1', 'user2');
annotate_port('gm_Subsystem/Sum1', 0, 1, 'cp : 26.558 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Sum2', 'user2');
annotate_port('gm_Subsystem/Sum2', 0, 1, 'cp : 42.4 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Sum3', 'user2');
annotate_port('gm_Subsystem/Sum3', 0, 1, 'cp : 58.154 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Sum3_outbuff', 'user2');
annotate_port('gm_Subsystem/Sum3_outbuff', 0, 1, 'cp : 58.154 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Sum6', 'user2');
annotate_port('gm_Subsystem/Sum6', 0, 1, 'cp : 84.326 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Sum7', 'user2');
annotate_port('gm_Subsystem/Sum7', 0, 1, 'cp : 100.08 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Sum7_outbuff', 'user2');
annotate_port('gm_Subsystem/Sum7_outbuff', 0, 1, 'cp : 100.08 ns');
