vmap work ../work

vmap -c
vcom  ur_ear_fpga_sim_calc_phase_temp_nfp_uminus_single.vhd
vcom  ur_ear_fpga_sim_calc_phase_temp_nfp_sub_single.vhd
vcom  ur_ear_fpga_sim_calc_phase_temp_nfp_div_single.vhd
vcom  ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single.vhd
vcom  ur_ear_fpga_sim_calc_phase_temp_nfp_add2_single.vhd
vcom  ur_ear_fpga_sim_calc_phase_temp_nfp_add_single.vhd
vcom  ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp.vhd
