SLStudio.Utils.RemoveHighlighting(get_param('calc_tau', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_calc_tau', 'handle'));
annotate_port('gm_calc_tau/Delay1', 1, 1, '');
annotate_port('calc_tau/Delay1', 1, 1, '');
annotate_port('gm_calc_tau/read address generator', 0, 1, '');
annotate_port('calc_tau/read address generator', 0, 1, '');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('gm_calc_tau/write address generator', 0, 1, '');
annotate_port('gm_calc_tau/delayMatch', 0, 1, '');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('gm_calc_tau/write address generator/Subtract_stage2', 0, 1, '');
annotate_port('gm_calc_tau/write address generator/Subtract_stage3', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('cp_wideband_gammatone_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_cp_wideband_gammatone_filter', 'handle'));
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, '');
annotate_port('cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('ohc_lowpass_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ohc_lowpass_filter', 'handle'));
annotate_port('gm_ohc_lowpass_filter/Unit Delay', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay', 1, 1, '');
annotate_port('gm_ohc_lowpass_filter/Unit Delay1', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay1', 1, 1, '');
annotate_port('gm_ohc_lowpass_filter/Unit Delay3', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay3', 1, 1, '');
annotate_port('gm_ohc_lowpass_filter/Unit Delay5', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay5', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('ohc_nl_boltzman_function', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ohc_nl_boltzman_function', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('ohc_nonlinear_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ohc_nonlinear_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('outer_hair_cell', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_outer_hair_cell', 'handle'));
annotate_port('gm_outer_hair_cell/Model1', 1, 1, '');
annotate_port('outer_hair_cell/Model1', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('control_path', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_control_path', 'handle'));
annotate_port('gm_control_path/Delay1', 1, 1, '');
annotate_port('control_path/Delay1', 1, 1, '');
annotate_port('gm_control_path/Delay2', 1, 1, '');
annotate_port('control_path/Delay2', 1, 1, '');
annotate_port('gm_control_path/Model', 1, 1, '');
annotate_port('control_path/Model', 1, 1, '');
annotate_port('gm_control_path/Model2', 0, 1, '');
annotate_port('gm_control_path/Model2', 1, 1, '');
annotate_port('control_path/Model2', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('control_path_sim', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_control_path_sim', 'handle'));
annotate_port('gm_control_path_sim/dataplane/Avalon Data Processing', 0, 1, '');
annotate_port('gm_control_path_sim/dataplane/Avalon Data Processing/Subsystem', 0, 1, '');
