open_system('gm_calc_tau');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/write address generator', 'user2');
annotate_port('gm_calc_tau/write address generator', 0, 1, 'cp : 5.481 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/delayMatch', 'user1');
annotate_port('gm_calc_tau/delayMatch', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/integer delay DPRAM', 'user1');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, 'cp : 5.691 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/write address generator/Subtract_stage2', 'user2');
annotate_port('gm_calc_tau/write address generator/Subtract_stage2', 0, 1, 'cp : 2.467 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/write address generator/Subtract_stage3', 'user2');
annotate_port('gm_calc_tau/write address generator/Subtract_stage3', 0, 1, 'cp : 5.481 ns');
open_system('gm_cp_wideband_gammatone_filter');
open_system('gm_ohc_lowpass_filter');
open_system('gm_ohc_nl_boltzman_function');
open_system('gm_ohc_nonlinear_filter');
open_system('gm_outer_hair_cell');
open_system('gm_control_path');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model2', 'user2');
annotate_port('gm_control_path/Model2', 0, 1, 'cp : 5.691 ns');
open_system('gm_control_path_sim');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path_sim/dataplane/Avalon Data Processing', 'user2');
annotate_port('gm_control_path_sim/dataplane/Avalon Data Processing', 0, 1, 'cp : 5.691 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path_sim/dataplane/Avalon Data Processing/Subsystem', 'user2');
annotate_port('gm_control_path_sim/dataplane/Avalon Data Processing/Subsystem', 0, 1, 'cp : 5.691 ns');
