open_system('calc_tau');
open_system('gm_calc_tau');
open_system('cp_wideband_gammatone_filter');
open_system('gm_cp_wideband_gammatone_filter');
open_system('ohc_lowpass_filter');
open_system('gm_ohc_lowpass_filter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay3', 'user1');
hilite_system('ohc_lowpass_filter/Unit Delay3', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay5', 'user1');
hilite_system('ohc_lowpass_filter/Unit Delay5', 'user1');
open_system('ohc_nl_boltzman_function');
open_system('gm_ohc_nl_boltzman_function');
open_system('ohc_nonlinear_filter');
open_system('gm_ohc_nonlinear_filter');
open_system('outer_hair_cell');
open_system('gm_outer_hair_cell');
open_system('control_path');
open_system('gm_control_path');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Delay1', 'user4');
hilite_system('control_path/Delay1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Delay2', 'user4');
hilite_system('control_path/Delay2', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model', 'user4');
hilite_system('control_path/Model', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model1', 'user4');
hilite_system('control_path/Model1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model2', 'user4');
hilite_system('control_path/Model2', 'user4');
open_system('control_path_sim');
open_system('gm_control_path_sim');
