open_system('calc_tau');
open_system('gm_calc_tau');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Delay1', 'user2');
annotate_port('gm_calc_tau/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/Delay1', 'user2');
annotate_port('calc_tau/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/read address generator', 'user2');
annotate_port('gm_calc_tau/read address generator', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/read address generator', 'user2');
annotate_port('calc_tau/read address generator', 0, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/integer delay DPRAM', 'user2');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/integer delay DPRAM', 'user2');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/integer delay DPRAM', 'user2');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/integer delay DPRAM', 'user2');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('cp_wideband_gammatone_filter');
open_system('gm_cp_wideband_gammatone_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 'user2');
annotate_port('cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('ohc_lowpass_filter');
open_system('gm_ohc_lowpass_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay1', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay1', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay3', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay3', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay5', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay5', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('ohc_nl_boltzman_function');
open_system('gm_ohc_nl_boltzman_function');
open_system('ohc_nonlinear_filter');
open_system('gm_ohc_nonlinear_filter');
open_system('outer_hair_cell');
open_system('gm_outer_hair_cell');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_outer_hair_cell/Model1', 'user2');
annotate_port('gm_outer_hair_cell/Model1', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('outer_hair_cell/Model1', 'user2');
annotate_port('outer_hair_cell/Model1', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('control_path');
open_system('gm_control_path');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Delay1', 'user2');
annotate_port('gm_control_path/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('control_path/Delay1', 'user2');
annotate_port('control_path/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Delay2', 'user2');
annotate_port('gm_control_path/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('control_path/Delay2', 'user2');
annotate_port('control_path/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model', 'user2');
annotate_port('gm_control_path/Model', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('control_path/Model', 'user2');
annotate_port('control_path/Model', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model2', 'user2');
annotate_port('gm_control_path/Model2', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('control_path/Model2', 'user2');
annotate_port('control_path/Model2', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('control_path_sim');
open_system('gm_control_path_sim');
