config alt_sld_fab_alt_sld_fab_180_sddrg2y_cfg;
		design alt_sld_fab_alt_sld_fab_180_sddrg2y;
		instance alt_sld_fab_alt_sld_fab_180_sddrg2y.presplit use alt_sld_fab_altera_super_splitter_180.alt_sld_fab_altera_super_splitter_180_tphxg3y;
		instance alt_sld_fab_alt_sld_fab_180_sddrg2y.splitter use alt_sld_fab_altera_sld_splitter_180.alt_sld_fab_altera_sld_splitter_180_bpibaqi;
		instance alt_sld_fab_alt_sld_fab_180_sddrg2y.sldfabric use alt_sld_fab_altera_sld_jtag_hub_180.alt_sld_fab_altera_sld_jtag_hub_180_7c4w4na;
		instance alt_sld_fab_alt_sld_fab_180_sddrg2y.ident use alt_sld_fab_altera_connection_identification_hub_180.alt_sld_fab_altera_connection_identification_hub_180_xgksifi;
endconfig

