SLStudio.Utils.RemoveHighlighting(get_param('noise_suppression', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_noise_suppression', 'handle'));
annotate_port('gm_noise_suppression/dataplane/dataplane', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal2', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal2', 1, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/reciprocal', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal2', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/reciprocal', 1, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal2', 1, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal1', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal1', 1, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/reciprocal1', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal1', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/reciprocal1', 1, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Reciprocal1', 1, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed', 1, 2, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Add2', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Add2', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Data Type Conversion3', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Data Type Conversion3', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Add', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Add', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Data Type Conversion2', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Data Type Conversion2', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed1/Switch', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Switch', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed1/Product', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Product', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed1/Data Type Conversion', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Data Type Conversion', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed1/Add1', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Add1', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed1/Product1', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Product1', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed1', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/mux', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Mux', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/in2_buff', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/Delay1', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/Delay1', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/Delay4', 0, 1, '');
annotate_port('noise_suppression/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/Delay4', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/Add_stage3', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/rd_8', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Add2', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1/ratechange_splitcomp', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1/splitcomp_multiport', 0, 1, '');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering', 0, 1, '');
