open_system('gm_noise_suppression');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane', 0, 1, 'cp : 12.735 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics', 0, 1, 'cp : 6.369 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed', 1, 2, 'cp : 12.735 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/in2_buff', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/in2_buff', 0, 1, 'cp : 6.369 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/Add_stage3', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/Add_stage3', 0, 1, 'cp : 6.369 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/rd_8', 'user1');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/compute statistics/rd_8', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Add2', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Add2', 0, 1, 'cp : 12.735 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1', 0, 1, 'cp : 7.057 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1/ratechange_splitcomp', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1/ratechange_splitcomp', 0, 1, 'cp : 6.369 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1/splitcomp_multiport', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/streaming_partition_streamed/Serializer_Subnetwork1/splitcomp_multiport', 0, 1, 'cp : 7.057 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering', 'user2');
annotate_port('gm_noise_suppression/dataplane/dataplane/Adaptive_Wiener_Filter Sample Based Filtering', 0, 1, 'cp : 12.735 ns');
