config audioblade_system_altera_emif_180_hqphmvy_cfg;
		design audioblade_system_altera_emif_180_hqphmvy;
		instance audioblade_system_altera_emif_180_hqphmvy.arch use audioblade_system_altera_emif_arch_nf_180.audioblade_system_altera_emif_arch_nf_180_6fyzjwi;
		instance audioblade_system_altera_emif_180_hqphmvy.cal_slave_component use audioblade_system_altera_emif_cal_slave_nf_180.audioblade_system_altera_emif_cal_slave_nf_180_5pbk77i;
endconfig

