vmap work ../work

vmap -c
vcom  ur_ear_fpga_sim_redocking_site_nfp_div_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_relop_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_mul_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_cal_trel_k.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_log10_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_sub_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_calc_Tref.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_uminus_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_abs_double.vhd
vcom  ur_ear_fpga_sim_redocking_site_Redock_Component.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_convert_fix_10_En0_to_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_Elapsed_Time_Component.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_add_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_Xsum_Component.vhd
vcom  ur_ear_fpga_sim_redocking_site_unitRateInterval_Component.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_relop_double.vhd
vcom  ur_ear_fpga_sim_redocking_site_Current_Release_Component.vhd
vcom  ur_ear_fpga_sim_redocking_site_Current_Refactory_Component.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_recip_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_round_single.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_relop_single_block.vhd
vcom  ur_ear_fpga_sim_redocking_site_nfp_relop_single_block1.vhd
vcom  ur_ear_fpga_sim_redocking_site_redocking_site.vhd
