package require -exact qsys 20.1
load_system {soc_base_system.qsys}
set_instance_parameter_value pll_using_AD1939_MCLK {gui_output_clock_frequency0} {98.304}

add_instance fft_filters_0 fft_filters 1.0

add_connection pll_using_AD1939_MCLK.outclk0 fft_filters_0.clock
add_connection clk_hps.clk_reset fft_filters_0.reset
add_connection hps.h2f_lw_axi_master fft_filters_0.avalon_slave
set_connection_parameter_value hps.h2f_lw_axi_master/fft_filters_0.avalon_slave arbitrationPriority {1}
set_connection_parameter_value hps.h2f_lw_axi_master/fft_filters_0.avalon_slave baseAddress {0x0020}
set_connection_parameter_value hps.h2f_lw_axi_master/fft_filters_0.avalon_slave defaultConnection {0}

add_connection FE_Qsys_AD1939_Audio_Mini_v1_0.Line_In fft_filters_0.avalon_streaming_sink

add_connection fft_filters_0.avalon_streaming_source FE_Qsys_AD1939_Audio_Mini_v1_0.Headphone_Out
save_system {audiomini_system}