SLStudio.Utils.RemoveHighlighting(get_param('AN_Simulink_Model_v1', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_AN_Simulink_Model_v1', 'handle'));
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem', 1, 2, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients', 0, 9, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/From21', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Goto8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product18', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product23', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product26', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum10', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum12', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum16', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product25_to_gain', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout/Gain1_unary', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Constant2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Reciprocal1_recip', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Subtract', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain5', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide17', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract9', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter', 1, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/Sum1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Switch1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4_out1bypassMux', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Gain2_unaryminus', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Add3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide5', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Log10', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Math Function1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Subtract1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Unit Delay14', 1, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product18', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product23', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product28', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product33', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum10', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum12', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum16', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum20', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum24', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7_outbuff', 0, 1, '');
