open_system('gm_AN_Simulink_Model_v1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter', 0, 1, 'cp : 712.921 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem', 1, 2, 'cp : 1359.513 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter', 0, 1, 'cp : 712.921 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout', 0, 1, 'cp : 712.921 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma', 0, 1, 'cp : 59.363 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients', 0, 9, 'cp : 475.692 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/From21', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/From21', 0, 1, 'cp : 475.692 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Goto8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Goto8', 0, 1, 'cp : 475.692 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product', 0, 1, 'cp : 486.064 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product13', 0, 1, 'cp : 585.846 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product18', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product18', 0, 1, 'cp : 627.772 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product23', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product23', 0, 1, 'cp : 669.698 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product26', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product26', 0, 1, 'cp : 711.624 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product8', 0, 1, 'cp : 543.92 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum1', 0, 1, 'cp : 501.906 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum10', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum10', 0, 1, 'cp : 601.6 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11', 0, 1, 'cp : 617.354 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11_outbuff', 0, 1, 'cp : 617.354 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum12', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum12', 0, 1, 'cp : 643.526 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13', 0, 1, 'cp : 659.28 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13_outbuff', 0, 1, 'cp : 659.28 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum16', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum16', 0, 1, 'cp : 685.452 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17', 0, 1, 'cp : 701.206 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17_outbuff', 0, 1, 'cp : 701.206 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum2', 0, 1, 'cp : 517.748 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3', 0, 1, 'cp : 533.502 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3_outbuff', 0, 1, 'cp : 533.502 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum6', 0, 1, 'cp : 559.674 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7', 0, 1, 'cp : 575.428 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7_outbuff', 0, 1, 'cp : 575.428 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product25_to_gain', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product25_to_gain', 0, 1, 'cp : 712.921 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout/Gain1_unary', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout/Gain1_unary', 0, 1, 'cp : 712.921 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Constant2', 'user1');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Constant2', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Reciprocal1_recip', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Reciprocal1_recip', 0, 1, 'cp : 43.521 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Subtract', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Subtract', 0, 1, 'cp : 59.363 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus', 0, 1, 'cp : 75.447 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus_outbuff', 0, 1, 'cp : 75.447 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain5', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain5', 0, 1, 'cp : 205.91 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage2', 0, 1, 'cp : 221.664 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage3', 0, 1, 'cp : 237.418 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5', 0, 1, 'cp : 430.462 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5_outbuff', 0, 1, 'cp : 430.462 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide1', 0, 1, 'cp : 120.66 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide17', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide17', 0, 1, 'cp : 475.692 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide7', 0, 1, 'cp : 298.49 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8', 0, 1, 'cp : 414.708 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8_outbuff', 0, 1, 'cp : 414.708 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1', 0, 1, 'cp : 75.205 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1_outbuff', 0, 1, 'cp : 75.205 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract6', 0, 1, 'cp : 204.613 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract9', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract9', 0, 1, 'cp : 253.26 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function3', 0, 1, 'cp : 188.771 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function6', 0, 1, 'cp : 369.495 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function', 0, 1, 'cp : 1050.159 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter', 1, 1, 'cp : 1359.513 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/Sum1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/Sum1', 0, 1, 'cp : 1066.001 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1', 0, 1, 'cp : 1049.101 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Switch1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Switch1', 0, 1, 'cp : 1050.159 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4_out1bypassMux', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4_out1bypassMux', 0, 1, 'cp : 1049.101 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Gain2_unaryminus', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Gain2_unaryminus', 0, 1, 'cp : 758.393 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Add3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Add3', 0, 1, 'cp : 931.357 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide1', 0, 1, 'cp : 1037.625 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide2', 0, 1, 'cp : 976.57 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide4', 0, 1, 'cp : 758.151 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide5', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide5', 0, 1, 'cp : 867.889 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Log10', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Log10', 0, 1, 'cp : 812.241 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Math Function1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Math Function1', 0, 1, 'cp : 915.603 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product3', 0, 1, 'cp : 822.659 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4', 0, 1, 'cp : 1048.043 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Subtract1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Subtract1', 0, 1, 'cp : 992.412 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Unit Delay14', 'user1');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Unit Delay14', 1, 1, 'cp : 1359.513 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product13', 0, 1, 'cp : 1160.271 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product18', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product18', 0, 1, 'cp : 1202.197 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product23', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product23', 0, 1, 'cp : 1244.123 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product28', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product28', 0, 1, 'cp : 1286.049 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product3', 0, 1, 'cp : 1076.419 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product33', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product33', 0, 1, 'cp : 1327.975 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product8', 0, 1, 'cp : 1118.345 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum10', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum10', 0, 1, 'cp : 1176.025 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11', 0, 1, 'cp : 1191.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11_outbuff', 0, 1, 'cp : 1191.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum12', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum12', 0, 1, 'cp : 1217.951 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13', 0, 1, 'cp : 1233.705 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13_outbuff', 0, 1, 'cp : 1233.705 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum16', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum16', 0, 1, 'cp : 1259.877 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17', 0, 1, 'cp : 1275.631 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17_outbuff', 0, 1, 'cp : 1275.631 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum2', 0, 1, 'cp : 1092.173 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum20', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum20', 0, 1, 'cp : 1301.803 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21', 0, 1, 'cp : 1317.557 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21_outbuff', 0, 1, 'cp : 1317.557 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum24', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum24', 0, 1, 'cp : 1343.729 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25', 0, 1, 'cp : 1359.483 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25_outbuff', 0, 1, 'cp : 1359.483 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3', 0, 1, 'cp : 1107.927 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3_outbuff', 0, 1, 'cp : 1107.927 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum6', 0, 1, 'cp : 1134.099 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7', 0, 1, 'cp : 1149.853 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7_outbuff', 0, 1, 'cp : 1149.853 ns');
