SLStudio.Utils.RemoveHighlighting(get_param('fft_filters', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_fft_filters', 'handle'));
annotate_port('gm_fft_filters/dataplane/dataplane', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/counter_A', 0, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/counter_A', 0, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/FFT_pulse_gen/Wait_for_data_to_start/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/FFT_pulse_gen/Wait_for_data_to_start/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/Filter_ROM_Choice', 1, 2, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/counter_gain_index', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Bitwise Operator', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Relational Operator1', 0, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Switch', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Switch', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/Filter_ROM_Choice/Complex_Gains_1_ROM', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/Filter_ROM_Choice/Complex_Gains_1_ROM/Gains_ROM_imag', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/Filter_ROM_Choice/Complex_Gains_1_ROM/Gains_ROM_imag/Lookup Table', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/Filter_ROM_Choice/Complex_Gains_1_ROM/Gains_ROM_imag/inrepeat', 0, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/Filter_ROM_Choice/Complex_Gains_1_ROM/Gains_ROM_imag/PipelineRegister', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/counter_B', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/counter_B', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Add', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Add', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Bitwise Operator', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/counter_A', 0, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/counter_A', 0, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/FFT_pulse_gen/Wait_for_data_to_start/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/FFT_pulse_gen/Wait_for_data_to_start/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Switch', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/counter_B', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/counter_B', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Add', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Add', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Bitwise Operator', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Bitwise Operator', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_Write_Select/FIFO_Write_Select', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_Write_Select', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine/fifo_state_machine', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1/fifo_state_machine1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2/fifo_state_machine2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3/fifo_state_machine3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_Write_Select/FIFO_Write_Select', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_Write_Select', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine/fifo_state_machine', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1/fifo_state_machine1', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2/fifo_state_machine2', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3/fifo_state_machine3', 1, 1, '');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, '');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left', 0, 1, '');
