open_system('fft_filters');
open_system('gm_fft_filters');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/counter_A', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/counter_A', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/counter_A', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/counter_A', 0, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Switch', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Switch', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/iFFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Frame_counter', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Frame_counter', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/counter_B', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/counter_B', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/counter_B', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/counter_B', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Left/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/counter_A', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/counter_A', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/counter_A', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/counter_A', 0, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Rate Transition2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/Fast_Transition/Upsample', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Analysis/FFT Frame Buffering/addr_B_gen/addr_B_gen_enable/B_Enable_Counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/Unit Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Switch', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Frequency_Domain_Processing/Apply_Complex_Gains/FFT_Filter_Coefficients/FFT_ROM_Indexing/Switch', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/iFFT', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine1', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine2', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/fifo_state_machine3', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Frame_counter', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Frame_counter', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/Frame_counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/counter_B', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/counter_B', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/counter_B', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/counter_B', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 'user2');
annotate_port('gm_fft_filters/dataplane/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 'user2');
annotate_port('fft_filters/dataplane/FFT_Analysis_Synthesis_Right/Synthesis/Overlap_and_Add/FIFO_4', 1, 1, 'Obstacle to clock-rate pipelining');
