SLStudio.Utils.RemoveHighlighting(get_param('pseudo_random_lut', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_pseudo_random_lut', 'handle'));
annotate_port('gm_pseudo_random_lut/Counter Limited', 0, 1, '');
annotate_port('pseudo_random_lut/Counter Limited', 0, 1, '');
annotate_port('gm_pseudo_random_lut/1-D Lookup Table', 1, 1, '');
annotate_port('gm_pseudo_random_lut/Data Type Conversion5', 0, 1, '');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, '');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, '');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, '');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, '');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('redocking_site', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_redocking_site', 'handle'));
annotate_port('gm_redocking_site/From10', 1, 1, '');
annotate_port('redocking_site/From10', 1, 1, '');
annotate_port('gm_redocking_site/From8', 1, 1, '');
annotate_port('redocking_site/From8', 1, 1, '');
annotate_port('gm_redocking_site/Redock Component', 1, 1, '');
annotate_port('redocking_site/Redock Component', 1, 1, '');
annotate_port('gm_redocking_site/Elapsed Time Component', 1, 1, '');
annotate_port('redocking_site/Elapsed Time Component', 1, 1, '');
annotate_port('gm_redocking_site/From7', 1, 1, '');
annotate_port('redocking_site/From7', 1, 1, '');
annotate_port('gm_redocking_site/Xsum Component', 1, 1, '');
annotate_port('redocking_site/Xsum Component', 1, 1, '');
annotate_port('gm_redocking_site/From3', 1, 1, '');
annotate_port('redocking_site/From3', 1, 1, '');
annotate_port('gm_redocking_site/unitRateInterval Component', 1, 1, '');
annotate_port('redocking_site/unitRateInterval Component', 1, 1, '');
annotate_port('gm_redocking_site/From1', 1, 1, '');
annotate_port('redocking_site/From1', 1, 1, '');
annotate_port('gm_redocking_site/Current Refactory Component', 1, 1, '');
annotate_port('redocking_site/Current Refactory Component', 1, 1, '');
annotate_port('gm_redocking_site/Current Refactory Component/Initialization Signal', 0, 1, '');
annotate_port('redocking_site/Current Refactory Component/Initialization Signal', 0, 1, '');
annotate_port('gm_redocking_site/Current Release Component/Initialization Signal', 0, 1, '');
annotate_port('redocking_site/Current Release Component/Initialization Signal', 0, 1, '');
annotate_port('gm_redocking_site/Elapsed Time Component/HDL Counter', 1, 1, '');
annotate_port('redocking_site/Elapsed Time Component/HDL Counter', 1, 1, '');
annotate_port('gm_redocking_site/Redock Component/Initialization Signal', 0, 1, '');
annotate_port('redocking_site/Redock Component/Initialization Signal', 0, 1, '');
annotate_port('gm_redocking_site/unitRateInterval Component/Initialization Signal', 0, 1, '');
annotate_port('redocking_site/unitRateInterval Component/Initialization Signal', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('spike_generator', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_spike_generator', 'handle'));
annotate_port('gm_spike_generator/Pseudo Random LUT', 0, 1, '');
annotate_port('gm_spike_generator/Delay', 1, 1, '');
annotate_port('spike_generator/Delay', 1, 1, '');
annotate_port('gm_spike_generator/Delay1', 1, 1, '');
annotate_port('spike_generator/Delay1', 1, 1, '');
annotate_port('gm_spike_generator/Delay10', 1, 1, '');
annotate_port('spike_generator/Delay10', 1, 1, '');
annotate_port('gm_spike_generator/Delay2', 1, 1, '');
annotate_port('spike_generator/Delay2', 1, 1, '');
annotate_port('gm_spike_generator/Delay3', 1, 1, '');
annotate_port('spike_generator/Delay3', 1, 1, '');
annotate_port('gm_spike_generator/Delay4', 1, 1, '');
annotate_port('spike_generator/Delay4', 1, 1, '');
annotate_port('gm_spike_generator/Delay5', 1, 1, '');
annotate_port('spike_generator/Delay5', 1, 1, '');
annotate_port('gm_spike_generator/Delay6', 1, 1, '');
annotate_port('spike_generator/Delay6', 1, 1, '');
annotate_port('gm_spike_generator/Delay7', 1, 1, '');
annotate_port('spike_generator/Delay7', 1, 1, '');
annotate_port('gm_spike_generator/Delay8', 1, 1, '');
annotate_port('spike_generator/Delay8', 1, 1, '');
annotate_port('gm_spike_generator/Delay9', 1, 1, '');
annotate_port('spike_generator/Delay9', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Site 41', 1, 1, '');
annotate_port('spike_generator/Redocking Site 4', 1, 1, '');
annotate_port('gm_spike_generator/From48', 1, 1, '');
annotate_port('spike_generator/From48', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Site 31', 1, 1, '');
annotate_port('spike_generator/Redocking Site 3', 1, 1, '');
annotate_port('gm_spike_generator/From47', 1, 1, '');
annotate_port('spike_generator/From47', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Site 21', 1, 1, '');
annotate_port('spike_generator/Redocking Site 2', 1, 1, '');
annotate_port('gm_spike_generator/From46', 1, 1, '');
annotate_port('spike_generator/From46', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Site 11', 1, 1, '');
annotate_port('spike_generator/Redocking Site 1', 1, 1, '');
annotate_port('gm_spike_generator/From2', 1, 1, '');
annotate_port('spike_generator/From2', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period/Delay2', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period/Delay2', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period/Delay6', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period/Delay6', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component/Initialization Signal', 0, 1, '');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component/Initialization Signal', 0, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('spike_generator_sim', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_spike_generator_sim', 'handle'));
annotate_port('gm_spike_generator_sim/dataplane/Avalon Data Processing', 0, 1, '');
annotate_port('gm_spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 0, 1, '');
annotate_port('gm_spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 1, 1, '');
annotate_port('spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 1, 1, '');
