open_system('gm_mean_spike_rate');
open_system('gm_initialize_signal');
open_system('gm_pseudo_random_lut');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pseudo_random_lut/1-D Lookup Table', 'user2');
annotate_port('gm_pseudo_random_lut/1-D Lookup Table', 1, 1, 'cp : 21.143 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pseudo_random_lut/Data Type Conversion5', 'user1');
annotate_port('gm_pseudo_random_lut/Data Type Conversion5', 0, 1, 'cp : 0 ns');
open_system('gm_redocking_site');
open_system('gm_spike_generator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Pseudo Random LUT', 'user2');
annotate_port('gm_spike_generator/Pseudo Random LUT', 0, 1, 'cp : 21.143 ns');
open_system('gm_spike_generator_sim');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator_sim/dataplane/Avalon Data Processing', 'user2');
annotate_port('gm_spike_generator_sim/dataplane/Avalon Data Processing', 0, 1, 'cp : 21.143 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 'user2');
annotate_port('gm_spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 0, 1, 'cp : 21.143 ns');
