open_system('mean_spike_rate');
open_system('gm_mean_spike_rate');
open_system('initialize_signal');
open_system('gm_initialize_signal');
open_system('pseudo_random_lut');
open_system('gm_pseudo_random_lut');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_pseudo_random_lut/Counter Limited', 'user2');
annotate_port('gm_pseudo_random_lut/Counter Limited', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('pseudo_random_lut/Counter Limited', 'user2');
annotate_port('pseudo_random_lut/Counter Limited', 0, 1, 'Obstacle to clock-rate pipelining');
open_system('redocking_site');
open_system('gm_redocking_site');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From10', 'user2');
annotate_port('gm_redocking_site/From10', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('redocking_site/From10', 'user2');
annotate_port('redocking_site/From10', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From8', 'user2');
annotate_port('gm_redocking_site/From8', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('redocking_site/From8', 'user2');
annotate_port('redocking_site/From8', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Redock Component', 'user2');
annotate_port('gm_redocking_site/Redock Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Redock Component', 'user2');
annotate_port('redocking_site/Redock Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Elapsed Time Component', 'user2');
annotate_port('gm_redocking_site/Elapsed Time Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Elapsed Time Component', 'user2');
annotate_port('redocking_site/Elapsed Time Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From7', 'user2');
annotate_port('gm_redocking_site/From7', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('redocking_site/From7', 'user2');
annotate_port('redocking_site/From7', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Xsum Component', 'user2');
annotate_port('gm_redocking_site/Xsum Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Xsum Component', 'user2');
annotate_port('redocking_site/Xsum Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From3', 'user2');
annotate_port('gm_redocking_site/From3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('redocking_site/From3', 'user2');
annotate_port('redocking_site/From3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/unitRateInterval Component', 'user2');
annotate_port('gm_redocking_site/unitRateInterval Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/unitRateInterval Component', 'user2');
annotate_port('redocking_site/unitRateInterval Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From1', 'user2');
annotate_port('gm_redocking_site/From1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('redocking_site/From1', 'user2');
annotate_port('redocking_site/From1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Refactory Component', 'user2');
annotate_port('gm_redocking_site/Current Refactory Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Current Refactory Component', 'user2');
annotate_port('redocking_site/Current Refactory Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Refactory Component/Initialization Signal', 'user2');
annotate_port('gm_redocking_site/Current Refactory Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('redocking_site/Current Refactory Component/Initialization Signal', 'user2');
annotate_port('redocking_site/Current Refactory Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Release Component/Initialization Signal', 'user2');
annotate_port('gm_redocking_site/Current Release Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('redocking_site/Current Release Component/Initialization Signal', 'user2');
annotate_port('redocking_site/Current Release Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Elapsed Time Component/HDL Counter', 'user2');
annotate_port('gm_redocking_site/Elapsed Time Component/HDL Counter', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('redocking_site/Elapsed Time Component/HDL Counter', 'user2');
annotate_port('redocking_site/Elapsed Time Component/HDL Counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Redock Component/Initialization Signal', 'user2');
annotate_port('gm_redocking_site/Redock Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('redocking_site/Redock Component/Initialization Signal', 'user2');
annotate_port('redocking_site/Redock Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/unitRateInterval Component/Initialization Signal', 'user2');
annotate_port('gm_redocking_site/unitRateInterval Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('redocking_site/unitRateInterval Component/Initialization Signal', 'user2');
annotate_port('redocking_site/unitRateInterval Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('spike_generator');
open_system('gm_spike_generator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay', 'user2');
annotate_port('gm_spike_generator/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay', 'user2');
annotate_port('spike_generator/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay1', 'user2');
annotate_port('gm_spike_generator/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay1', 'user2');
annotate_port('spike_generator/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay10', 'user2');
annotate_port('gm_spike_generator/Delay10', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay10', 'user2');
annotate_port('spike_generator/Delay10', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay2', 'user2');
annotate_port('gm_spike_generator/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay2', 'user2');
annotate_port('spike_generator/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay3', 'user2');
annotate_port('gm_spike_generator/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay3', 'user2');
annotate_port('spike_generator/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay4', 'user2');
annotate_port('gm_spike_generator/Delay4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay4', 'user2');
annotate_port('spike_generator/Delay4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay5', 'user2');
annotate_port('gm_spike_generator/Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay5', 'user2');
annotate_port('spike_generator/Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay6', 'user2');
annotate_port('gm_spike_generator/Delay6', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay6', 'user2');
annotate_port('spike_generator/Delay6', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay7', 'user2');
annotate_port('gm_spike_generator/Delay7', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay7', 'user2');
annotate_port('spike_generator/Delay7', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay8', 'user2');
annotate_port('gm_spike_generator/Delay8', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay8', 'user2');
annotate_port('spike_generator/Delay8', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Delay9', 'user2');
annotate_port('gm_spike_generator/Delay9', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Delay9', 'user2');
annotate_port('spike_generator/Delay9', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 41', 'user2');
annotate_port('gm_spike_generator/Redocking Site 41', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('spike_generator/Redocking Site 4', 'user2');
annotate_port('spike_generator/Redocking Site 4', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From48', 'user2');
annotate_port('gm_spike_generator/From48', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From48', 'user2');
annotate_port('spike_generator/From48', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 31', 'user2');
annotate_port('gm_spike_generator/Redocking Site 31', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Site 3', 'user2');
annotate_port('spike_generator/Redocking Site 3', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From47', 'user2');
annotate_port('gm_spike_generator/From47', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From47', 'user2');
annotate_port('spike_generator/From47', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 21', 'user2');
annotate_port('gm_spike_generator/Redocking Site 21', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Site 2', 'user2');
annotate_port('spike_generator/Redocking Site 2', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From46', 'user2');
annotate_port('gm_spike_generator/From46', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From46', 'user2');
annotate_port('spike_generator/From46', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 11', 'user2');
annotate_port('gm_spike_generator/Redocking Site 11', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Site 1', 'user2');
annotate_port('spike_generator/Redocking Site 1', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From2', 'user2');
annotate_port('gm_spike_generator/From2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From2', 'user2');
annotate_port('spike_generator/From2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Calculation', 'user2');
annotate_port('spike_generator/Redocking Calculation', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('spike_generator/Redocking Calculation/Correct Redocking Period', 'user2');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Correct Redocking Period/Delay2', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Redocking Calculation/Correct Redocking Period/Delay2', 'user2');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Correct Redocking Period/Delay6', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period/Delay6', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Redocking Calculation/Correct Redocking Period/Delay6', 'user2');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period/Delay6', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Current Redock Component/Initialization Signal', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('spike_generator/Redocking Calculation/Current Redock Component/Initialization Signal', 'user2');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component/Initialization Signal', 0, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('spike_generator_sim');
open_system('gm_spike_generator_sim');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 'user2');
annotate_port('gm_spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 'user2');
annotate_port('spike_generator_sim/dataplane/Avalon Data Processing/Spike Generator Singles', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
