open_system('mean_spike_rate');
open_system('gm_mean_spike_rate');
open_system('initialize_signal');
open_system('gm_initialize_signal');
open_system('pseudo_random_lut');
open_system('gm_pseudo_random_lut');
open_system('redocking_site');
open_system('gm_redocking_site');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From8', 'user3');
hilite_system('redocking_site/From8', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Redock Component', 'user3');
hilite_system('redocking_site/Redock Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From5', 'user3');
hilite_system('redocking_site/From5', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Elapsed Time Component', 'user3');
hilite_system('redocking_site/Elapsed Time Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From7', 'user3');
hilite_system('redocking_site/From7', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Xsum Component', 'user3');
hilite_system('redocking_site/Xsum Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From3', 'user3');
hilite_system('redocking_site/From3', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/unitRateInterval Component', 'user3');
hilite_system('redocking_site/unitRateInterval Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/xsum_logic', 'user3');
hilite_system('redocking_site/xsum_logic', 'user3');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From1', 'user5');
hilite_system('redocking_site/From1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Refactory Component', 'user5');
hilite_system('redocking_site/Current Refactory Component', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Goto2', 'user5');
hilite_system('redocking_site/Goto2', 'user5');
open_system('spike_generator');
open_system('gm_spike_generator');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From35', 'user5');
hilite_system('spike_generator/From35', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 41', 'user5');
hilite_system('spike_generator/Redocking Site 4', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto26', 'user5');
hilite_system('spike_generator/Goto26', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From48', 'user5');
hilite_system('spike_generator/From48', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From24', 'user5');
hilite_system('spike_generator/From24', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 31', 'user5');
hilite_system('spike_generator/Redocking Site 3', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto25', 'user5');
hilite_system('spike_generator/Goto25', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From47', 'user5');
hilite_system('spike_generator/From47', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From13', 'user5');
hilite_system('spike_generator/From13', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 21', 'user5');
hilite_system('spike_generator/Redocking Site 2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto4', 'user5');
hilite_system('spike_generator/Goto4', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From46', 'user5');
hilite_system('spike_generator/From46', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto', 'user5');
hilite_system('spike_generator/Goto', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From', 'user5');
hilite_system('spike_generator/From', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 11', 'user5');
hilite_system('spike_generator/Redocking Site 1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto2', 'user5');
hilite_system('spike_generator/Goto2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From2', 'user5');
hilite_system('spike_generator/From2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation', 'user5');
hilite_system('spike_generator/Redocking Calculation', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Current Redock Component', 'user5');
hilite_system('spike_generator/Redocking Calculation/Current Redock Component', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 'user5');
hilite_system('spike_generator/Redocking Calculation/Correct Redocking Period', 'user5');
open_system('spike_generator_sim');
open_system('gm_spike_generator_sim');
