open_system('mean_spike_rate');
open_system('gm_mean_spike_rate');
open_system('initialize_signal');
open_system('gm_initialize_signal');
open_system('pseudo_random_lut');
open_system('gm_pseudo_random_lut');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('pseudo_random_lut/1-D Lookup Table', 'user2');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, 'Block not characterized for this configuration');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('pseudo_random_lut/1-D Lookup Table', 'user2');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('pseudo_random_lut/1-D Lookup Table', 'user2');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('pseudo_random_lut/1-D Lookup Table', 'user2');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('pseudo_random_lut/1-D Lookup Table', 'user2');
annotate_port('pseudo_random_lut/1-D Lookup Table', 1, 1, 'Block not characterized');
open_system('redocking_site');
open_system('gm_redocking_site');
open_system('spike_generator');
open_system('gm_spike_generator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Current Redock Component/Add1', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, 'Block not characterized');
hilite_system('spike_generator/Redocking Calculation/Current Redock Component/Add1', 'user2');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, 'Block not characterized');
open_system('spike_generator_sim');
open_system('gm_spike_generator_sim');
