vlib work
vmap -c
vcom  Auditory_Nerve_Model_pkg.vhd
vcom  nfp_uminus_single.vhd
vcom  nfp_mul_single.vhd
vcom  nfp_add_single.vhd
vcom  nfp_gain_pow2_single.vhd
vcom  C1_FIlter.vhd
vcom  Calculate_C1filterout.vhd
vcom  nfp_recip_single.vhd
vcom  nfp_sub_single.vhd
vcom  Calculate_rsigma.vhd
vcom  nfp_add2_single.vhd
vcom  nfp_div_single.vhd
vcom  nfp_atan_single.vhd
vcom  nfp_tan_single.vhd
vcom  Get_C1_Coefficients.vhd
vcom  C1_Chirp_Filter.vhd
vcom  nfp_abs_single.vhd
vcom  Calculate_C2filterout.vhd
vcom  C2_Wideband_Filter.vhd
vcom  nfp_pow_single.vhd
vcom  nfp_relop_single.vhd
vcom  Calculate_wbout.vhd
vcom  Third_Order_IIR_Filter.vhd
vcom  nfp_relop_single_block.vhd
vcom  MATLAB_Function1.vhd
vcom  nfp_sincos_single.vhd
vcom  CP_Wideband_Gammatone_Filter.vhd
vcom  Middle_Ear_Filter.vhd
vcom  nfp_log10_single.vhd
vcom  nfp_exp_single.vhd
vcom  Subsystem1.vhd
vcom  nfp_log_single.vhd
vcom  IHC_C1_NL_Logarithmic_Function.vhd
vcom  Subsystem1_block.vhd
vcom  IHC_C2_NL_Logarithmic_Function.vhd
vcom  IHC_LP_Filter.vhd
vcom  Subsystem.vhd
vcom  Calculate_tauc1.vhd
vcom  nfp_relop_single_block1.vhd
vcom  NL_After_OHC_Function.vhd
vcom  OHC_LP_Filter.vhd
vcom  OHC_NL_Boltzman_Function.vhd
vcom  Subsystem1_block1.vhd
vcom  Auditory_Nerve_Model.vhd
