SLStudio.Utils.RemoveHighlighting(get_param('AN_Simulink_Model_v1', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_AN_Simulink_Model_v1', 'handle'));
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem', 1, 2, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients', 0, 9, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/From21', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Goto8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product18', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product23', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product26', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum10', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum12', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum16', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product25_to_gain', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout/Gain1_unary', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Reciprocal_recip', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Subtract', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain5', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide17', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract9', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Complex to Real-Imag', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product_ReIm2Complex', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_C2ReIm_1', 0, 2, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_ReIm2Complex', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_AC_minus_BD', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Product', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Product1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Gain', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4_C2ReIm', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4_ReIm2Complex', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7_C2ReIm', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7_ReIm2Complex', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8_C2ReIm', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8_ReIm2Complex', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum2_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum4_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum5', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum6_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Unit Delay1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum10', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum11', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum11_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum7_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product15_to_gain', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter', 1, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/Sum1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Switch1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4_out1bypassMux', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Gain2_unaryminus', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Add3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide5', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Log10', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Math Function1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Subtract1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Unit Delay14', 1, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product18', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product23', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product28', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product33', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum10', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum12', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum16', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum20', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum24', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Add', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Subtract', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Product_to_gain', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_Switch1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_Switch2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Gain2_unaryminus', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Abs', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Add3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Divide1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Exp', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product4_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_UpperRelop', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Product3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Product8', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum6', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum7', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum7_outbuff', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Gain1_unaryminus', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Add1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Add4', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide3', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Math Function2', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Product', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Subtract1', 0, 1, '');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Subtract3', 0, 1, '');
