open_system('gm_AN_Simulink_Model_v1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter', 0, 1, 'cp : 1556.989 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter', 0, 1, 'cp : 336.737 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter', 0, 1, 'cp : 143.303 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem', 1, 2, 'cp : 2203.581 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1', 0, 1, 'cp : 844.156 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter', 0, 1, 'cp : 1556.989 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout', 0, 1, 'cp : 1556.989 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma', 0, 1, 'cp : 903.431 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients', 0, 9, 'cp : 1319.76 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/From21', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/From21', 0, 1, 'cp : 1319.76 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Goto8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Goto8', 0, 1, 'cp : 1319.76 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product', 0, 1, 'cp : 1330.132 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product13', 0, 1, 'cp : 1429.914 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product18', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product18', 0, 1, 'cp : 1471.84 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product23', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product23', 0, 1, 'cp : 1513.766 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product26', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product26', 0, 1, 'cp : 1555.692 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product8', 0, 1, 'cp : 1387.988 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum1', 0, 1, 'cp : 1345.974 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum10', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum10', 0, 1, 'cp : 1445.668 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11', 0, 1, 'cp : 1461.422 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum11_outbuff', 0, 1, 'cp : 1461.422 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum12', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum12', 0, 1, 'cp : 1487.594 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13', 0, 1, 'cp : 1503.348 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum13_outbuff', 0, 1, 'cp : 1503.348 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum16', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum16', 0, 1, 'cp : 1529.52 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17', 0, 1, 'cp : 1545.274 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum17_outbuff', 0, 1, 'cp : 1545.274 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum2', 0, 1, 'cp : 1361.816 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3', 0, 1, 'cp : 1377.57 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum3_outbuff', 0, 1, 'cp : 1377.57 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum6', 0, 1, 'cp : 1403.742 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7', 0, 1, 'cp : 1419.496 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Sum7_outbuff', 0, 1, 'cp : 1419.496 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product25_to_gain', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/C1 FIlter/Product25_to_gain', 0, 1, 'cp : 1556.989 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout/Gain1_unary', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate C1filterout/Gain1_unary', 0, 1, 'cp : 1556.989 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Reciprocal_recip', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Reciprocal_recip', 0, 1, 'cp : 887.677 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Subtract', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Calculate rsigma/Subtract', 0, 1, 'cp : 903.431 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus', 0, 1, 'cp : 919.515 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain3_unaryminus_outbuff', 0, 1, 'cp : 919.515 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain5', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Gain5', 0, 1, 'cp : 1049.978 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage2', 0, 1, 'cp : 1065.732 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add4_stage3', 0, 1, 'cp : 1081.486 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5', 0, 1, 'cp : 1274.53 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Add5_outbuff', 0, 1, 'cp : 1274.53 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide1', 0, 1, 'cp : 964.728 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide17', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide17', 0, 1, 'cp : 1319.76 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide7', 0, 1, 'cp : 1142.558 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8', 0, 1, 'cp : 1258.776 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Divide8_outbuff', 0, 1, 'cp : 1258.776 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1', 0, 1, 'cp : 919.273 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract1_outbuff', 0, 1, 'cp : 919.273 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract6', 0, 1, 'cp : 1048.681 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract9', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Subtract9', 0, 1, 'cp : 1097.328 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function3', 0, 1, 'cp : 1032.839 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/C1 Chirp Filter/Get C1 Coefficients/Trigonometric Function6', 0, 1, 'cp : 1213.563 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout', 0, 1, 'cp : 336.737 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter', 0, 1, 'cp : 279.361 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Complex to Real-Imag', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Complex to Real-Imag', 0, 1, 'cp : 305.575 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product_ReIm2Complex', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product_ReIm2Complex', 0, 1, 'cp : 153.721 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_C2ReIm_1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_C2ReIm_1', 0, 2, 'cp : 279.361 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_ReIm2Complex', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_ReIm2Complex', 0, 1, 'cp : 305.575 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product', 0, 1, 'cp : 153.721 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product13', 0, 1, 'cp : 289.733 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_AC_minus_BD', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Product1_AC_minus_BD', 0, 1, 'cp : 305.575 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Product', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Product', 0, 1, 'cp : 315.947 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Product1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Product1', 0, 1, 'cp : 336.737 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Gain', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Calculate wbout/Gain', 0, 1, 'cp : 326.365 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4_C2ReIm', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4_C2ReIm', 0, 1, 'cp : 169.475 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4_ReIm2Complex', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4_ReIm2Complex', 0, 1, 'cp : 179.847 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7_C2ReIm', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7_C2ReIm', 0, 1, 'cp : 211.355 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7_ReIm2Complex', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7_ReIm2Complex', 0, 1, 'cp : 221.727 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8_C2ReIm', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8_C2ReIm', 0, 1, 'cp : 253.235 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8_ReIm2Complex', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8_ReIm2Complex', 0, 1, 'cp : 263.607 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum1', 0, 1, 'cp : 169.475 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum2', 0, 1, 'cp : 195.601 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum2_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum2_outbuff', 0, 1, 'cp : 195.601 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum3', 0, 1, 'cp : 211.355 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum4', 0, 1, 'cp : 237.481 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum4_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum4_outbuff', 0, 1, 'cp : 237.481 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum5', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum5', 0, 1, 'cp : 253.235 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum6', 0, 1, 'cp : 279.361 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum6_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Sum6_outbuff', 0, 1, 'cp : 279.361 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product4', 0, 1, 'cp : 179.847 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product7', 0, 1, 'cp : 221.727 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Third Order IIR Filter/Product8', 0, 1, 'cp : 263.607 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Unit Delay1', 'user1');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Unit Delay1', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product', 0, 1, 'cp : 10.716 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product13', 0, 1, 'cp : 110.498 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product8', 0, 1, 'cp : 68.572 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum1', 0, 1, 'cp : 26.558 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum10', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum10', 0, 1, 'cp : 126.252 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum11', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum11', 0, 1, 'cp : 142.006 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum11_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum11_outbuff', 0, 1, 'cp : 142.006 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum2', 0, 1, 'cp : 42.4 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum3', 0, 1, 'cp : 58.154 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum3_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum3_outbuff', 0, 1, 'cp : 58.154 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum6', 0, 1, 'cp : 84.326 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum7', 0, 1, 'cp : 100.08 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum7_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Sum7_outbuff', 0, 1, 'cp : 100.08 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product15_to_gain', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Middle Ear Filter/Product15_to_gain', 0, 1, 'cp : 143.303 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function', 0, 1, 'cp : 1894.227 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter', 1, 1, 'cp : 2203.581 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/Sum1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/Sum1', 0, 1, 'cp : 1910.069 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1', 0, 1, 'cp : 1893.169 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Switch1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Switch1', 0, 1, 'cp : 1894.227 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4_out1bypassMux', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4_out1bypassMux', 0, 1, 'cp : 1893.169 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Gain2_unaryminus', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Gain2_unaryminus', 0, 1, 'cp : 1602.461 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Add3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Add3', 0, 1, 'cp : 1775.425 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide1', 0, 1, 'cp : 1881.693 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide2', 0, 1, 'cp : 1820.638 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide4', 0, 1, 'cp : 1602.219 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide5', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Divide5', 0, 1, 'cp : 1711.957 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Log10', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Log10', 0, 1, 'cp : 1656.309 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Math Function1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Math Function1', 0, 1, 'cp : 1759.671 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product3', 0, 1, 'cp : 1666.727 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Product4', 0, 1, 'cp : 1892.111 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Subtract1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC C1 NL Logarithmic Function/Subsystem1/Subtract1', 0, 1, 'cp : 1836.48 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Unit Delay14', 'user1');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Unit Delay14', 1, 1, 'cp : 2203.581 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product13', 0, 1, 'cp : 2004.339 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product18', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product18', 0, 1, 'cp : 2046.265 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product23', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product23', 0, 1, 'cp : 2088.191 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product28', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product28', 0, 1, 'cp : 2130.117 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product3', 0, 1, 'cp : 1920.487 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product33', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product33', 0, 1, 'cp : 2172.043 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Product8', 0, 1, 'cp : 1962.413 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum10', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum10', 0, 1, 'cp : 2020.093 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11', 0, 1, 'cp : 2035.847 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum11_outbuff', 0, 1, 'cp : 2035.847 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum12', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum12', 0, 1, 'cp : 2062.019 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13', 0, 1, 'cp : 2077.773 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum13_outbuff', 0, 1, 'cp : 2077.773 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum16', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum16', 0, 1, 'cp : 2103.945 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17', 0, 1, 'cp : 2119.699 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum17_outbuff', 0, 1, 'cp : 2119.699 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum2', 0, 1, 'cp : 1936.241 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum20', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum20', 0, 1, 'cp : 2145.871 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21', 0, 1, 'cp : 2161.625 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum21_outbuff', 0, 1, 'cp : 2161.625 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum24', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum24', 0, 1, 'cp : 2187.797 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25', 0, 1, 'cp : 2203.551 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum25_outbuff', 0, 1, 'cp : 2203.551 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3', 0, 1, 'cp : 1951.995 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum3_outbuff', 0, 1, 'cp : 1951.995 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum6', 0, 1, 'cp : 1978.167 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7', 0, 1, 'cp : 1993.921 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem/IHC LP Filter/Sum7_outbuff', 0, 1, 'cp : 1993.921 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1', 0, 1, 'cp : 844.156 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function', 0, 1, 'cp : 811.351 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter', 0, 1, 'cp : 677.652 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function', 0, 1, 'cp : 593.8 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Add', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Add', 0, 1, 'cp : 844.156 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Subtract', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Subtract', 0, 1, 'cp : 827.105 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Product_to_gain', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/Calculate tauc1/Product_to_gain', 0, 1, 'cp : 828.402 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_Switch1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_Switch1', 0, 1, 'cp : 810.709 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_Switch2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_Switch2', 0, 1, 'cp : 811.351 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Gain2_unaryminus', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Gain2_unaryminus', 0, 1, 'cp : 723.124 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Abs', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Abs', 0, 1, 'cp : 677.652 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Add3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Add3', 0, 1, 'cp : 797.098 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Divide1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Divide1', 0, 1, 'cp : 722.882 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Exp', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Exp', 0, 1, 'cp : 770.838 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product3', 0, 1, 'cp : 781.256 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product4', 0, 1, 'cp : 807.516 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product4_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Product4_outbuff', 0, 1, 'cp : 807.516 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_UpperRelop', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/NL After OHC Function/Saturation_UpperRelop', 0, 1, 'cp : 809.742 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Product3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Product3', 0, 1, 'cp : 604.218 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Product8', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Product8', 0, 1, 'cp : 646.144 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum2', 0, 1, 'cp : 619.972 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum3', 0, 1, 'cp : 635.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum3_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum3_outbuff', 0, 1, 'cp : 635.726 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum6', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum6', 0, 1, 'cp : 661.898 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum7', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum7', 0, 1, 'cp : 677.652 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum7_outbuff', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC LP Filter/Sum7_outbuff', 0, 1, 'cp : 677.652 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Gain1_unaryminus', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Gain1_unaryminus', 0, 1, 'cp : 397.963 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Add1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Add1', 0, 1, 'cp : 461.431 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Add4', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Add4', 0, 1, 'cp : 487.603 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide1', 0, 1, 'cp : 397.721 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide2', 0, 1, 'cp : 532.816 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Divide3', 0, 1, 'cp : 593.8 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Math Function2', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Math Function2', 0, 1, 'cp : 445.677 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Product', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Product', 0, 1, 'cp : 471.849 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Subtract1', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Subtract1', 0, 1, 'cp : 352.491 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Subtract3', 'user2');
annotate_port('gm_AN_Simulink_Model_v1/Auditory Nerve Model/Subsystem1/OHC NL Boltzman Function/Subtract3', 0, 1, 'cp : 548.57 ns');
