open_system('AN_Simulink_Model_v1');
open_system('gm_AN_Simulink_Model_v1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/MATLAB Function1', 'user2');
hilite_system('AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/MATLAB Function1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Delay', 'user2');
hilite_system('AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Delay', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Sum/Sum', 'user2');
hilite_system('AN_Simulink_Model_v1/Auditory Nerve Model/CP Wideband Gammatone Filter/Sum', 'user2');
