open_system('gm_alpha7th_Order_IIR_Filter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Unit Delay', 'user1');
annotate_port('gm_alpha7th_Order_IIR_Filter/Unit Delay', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Unit Delay14', 'user1');
annotate_port('gm_alpha7th_Order_IIR_Filter/Unit Delay14', 1, 1, 'cp : 293.898 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Product13', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Product13', 0, 1, 'cp : 94.656 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Product18', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Product18', 0, 1, 'cp : 136.582 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Product2', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Product2', 0, 1, 'cp : 10.716 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Product23', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Product23', 0, 1, 'cp : 178.508 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Product28', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Product28', 0, 1, 'cp : 220.434 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Product33', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Product33', 0, 1, 'cp : 262.36 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Product8', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Product8', 0, 1, 'cp : 52.73 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum10', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum10', 0, 1, 'cp : 110.41 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum11', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum11', 0, 1, 'cp : 126.164 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum11_outbuff', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum11_outbuff', 0, 1, 'cp : 126.164 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum12', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum12', 0, 1, 'cp : 152.336 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum13', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum13', 0, 1, 'cp : 168.09 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum13_outbuff', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum13_outbuff', 0, 1, 'cp : 168.09 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum16', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum16', 0, 1, 'cp : 194.262 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum17', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum17', 0, 1, 'cp : 210.016 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum17_outbuff', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum17_outbuff', 0, 1, 'cp : 210.016 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum2', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum2', 0, 1, 'cp : 26.558 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum20', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum20', 0, 1, 'cp : 236.188 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum21', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum21', 0, 1, 'cp : 251.942 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum21_outbuff', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum21_outbuff', 0, 1, 'cp : 251.942 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum24', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum24', 0, 1, 'cp : 278.114 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum25', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum25', 0, 1, 'cp : 293.868 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum25_outbuff', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum25_outbuff', 0, 1, 'cp : 293.868 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum3', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum3', 0, 1, 'cp : 42.312 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum3_outbuff', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum3_outbuff', 0, 1, 'cp : 42.312 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum6', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum6', 0, 1, 'cp : 68.484 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum7', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum7', 0, 1, 'cp : 84.238 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha7th_Order_IIR_Filter/Sum7_outbuff', 'user2');
annotate_port('gm_alpha7th_Order_IIR_Filter/Sum7_outbuff', 0, 1, 'cp : 84.238 ns');
