# request TCL package from ACDS 13.1
package require -exact qsys 13.1

# module SG_DataPlane
set_module_property DESCRIPTION ""
set_module_property NAME SG_DataPlane
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "HDL Coder Generated IP"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME SG_DataPlane
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false

# documentation
set docprefix file:///
add_documentation_link "DATASHEET" [append docprefix [get_module_property MODULE_DIRECTORY] /doc/SG_ip_core_report.html]

# file sets
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SG_DataPlane
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SG_DataPlane_src_Left_Channel_Processing.vhd VHDL PATH hdl/SG_DataPlane_src_Left_Channel_Processing.vhd 
add_fileset_file SG_DataPlane_src_Right_Channel_Processing.vhd VHDL PATH hdl/SG_DataPlane_src_Right_Channel_Processing.vhd 
add_fileset_file SG_DataPlane_src_Avalon_Data_Processing.vhd VHDL PATH hdl/SG_DataPlane_src_Avalon_Data_Processing.vhd 
add_fileset_file SG_DataPlane_src_SG_DataPlane.vhd VHDL PATH hdl/SG_DataPlane_src_SG_DataPlane.vhd 
add_fileset_file SG_DataPlane_reset_sync.vhd VHDL PATH hdl/SG_DataPlane_reset_sync.vhd 
add_fileset_file SG_DataPlane_dut.vhd VHDL PATH hdl/SG_DataPlane_dut.vhd 
add_fileset_file SG_DataPlane_SimpleDualPortRAM_generic.vhd VHDL PATH hdl/SG_DataPlane_SimpleDualPortRAM_generic.vhd 
add_fileset_file SG_DataPlane_rdfifo_data_classic.vhd VHDL PATH hdl/SG_DataPlane_rdfifo_data_classic.vhd 
add_fileset_file SG_DataPlane_rdfifo_data.vhd VHDL PATH hdl/SG_DataPlane_rdfifo_data.vhd 
add_fileset_file SG_DataPlane_SimpleDualPortRAM_singlebit.vhd VHDL PATH hdl/SG_DataPlane_SimpleDualPortRAM_singlebit.vhd 
add_fileset_file SG_DataPlane_rdfifo_last_classic.vhd VHDL PATH hdl/SG_DataPlane_rdfifo_last_classic.vhd 
add_fileset_file SG_DataPlane_rdfifo_last.vhd VHDL PATH hdl/SG_DataPlane_rdfifo_last.vhd 
add_fileset_file SG_DataPlane_rdfifo_rid_classic.vhd VHDL PATH hdl/SG_DataPlane_rdfifo_rid_classic.vhd 
add_fileset_file SG_DataPlane_rdfifo_rid.vhd VHDL PATH hdl/SG_DataPlane_rdfifo_rid.vhd 
add_fileset_file SG_DataPlane_axi4_module.vhd VHDL PATH hdl/SG_DataPlane_axi4_module.vhd 
add_fileset_file SG_DataPlane_addr_decoder.vhd VHDL PATH hdl/SG_DataPlane_addr_decoder.vhd 
add_fileset_file SG_DataPlane_axi4.vhd VHDL PATH hdl/SG_DataPlane_axi4.vhd 
add_fileset_file SG_DataPlane.vhd VHDL PATH hdl/SG_DataPlane.vhd TOP_LEVEL_FILE

# connection point ip_clk
add_interface ip_clk clock end
set_interface_property ip_clk clockRate 0
set_interface_property ip_clk ENABLED true
set_interface_property ip_clk EXPORT_OF ""
set_interface_property ip_clk PORT_NAME_MAP ""
set_interface_property ip_clk CMSIS_SVD_VARIABLES ""
set_interface_property ip_clk SVD_ADDRESS_GROUP ""
add_interface_port ip_clk IPCORE_CLK clk Input 1

# connection point ip_rst
add_interface ip_rst reset end
set_interface_property ip_rst associatedClock ip_clk
set_interface_property ip_rst synchronousEdges DEASSERT
set_interface_property ip_rst ENABLED true
set_interface_property ip_rst EXPORT_OF ""
set_interface_property ip_rst PORT_NAME_MAP ""
set_interface_property ip_rst CMSIS_SVD_VARIABLES ""
set_interface_property ip_rst SVD_ADDRESS_GROUP ""
add_interface_port ip_rst IPCORE_RESETN reset_n Input 1

## AXI4 Bus
# connection point axi_clk
add_interface axi_clk clock end
set_interface_property axi_clk clockRate 0
set_interface_property axi_clk ENABLED true
set_interface_property axi_clk EXPORT_OF ""
set_interface_property axi_clk PORT_NAME_MAP ""
set_interface_property axi_clk CMSIS_SVD_VARIABLES ""
set_interface_property axi_clk SVD_ADDRESS_GROUP ""
add_interface_port axi_clk AXI4_ACLK clk Input 1

# connection point axi_reset
add_interface axi_reset reset end
set_interface_property axi_reset associatedClock axi_clk
set_interface_property axi_reset synchronousEdges DEASSERT
set_interface_property axi_reset ENABLED true
set_interface_property axi_reset EXPORT_OF ""
set_interface_property axi_reset PORT_NAME_MAP ""
set_interface_property axi_reset CMSIS_SVD_VARIABLES ""
set_interface_property axi_reset SVD_ADDRESS_GROUP ""
add_interface_port axi_reset AXI4_ARESETN reset_n Input 1

# connection point s_axi
add_interface s_axi axi4 end
set_interface_property s_axi associatedClock axi_clk
set_interface_property s_axi associatedReset axi_reset
set_interface_property s_axi readAcceptanceCapability 1
set_interface_property s_axi writeAcceptanceCapability 1
set_interface_property s_axi combinedAcceptanceCapability 1
set_interface_property s_axi readDataReorderingDepth 1
set_interface_property s_axi bridgesToMaster ""
set_interface_property s_axi ENABLED true
set_interface_property s_axi EXPORT_OF ""
set_interface_property s_axi PORT_NAME_MAP ""
set_interface_property s_axi CMSIS_SVD_VARIABLES ""
set_interface_property s_axi SVD_ADDRESS_GROUP ""
add_interface_port s_axi AXI4_AWID awid Input 12
add_interface_port s_axi AXI4_AWADDR awaddr Input 16
add_interface_port s_axi AXI4_AWLEN awlen Input 8
add_interface_port s_axi AXI4_AWSIZE awsize Input 3
add_interface_port s_axi AXI4_AWBURST awburst Input 2
add_interface_port s_axi AXI4_AWLOCK awlock Input 1
add_interface_port s_axi AXI4_AWCACHE awcache Input 4
add_interface_port s_axi AXI4_AWPROT awprot Input 3
add_interface_port s_axi AXI4_AWVALID awvalid Input 1
add_interface_port s_axi AXI4_WDATA wdata Input 32
add_interface_port s_axi AXI4_WSTRB wstrb Input 4
add_interface_port s_axi AXI4_WLAST wlast Input 1
add_interface_port s_axi AXI4_WVALID wvalid Input 1
add_interface_port s_axi AXI4_BREADY bready Input 1
add_interface_port s_axi AXI4_ARID arid Input 12
add_interface_port s_axi AXI4_ARADDR araddr Input 16
add_interface_port s_axi AXI4_ARLEN arlen Input 8
add_interface_port s_axi AXI4_ARSIZE arsize Input 3
add_interface_port s_axi AXI4_ARBURST arburst Input 2
add_interface_port s_axi AXI4_ARLOCK arlock Input 1
add_interface_port s_axi AXI4_ARCACHE arcache Input 4
add_interface_port s_axi AXI4_ARPROT arprot Input 3
add_interface_port s_axi AXI4_ARVALID arvalid Input 1
add_interface_port s_axi AXI4_RREADY rready Input 1
add_interface_port s_axi AXI4_AWREADY awready Output 1
add_interface_port s_axi AXI4_WREADY wready Output 1
add_interface_port s_axi AXI4_BID bid Output 12
add_interface_port s_axi AXI4_BRESP bresp Output 2
add_interface_port s_axi AXI4_BVALID bvalid Output 1
add_interface_port s_axi AXI4_ARREADY arready Output 1
add_interface_port s_axi AXI4_RID rid Output 12
add_interface_port s_axi AXI4_RDATA rdata Output 32
add_interface_port s_axi AXI4_RRESP rresp Output 2
add_interface_port s_axi AXI4_RLAST rlast Output 1
add_interface_port s_axi AXI4_RVALID rvalid Output 1

## External Ports
# connection point avalon_sink_valid
add_interface avalon_sink_valid conduit end
set_interface_property avalon_sink_valid associatedClock ip_clk
set_interface_property avalon_sink_valid associatedReset ip_rst
set_interface_property avalon_sink_valid ENABLED true
set_interface_property avalon_sink_valid EXPORT_OF ""
set_interface_property avalon_sink_valid PORT_NAME_MAP ""
set_interface_property avalon_sink_valid CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sink_valid SVD_ADDRESS_GROUP ""
add_interface_port avalon_sink_valid avalon_sink_valid pin Input 1

# connection point avalon_sink_data
add_interface avalon_sink_data conduit end
set_interface_property avalon_sink_data associatedClock ip_clk
set_interface_property avalon_sink_data associatedReset ip_rst
set_interface_property avalon_sink_data ENABLED true
set_interface_property avalon_sink_data EXPORT_OF ""
set_interface_property avalon_sink_data PORT_NAME_MAP ""
set_interface_property avalon_sink_data CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sink_data SVD_ADDRESS_GROUP ""
add_interface_port avalon_sink_data avalon_sink_data pin Input 32

# connection point avalon_sink_channel
add_interface avalon_sink_channel conduit end
set_interface_property avalon_sink_channel associatedClock ip_clk
set_interface_property avalon_sink_channel associatedReset ip_rst
set_interface_property avalon_sink_channel ENABLED true
set_interface_property avalon_sink_channel EXPORT_OF ""
set_interface_property avalon_sink_channel PORT_NAME_MAP ""
set_interface_property avalon_sink_channel CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sink_channel SVD_ADDRESS_GROUP ""
add_interface_port avalon_sink_channel avalon_sink_channel pin Input 2

# connection point avalon_sink_error
add_interface avalon_sink_error conduit end
set_interface_property avalon_sink_error associatedClock ip_clk
set_interface_property avalon_sink_error associatedReset ip_rst
set_interface_property avalon_sink_error ENABLED true
set_interface_property avalon_sink_error EXPORT_OF ""
set_interface_property avalon_sink_error PORT_NAME_MAP ""
set_interface_property avalon_sink_error CMSIS_SVD_VARIABLES ""
set_interface_property avalon_sink_error SVD_ADDRESS_GROUP ""
add_interface_port avalon_sink_error avalon_sink_error pin Input 2

# connection point register_control_left_gain
add_interface register_control_left_gain conduit end
set_interface_property register_control_left_gain associatedClock ip_clk
set_interface_property register_control_left_gain associatedReset ip_rst
set_interface_property register_control_left_gain ENABLED true
set_interface_property register_control_left_gain EXPORT_OF ""
set_interface_property register_control_left_gain PORT_NAME_MAP ""
set_interface_property register_control_left_gain CMSIS_SVD_VARIABLES ""
set_interface_property register_control_left_gain SVD_ADDRESS_GROUP ""
add_interface_port register_control_left_gain register_control_left_gain pin Input 32

# connection point register_control_right_gain
add_interface register_control_right_gain conduit end
set_interface_property register_control_right_gain associatedClock ip_clk
set_interface_property register_control_right_gain associatedReset ip_rst
set_interface_property register_control_right_gain ENABLED true
set_interface_property register_control_right_gain EXPORT_OF ""
set_interface_property register_control_right_gain PORT_NAME_MAP ""
set_interface_property register_control_right_gain CMSIS_SVD_VARIABLES ""
set_interface_property register_control_right_gain SVD_ADDRESS_GROUP ""
add_interface_port register_control_right_gain register_control_right_gain pin Input 32

# connection point avalon_source_valid
add_interface avalon_source_valid conduit end
set_interface_property avalon_source_valid associatedClock ip_clk
set_interface_property avalon_source_valid associatedReset ip_rst
set_interface_property avalon_source_valid ENABLED true
set_interface_property avalon_source_valid EXPORT_OF ""
set_interface_property avalon_source_valid PORT_NAME_MAP ""
set_interface_property avalon_source_valid CMSIS_SVD_VARIABLES ""
set_interface_property avalon_source_valid SVD_ADDRESS_GROUP ""
add_interface_port avalon_source_valid avalon_source_valid pin Output 1

# connection point avalon_source_data
add_interface avalon_source_data conduit end
set_interface_property avalon_source_data associatedClock ip_clk
set_interface_property avalon_source_data associatedReset ip_rst
set_interface_property avalon_source_data ENABLED true
set_interface_property avalon_source_data EXPORT_OF ""
set_interface_property avalon_source_data PORT_NAME_MAP ""
set_interface_property avalon_source_data CMSIS_SVD_VARIABLES ""
set_interface_property avalon_source_data SVD_ADDRESS_GROUP ""
add_interface_port avalon_source_data avalon_source_data pin Output 32

# connection point avalon_source_channel
add_interface avalon_source_channel conduit end
set_interface_property avalon_source_channel associatedClock ip_clk
set_interface_property avalon_source_channel associatedReset ip_rst
set_interface_property avalon_source_channel ENABLED true
set_interface_property avalon_source_channel EXPORT_OF ""
set_interface_property avalon_source_channel PORT_NAME_MAP ""
set_interface_property avalon_source_channel CMSIS_SVD_VARIABLES ""
set_interface_property avalon_source_channel SVD_ADDRESS_GROUP ""
add_interface_port avalon_source_channel avalon_source_channel pin Output 2

# connection point avalon_source_error
add_interface avalon_source_error conduit end
set_interface_property avalon_source_error associatedClock ip_clk
set_interface_property avalon_source_error associatedReset ip_rst
set_interface_property avalon_source_error ENABLED true
set_interface_property avalon_source_error EXPORT_OF ""
set_interface_property avalon_source_error PORT_NAME_MAP ""
set_interface_property avalon_source_error CMSIS_SVD_VARIABLES ""
set_interface_property avalon_source_error SVD_ADDRESS_GROUP ""
add_interface_port avalon_source_error avalon_source_error pin Output 2

