vmap work ../work

vmap -c
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_uminus_single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_gain_pow2_single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_convert_double2single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_sub_single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_add_single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_add2_single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_div_single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_nfp_tan_single.vhd
vcom  ur_ear_fpga_sim_calc_c1_coefficients_calc_c1_coefficients.vhd
