-- -------------------------------------------------------------
-- 
-- File Name: D:\NIH3Repo\simulink_models\models\ur_ear_fpga\hdlsrc\ur_ear_fpga_sim\redocking_site\ur_ear_fpga_sim_redocking_site_redocking_site.vhd
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ur_ear_fpga_sim_redocking_site_redocking_site
-- Source Path: redocking_site
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ur_ear_fpga_sim_redocking_site_redocking_site IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        synout                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        uriRandNum                        :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        redockRandNum                     :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        TrefRandNum                       :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        t_rel                             :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        tabs                              :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        nSites                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        tdres                             :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        t_rd_init                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        tau_rd                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        spout                             :   OUT   std_logic;
        sptime                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
        recalculate_redocking             :   OUT   std_logic
        );
END ur_ear_fpga_sim_redocking_site_redocking_site;


ARCHITECTURE rtl OF ur_ear_fpga_sim_redocking_site_redocking_site IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT ur_ear_fpga_sim_redocking_site_Redock_Component
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          randNum                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          recalculate                     :   IN    std_logic;
          current_redocking_period        :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          oneSiteRedock                   :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_Elapsed_Time_Component
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          tdres                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          reset_1                         :   IN    std_logic;
          elapsed_time                    :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_nfp_relop_single_block
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out1                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_Xsum_Component
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          synout                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nSites                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          reset_1                         :   IN    std_logic;
          increment                       :   IN    std_logic;
          Xsum                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_unitRateInterval_Component
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          randNum                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          tdres                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          recalculate                     :   IN    std_logic;
          unitRateInterval                :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_nfp_relop_single_block1
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out1                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_Current_Release_Component
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          previous_release_times          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          recalculate                     :   IN    std_logic;
          elapsed_time                    :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          t_rd_init                       :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          current_release_times           :   OUT   std_logic_vector(31 DOWNTO 0);  -- single
          prev_times                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_cal_trel_k
    PORT( synout                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          trel                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          trel_k                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_calc_Tref
    PORT( trel_k                          :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          randData                        :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          tabs                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Tref                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_Current_Refactory_Component
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          current_release_times           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Tref                            :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          recalculate                     :   IN    std_logic;
          current_refactory_period        :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_nfp_recip_single
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_nfp_mul_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_nfp_round_single
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ur_ear_fpga_sim_redocking_site_Redock_Component
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_Redock_Component(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_Elapsed_Time_Component
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_Elapsed_Time_Component(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_nfp_relop_single_block
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_nfp_relop_single_block(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_Xsum_Component
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_Xsum_Component(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_unitRateInterval_Component
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_unitRateInterval_Component(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_nfp_relop_single_block1
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_nfp_relop_single_block1(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_Current_Release_Component
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_Current_Release_Component(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_cal_trel_k
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_cal_trel_k(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_calc_Tref
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_calc_Tref(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_Current_Refactory_Component
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_Current_Refactory_Component(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_nfp_recip_single
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_nfp_recip_single(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_nfp_mul_single
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_nfp_mul_single(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_nfp_round_single
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_nfp_round_single(rtl);

  FOR ALL : ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0
    USE ENTITY work.ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0(rtl);

  -- Signals
  SIGNAL Less_Than_out1                   : std_logic;
  SIGNAL Redock_Component_out1            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Elapsed_Time_Component_out1      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL GreaterThan_out1                 : std_logic;
  SIGNAL Xsum_Component_out1              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL unitRateInterval_Component_out1  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Less_Than_out1_1                 : std_logic;
  SIGNAL Current_Release_Component_out2   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Current_Release_Component_out1   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL cal_trel_k_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL calc_Tref_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL GreaterThanOrEqual1_out1         : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL Current_Refactory_Component_out1 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL GreaterThanOrEqual1_out1_1       : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL Constant_out1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Switch_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Delay2_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide1_recip_out                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide_recip_out                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Round_out1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Data_Type_Conversion_out1        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Data_Type_Conversion_out1_unsigned : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Divide1_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Round1_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Data_Type_Conversion1_out1       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Data_Type_Conversion1_out1_unsigned : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Equal_relop1                     : std_logic;

BEGIN
  -- Change from GTEQ to LT for formatting
  -- 
  -- Line 606
  -- 
  -- Lines 570 - 572
  -- 
  -- Line 599

  u_Redock_Component : ur_ear_fpga_sim_redocking_site_Redock_Component
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              randNum => redockRandNum,  -- single
              recalculate => Less_Than_out1,
              current_redocking_period => tau_rd,  -- single
              oneSiteRedock => Redock_Component_out1  -- single
              );

  u_Elapsed_Time_Component : ur_ear_fpga_sim_redocking_site_Elapsed_Time_Component
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              tdres => tdres,  -- single
              reset_1 => Less_Than_out1,
              elapsed_time => Elapsed_Time_Component_out1  -- single
              );

  u_nfp_relop_comp : ur_ear_fpga_sim_redocking_site_nfp_relop_single_block
    PORT MAP( nfp_in1 => Elapsed_Time_Component_out1,  -- ufix32
              nfp_in2 => Redock_Component_out1,  -- ufix32
              nfp_out1 => GreaterThan_out1
              );

  u_Xsum_Component : ur_ear_fpga_sim_redocking_site_Xsum_Component
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              synout => synout,  -- single
              nSites => nSites,  -- single
              reset_1 => Less_Than_out1,
              increment => GreaterThan_out1,
              Xsum => Xsum_Component_out1  -- single
              );

  u_unitRateInterval_Component : ur_ear_fpga_sim_redocking_site_unitRateInterval_Component
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              randNum => uriRandNum,  -- single
              tdres => tdres,  -- single
              recalculate => Less_Than_out1,
              unitRateInterval => unitRateInterval_Component_out1  -- single
              );

  u_nfp_relop_comp_1 : ur_ear_fpga_sim_redocking_site_nfp_relop_single_block1
    PORT MAP( nfp_in1 => unitRateInterval_Component_out1,  -- ufix32
              nfp_in2 => Xsum_Component_out1,  -- ufix32
              nfp_out1 => Less_Than_out1_1
              );

  u_Current_Release_Component : ur_ear_fpga_sim_redocking_site_Current_Release_Component
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              previous_release_times => Current_Release_Component_out2,  -- single
              recalculate => Less_Than_out1,
              elapsed_time => Elapsed_Time_Component_out1,  -- single
              t_rd_init => t_rd_init,  -- single
              current_release_times => Current_Release_Component_out1,  -- single
              prev_times => Current_Release_Component_out2  -- single
              );

  u_cal_trel_k : ur_ear_fpga_sim_redocking_site_cal_trel_k
    PORT MAP( synout => synout,  -- single
              trel => t_rel,  -- single
              trel_k => cal_trel_k_out1  -- single
              );

  u_calc_Tref : ur_ear_fpga_sim_redocking_site_calc_Tref
    PORT MAP( trel_k => cal_trel_k_out1,  -- single
              randData => TrefRandNum,  -- single
              tabs => tabs,  -- single
              Tref => calc_Tref_out1  -- single
              );

  u_Current_Refactory_Component : ur_ear_fpga_sim_redocking_site_Current_Refactory_Component
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              current_release_times => Current_Release_Component_out1,  -- single
              Tref => calc_Tref_out1,  -- single
              recalculate => AND1_out1,
              current_refactory_period => Current_Refactory_Component_out1  -- single
              );

  u_nfp_relop_comp_2 : ur_ear_fpga_sim_redocking_site_nfp_relop_single_block
    PORT MAP( nfp_in1 => Current_Release_Component_out1,  -- ufix32
              nfp_in2 => Current_Refactory_Component_out1,  -- ufix32
              nfp_out1 => GreaterThanOrEqual1_out1_1
              );

  u_nfp_recip_comp : ur_ear_fpga_sim_redocking_site_nfp_recip_single
    PORT MAP( nfp_in => tdres,  -- ufix32
              nfp_out => Divide1_recip_out  -- ufix32
              );

  u_nfp_recip_comp_1 : ur_ear_fpga_sim_redocking_site_nfp_recip_single
    PORT MAP( nfp_in => tdres,  -- ufix32
              nfp_out => Divide_recip_out  -- ufix32
              );

  u_nfp_mul_comp : ur_ear_fpga_sim_redocking_site_nfp_mul_single
    PORT MAP( nfp_in1 => Delay2_out1,  -- ufix32
              nfp_in2 => Divide_recip_out,  -- ufix32
              nfp_out => Divide_out1  -- ufix32
              );

  u_nfp_round_comp : ur_ear_fpga_sim_redocking_site_nfp_round_single
    PORT MAP( nfp_in => Divide_out1,  -- ufix32
              nfp_out => Round_out1  -- ufix32
              );

  u_redocking_site_nfp_convert_single_to_fix_32_En0 : ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0
    PORT MAP( nfp_in => Round_out1,  -- ufix32
              nfp_out => Data_Type_Conversion_out1  -- ufix32
              );

  u_nfp_mul_comp_1 : ur_ear_fpga_sim_redocking_site_nfp_mul_single
    PORT MAP( nfp_in1 => Elapsed_Time_Component_out1,  -- ufix32
              nfp_in2 => Divide1_recip_out,  -- ufix32
              nfp_out => Divide1_out1  -- ufix32
              );

  u_nfp_round_comp_1 : ur_ear_fpga_sim_redocking_site_nfp_round_single
    PORT MAP( nfp_in => Divide1_out1,  -- ufix32
              nfp_out => Round1_out1  -- ufix32
              );

  u_redocking_site_nfp_convert_single_to_fix_32_En0_1 : ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0
    PORT MAP( nfp_in => Round1_out1,  -- ufix32
              nfp_out => Data_Type_Conversion1_out1  -- ufix32
              );

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Less_Than_out1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_2048_0 = '1' THEN
        Less_Than_out1 <= Less_Than_out1_1;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  AND1_out1 <= GreaterThanOrEqual1_out1 AND Less_Than_out1;

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      GreaterThanOrEqual1_out1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_2048_0 = '1' THEN
        GreaterThanOrEqual1_out1 <= GreaterThanOrEqual1_out1_1;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  AND_out1 <= Less_Than_out1 AND GreaterThanOrEqual1_out1;

  spout <= AND_out1;

  Constant_out1 <= X"00000000";

  
  Switch_out1 <= Constant_out1 WHEN AND_out1 = '0' ELSE
      Current_Release_Component_out1;

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= X"00000000";
    ELSIF rising_edge(clk) THEN
      IF enb_1_2048_0 = '1' THEN
        Delay2_out1 <= Redock_Component_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Data_Type_Conversion_out1_unsigned <= unsigned(Data_Type_Conversion_out1);

  Data_Type_Conversion1_out1_unsigned <= unsigned(Data_Type_Conversion1_out1);

  
  Equal_relop1 <= '1' WHEN Data_Type_Conversion_out1_unsigned = Data_Type_Conversion1_out1_unsigned ELSE
      '0';

  recalculate_redocking <= Equal_relop1;

  sptime <= Switch_out1;

END rtl;

