-- -------------------------------------------------------------
-- 
-- File Name: C:\Flat Earth\fpga-open-speech-tools\simulink_models\models\pFIR_Testing\hdlsrc\pFIR_Testing\pFIR_Testing_Programmable_Upclocked_FIR.vhd
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pFIR_Testing_Programmable_Upclocked_FIR
-- Source Path: pFIR_Testing/dataplane/Test FIR with Custom FIR Libraries Sample Based Filtering/Left Channel Processing/Programmable 
-- Upclocked FI
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY pFIR_Testing_Programmable_Upclocked_FIR IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        enb_1_4_1                         :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        Data_in                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        Valid_in                          :   IN    std_logic;
        Wr_Data                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        Wr_Addr                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Wr_En                             :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Data_out                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        Valid_out                         :   OUT   std_logic
        );
END pFIR_Testing_Programmable_Upclocked_FIR;


ARCHITECTURE rtl OF pFIR_Testing_Programmable_Upclocked_FIR IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT pFIR_Testing_Addr_Gen
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          Input_Addr                      :   OUT   std_logic_vector(8 DOWNTO 0);  -- ufix9
          Data_History_Rd_addr            :   OUT   std_logic_vector(8 DOWNTO 0);  -- ufix9
          End_of_sample_calc              :   OUT   std_logic;
          b_k_addr                        :   OUT   std_logic_vector(8 DOWNTO 0)  -- ufix9
          );
  END COMPONENT;

  COMPONENT pFIR_Testing_SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          rd_dout                         :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  COMPONENT pFIR_Testing_B_k_Memory_Block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          din_A                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          addr_A                          :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
          we_A                            :   IN    std_logic;
          din_B                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          addr_B                          :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
          we_B                            :   IN    std_logic;
          dout_A                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          dout_B                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En28
          );
  END COMPONENT;

  COMPONENT pFIR_Testing_Multiply_And_Sum
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          x_n_i                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          End_of_sample_calc              :   IN    std_logic;
          b_i                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          Filtered_Output                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          Output_Valid                    :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : pFIR_Testing_Addr_Gen
    USE ENTITY work.pFIR_Testing_Addr_Gen(rtl);

  FOR ALL : pFIR_Testing_SimpleDualPortRAM_generic
    USE ENTITY work.pFIR_Testing_SimpleDualPortRAM_generic(rtl);

  FOR ALL : pFIR_Testing_B_k_Memory_Block2
    USE ENTITY work.pFIR_Testing_B_k_Memory_Block2(rtl);

  FOR ALL : pFIR_Testing_Multiply_And_Sum
    USE ENTITY work.pFIR_Testing_Multiply_And_Sum(rtl);

  -- Signals
  SIGNAL Data_in_signed                   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Rate_Transition1_out1            : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Addr_Gen_out1                    : std_logic_vector(8 DOWNTO 0);  -- ufix9
  SIGNAL Addr_Gen_out2                    : std_logic_vector(8 DOWNTO 0);  -- ufix9
  SIGNAL Addr_Gen_out3                    : std_logic;
  SIGNAL Addr_Gen_out4                    : std_logic_vector(8 DOWNTO 0);  -- ufix9
  SIGNAL Addr_Gen_out1_unsigned           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Rate_Transition1_out1_1          : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Addr_Gen_out1_1                  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Rate_Transition2_out1            : std_logic;
  SIGNAL Rate_Transition2_out1_1          : std_logic;
  SIGNAL Addr_Gen_out2_unsigned           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Data_Type_Conversion4_out1       : std_logic;
  SIGNAL Addr_Gen_out2_1                  : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL x_n_i                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Alignment_Delay_out1             : std_logic;
  SIGNAL Wr_Data_signed                   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Rate_Transition3_out1            : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Wr_Addr_unsigned                 : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Rate_Transition4_out1            : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Wr_En_signed                     : signed(31 DOWNTO 0);  -- int32
  SIGNAL Rate_Transition5_out1            : signed(31 DOWNTO 0);  -- int32
  SIGNAL Rate_Transition3_out1_1          : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Rate_Transition4_out1_1          : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Data_Type_Conversion2_out1       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Rate_Transition5_out1_1          : signed(31 DOWNTO 0);  -- int32
  SIGNAL Data_Type_Conversion3_out1       : std_logic;
  SIGNAL Never_write_B2_out1              : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Always_read_B2_out1              : std_logic;
  SIGNAL B_k_Memory_Block2_out1           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL b_i                              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Multiply_And_Sum_out1            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Multiply_And_Sum_out2            : std_logic;
  SIGNAL Multiply_And_Sum_out2_1          : std_logic;
  SIGNAL Multiply_And_Sum_out1_signed     : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Output_memory_out1               : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Output_Stabalizer_out1           : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Rate_Transition_out1             : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Valid_align3_reg                 : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL Valid_align3_out1                : std_logic;
  SIGNAL Rate_Transition7_out1            : std_logic;

BEGIN
  -- B_ks will be programmable eventually.
  -- For the Conference, they will be preset.
  -- 
  -- consider desired output rate
  -- 
  -- try delaying Valid_in by 3 in fast time, set that to Valid_out after rate transition

  u_Addr_Gen : pFIR_Testing_Addr_Gen
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => enb_1_4_0,
              enb_1_2048_0 => enb_1_2048_0,
              Input_Addr => Addr_Gen_out1,  -- ufix9
              Data_History_Rd_addr => Addr_Gen_out2,  -- ufix9
              End_of_sample_calc => Addr_Gen_out3,
              b_k_addr => Addr_Gen_out4  -- ufix9
              );

  u_Input_Data_Circular_Buffer : pFIR_Testing_SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 9,
                 DataWidth => 32
                 )
    PORT MAP( clk => clk,
              enb_1_4_0 => enb_1_4_0,
              wr_din => std_logic_vector(Rate_Transition1_out1_1),
              wr_addr => std_logic_vector(Addr_Gen_out1_1),
              wr_en => Data_Type_Conversion4_out1,
              rd_addr => std_logic_vector(Addr_Gen_out2_1),
              rd_dout => x_n_i
              );

  -- 
  u_B_k_Memory_Block2 : pFIR_Testing_B_k_Memory_Block2
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => enb_1_4_0,
              din_A => std_logic_vector(Rate_Transition3_out1_1),  -- sfix32_En28
              addr_A => std_logic_vector(Data_Type_Conversion2_out1),  -- ufix9
              we_A => Data_Type_Conversion3_out1,
              din_B => std_logic_vector(Never_write_B2_out1),  -- sfix32_En28
              addr_B => Addr_Gen_out4,  -- ufix9
              we_B => Always_read_B2_out1,
              dout_A => B_k_Memory_Block2_out1,  -- sfix32_En28
              dout_B => b_i  -- sfix32_En28
              );

  u_Multiply_And_Sum : pFIR_Testing_Multiply_And_Sum
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => enb_1_4_0,
              x_n_i => x_n_i,  -- sfix32_En28
              End_of_sample_calc => Alignment_Delay_out1,
              b_i => b_i,  -- sfix32_En28
              Filtered_Output => Multiply_And_Sum_out1,  -- sfix32_En28
              Output_Valid => Multiply_And_Sum_out2
              );

  Data_in_signed <= signed(Data_in);

  Rate_Transition1_output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition1_out1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_1 = '1' THEN
        Rate_Transition1_out1 <= Data_in_signed;
      END IF;
    END IF;
  END PROCESS Rate_Transition1_output_process;


  Addr_Gen_out1_unsigned <= unsigned(Addr_Gen_out1);

  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition1_out1_1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Rate_Transition1_out1_1 <= Rate_Transition1_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Addr_Gen_out1_1 <= to_unsigned(16#000#, 9);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Addr_Gen_out1_1 <= Addr_Gen_out1_unsigned;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  Rate_Transition2_output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition2_out1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_1 = '1' THEN
        Rate_Transition2_out1 <= Valid_in;
      END IF;
    END IF;
  END PROCESS Rate_Transition2_output_process;


  PipelineRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition2_out1_1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Rate_Transition2_out1_1 <= Rate_Transition2_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  Addr_Gen_out2_unsigned <= unsigned(Addr_Gen_out2);

  
  Data_Type_Conversion4_out1 <= '1' WHEN Rate_Transition2_out1_1 /= '0' ELSE
      '0';

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Addr_Gen_out2_1 <= to_unsigned(16#000#, 9);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Addr_Gen_out2_1 <= Addr_Gen_out2_unsigned;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  Alignment_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Alignment_Delay_out1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Alignment_Delay_out1 <= Addr_Gen_out3;
      END IF;
    END IF;
  END PROCESS Alignment_Delay_process;


  Wr_Data_signed <= signed(Wr_Data);

  Rate_Transition3_output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition3_out1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_1 = '1' THEN
        Rate_Transition3_out1 <= Wr_Data_signed;
      END IF;
    END IF;
  END PROCESS Rate_Transition3_output_process;


  Wr_Addr_unsigned <= unsigned(Wr_Addr);

  Rate_Transition4_output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition4_out1 <= to_unsigned(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_1 = '1' THEN
        Rate_Transition4_out1 <= Wr_Addr_unsigned;
      END IF;
    END IF;
  END PROCESS Rate_Transition4_output_process;


  Wr_En_signed <= signed(Wr_En);

  Rate_Transition5_output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition5_out1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_1 = '1' THEN
        Rate_Transition5_out1 <= Wr_En_signed;
      END IF;
    END IF;
  END PROCESS Rate_Transition5_output_process;


  PipelineRegister2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition3_out1_1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Rate_Transition3_out1_1 <= Rate_Transition3_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister2_process;


  PipelineRegister3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition4_out1_1 <= to_unsigned(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Rate_Transition4_out1_1 <= Rate_Transition4_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister3_process;


  Data_Type_Conversion2_out1 <= Rate_Transition4_out1_1(8 DOWNTO 0);

  PipelineRegister4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition5_out1_1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Rate_Transition5_out1_1 <= Rate_Transition5_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister4_process;


  
  Data_Type_Conversion3_out1 <= '1' WHEN Rate_Transition5_out1_1 /= to_signed(0, 32) ELSE
      '0';

  Never_write_B2_out1 <= to_signed(0, 32);

  Always_read_B2_out1 <= '0';

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_And_Sum_out2_1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Multiply_And_Sum_out2_1 <= Multiply_And_Sum_out2;
      END IF;
    END IF;
  END PROCESS delayMatch2_process;


  Multiply_And_Sum_out1_signed <= signed(Multiply_And_Sum_out1);

  
  Output_Stabalizer_out1 <= Output_memory_out1 WHEN Multiply_And_Sum_out2_1 = '0' ELSE
      Multiply_And_Sum_out1_signed;

  Output_memory_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Output_memory_out1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Output_memory_out1 <= Output_Stabalizer_out1;
      END IF;
    END IF;
  END PROCESS Output_memory_process;


  Rate_Transition_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition_out1 <= to_signed(0, 32);
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Rate_Transition_out1 <= Output_memory_out1;
      END IF;
    END IF;
  END PROCESS Rate_Transition_process;


  Data_out <= std_logic_vector(Rate_Transition_out1);

  -- 
  -- 
  Valid_align3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Valid_align3_reg <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Valid_align3_reg(0) <= Rate_Transition2_out1_1;
        Valid_align3_reg(1 TO 2) <= Valid_align3_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS Valid_align3_process;

  Valid_align3_out1 <= Valid_align3_reg(2);

  Rate_Transition7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Rate_Transition7_out1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_4_0 = '1' THEN
        Rate_Transition7_out1 <= Valid_align3_out1;
      END IF;
    END IF;
  END PROCESS Rate_Transition7_process;


  Valid_out <= Rate_Transition7_out1;

END rtl;

