-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\mc_gr\Desktop\FPGA Open Speech Tools\simulink_models\models\pFIR_Testing\hdlsrc\pFIR_Testing\pFIR_Testing_Left_Channel_Processing.vhd
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pFIR_Testing_Left_Channel_Processing
-- Source Path: pFIR_Testing/dataplane/Test FIR with Custom FIR Libraries Sample Based Filtering/Left Channel Processing
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.pFIR_Testing_dataplane_pkg.ALL;

ENTITY pFIR_Testing_Left_Channel_Processing IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        enb_1_4_1                         :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        Left_Data_Sink                    :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        register_control_enable           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        left_data_valid                   :   IN    std_logic;
        ram_control_Wr_Data               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        ram_control_RW_Addr               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ram_control_Wr_En                 :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Left_Data_Source                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        Left_Data_Valid_Source            :   OUT   std_logic
        );
END pFIR_Testing_Left_Channel_Processing;


ARCHITECTURE rtl OF pFIR_Testing_Left_Channel_Processing IS

  -- Component Declarations
  COMPONENT pFIR_Testing_Programmable_Upclocked_FIR
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          enb_1_4_1                       :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          Data_in                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          Valid_in                        :   IN    std_logic;
          Wr_Data                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          Wr_Addr                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Wr_En                           :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Data_out                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : pFIR_Testing_Programmable_Upclocked_FIR
    USE ENTITY work.pFIR_Testing_Programmable_Upclocked_FIR(rtl);

  -- Signals
  SIGNAL register_control_enable_signed   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL delayMatch_reg                   : vector_of_signed32(0 TO 3);  -- sfix32 [4]
  SIGNAL register_control_enable_1        : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Left_Data_Sink_signed            : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL delayMatch1_reg                  : vector_of_signed32(0 TO 3);  -- sfix32 [4]
  SIGNAL left_data_sinksource_passthrough : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL left_filtered_out                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Programmable_Upclocked_FIR_out2  : std_logic;
  SIGNAL left_filtered_out_signed         : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Left_Data_Source_1               : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Left_Data_Source_2               : std_logic;

BEGIN
  -- avalon_slave_readdata <= RW_Dout
  -- 
  -- Pass a second avalon interface (data, addr, wr_en) into this?
  -- 
  -- An enabled subsystem
  -- This subsystem only runs when the data valid signal is enabled (asserted)

  u_Programmable_Upclocked_FIR : pFIR_Testing_Programmable_Upclocked_FIR
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              enb_1_4_0 => enb_1_4_0,
              enb_1_4_1 => enb_1_4_1,
              enb_1_2048_0 => enb_1_2048_0,
              Data_in => Left_Data_Sink,  -- sfix32_En28
              Valid_in => left_data_valid,
              Wr_Data => ram_control_Wr_Data,  -- sfix32_En28
              Wr_Addr => ram_control_RW_Addr,  -- uint32
              Wr_En => ram_control_Wr_En,  -- int32
              Data_out => left_filtered_out,  -- sfix32_En28
              Valid_out => Programmable_Upclocked_FIR_out2
              );

  register_control_enable_signed <= signed(register_control_enable);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_signed(0, 32));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= register_control_enable_signed;
        delayMatch_reg(1 TO 3) <= delayMatch_reg(0 TO 2);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  register_control_enable_1 <= delayMatch_reg(3);

  Left_Data_Sink_signed <= signed(Left_Data_Sink);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch1_reg <= (OTHERS => to_signed(0, 32));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        delayMatch1_reg(0) <= Left_Data_Sink_signed;
        delayMatch1_reg(1 TO 3) <= delayMatch1_reg(0 TO 2);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  left_data_sinksource_passthrough <= delayMatch1_reg(3);

  left_filtered_out_signed <= signed(left_filtered_out);

  
  Left_Data_Source_1 <= left_data_sinksource_passthrough WHEN register_control_enable_1 = to_signed(0, 32) ELSE
      left_filtered_out_signed;

  Left_Data_Source <= std_logic_vector(Left_Data_Source_1);

  
  Left_Data_Source_2 <= left_data_valid WHEN register_control_enable_signed = to_signed(0, 32) ELSE
      Programmable_Upclocked_FIR_out2;

  Left_Data_Valid_Source <= Left_Data_Source_2;

END rtl;

