SLStudio.Utils.RemoveHighlighting(get_param('alpha10th_Order_IIR_Filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_alpha10th_Order_IIR_Filter', 'handle'));
annotate_port('gm_alpha10th_Order_IIR_Filter/Unit Delay1', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Unit Delay10', 1, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product13', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product18', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product23', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product8', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum1', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum10', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum11', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum11_outbuff', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum12', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum13', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum13_outbuff', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum16', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum17', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum17_outbuff', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum2', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum3', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum6', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum7', 0, 1, '');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum7_outbuff', 0, 1, '');
