open_system('gm_alpha10th_Order_IIR_Filter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Unit Delay1', 'user1');
annotate_port('gm_alpha10th_Order_IIR_Filter/Unit Delay1', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Unit Delay10', 'user1');
annotate_port('gm_alpha10th_Order_IIR_Filter/Unit Delay10', 1, 1, 'cp : 225.888 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Product', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product', 0, 1, 'cp : 10.716 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Product13', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product13', 0, 1, 'cp : 110.498 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Product18', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product18', 0, 1, 'cp : 152.424 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Product23', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product23', 0, 1, 'cp : 194.35 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Product8', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Product8', 0, 1, 'cp : 68.572 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum1', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum1', 0, 1, 'cp : 26.558 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum10', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum10', 0, 1, 'cp : 126.252 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum11', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum11', 0, 1, 'cp : 142.006 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum11_outbuff', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum11_outbuff', 0, 1, 'cp : 142.006 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum12', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum12', 0, 1, 'cp : 168.178 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum13', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum13', 0, 1, 'cp : 183.932 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum13_outbuff', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum13_outbuff', 0, 1, 'cp : 183.932 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum16', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum16', 0, 1, 'cp : 210.104 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum17', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum17', 0, 1, 'cp : 225.858 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum17_outbuff', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum17_outbuff', 0, 1, 'cp : 225.858 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum2', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum2', 0, 1, 'cp : 42.4 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum3', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum3', 0, 1, 'cp : 58.154 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum3_outbuff', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum3_outbuff', 0, 1, 'cp : 58.154 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum6', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum6', 0, 1, 'cp : 84.326 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum7', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum7', 0, 1, 'cp : 100.08 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_alpha10th_Order_IIR_Filter/Sum7_outbuff', 'user2');
annotate_port('gm_alpha10th_Order_IIR_Filter/Sum7_outbuff', 0, 1, 'cp : 100.08 ns');
