config audioblade_system_altera_avalon_st_adapter_180_u2irali_cfg;
		design audioblade_system_altera_avalon_st_adapter_180_u2irali;
		instance audioblade_system_altera_avalon_st_adapter_180_u2irali.channel_adapter_0 use audioblade_system_channel_adapter_180.audioblade_system_channel_adapter_180_wixceeq;
endconfig

