vlib work
vcom  MNR_dataplane_pkg.vhd
vcom  MNR_Grab_the_Look_behind_Window_and_Calculate_the_Mean.vhd
vcom  MNR_Right_Channel_Processing.vhd
vcom  MNR_Grab_the_Look_behind_Window_and_Calculate_the_Mean_block.vhd
vcom  MNR_Right_Channel_Processing1.vhd
vcom  MNR_Adaptive_Wiener_Filter_Sample_Based_Filtering.vhd
vcom  MNR_dataplane.vhd
