vmap work ../work

vmap -c
vcom  ur_ear_fpga_sim_ihc_lowpass_filter_nfp_uminus_single.vhd
vcom  ur_ear_fpga_sim_ihc_lowpass_filter_nfp_mul_single.vhd
vcom  ur_ear_fpga_sim_ihc_lowpass_filter_nfp_add_single.vhd
vcom  ur_ear_fpga_sim_ihc_lowpass_filter_nfp_sub_single.vhd
vcom  ur_ear_fpga_sim_ihc_lowpass_filter_ihc_lowpass_filter.vhd
