-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\control_path_sim\ohc_nl_boltzman_function\ohc_nl_boltzman_function_ohc_nl_boltzman_function.vhd
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ohc_nl_boltzman_function_ohc_nl_boltzman_function
-- Source Path: ohc_nl_boltzman_function
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ohc_nl_boltzman_function_ohc_nl_boltzman_function IS
  PORT( ohc_nl_boltzman_in                :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        ohc_nl_boltzman_out               :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END ohc_nl_boltzman_function_ohc_nl_boltzman_function;


ARCHITECTURE rtl OF ohc_nl_boltzman_function_ohc_nl_boltzman_function IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT ohc_nl_boltzman_function_nfp_sub_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ohc_nl_boltzman_function_nfp_div_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ohc_nl_boltzman_function_nfp_uminus_single
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ohc_nl_boltzman_function_nfp_exp_single
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ohc_nl_boltzman_function_nfp_add_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ohc_nl_boltzman_function_nfp_mul_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ohc_nl_boltzman_function_nfp_sub_single
    USE ENTITY work.ohc_nl_boltzman_function_nfp_sub_single(rtl);

  FOR ALL : ohc_nl_boltzman_function_nfp_div_single
    USE ENTITY work.ohc_nl_boltzman_function_nfp_div_single(rtl);

  FOR ALL : ohc_nl_boltzman_function_nfp_uminus_single
    USE ENTITY work.ohc_nl_boltzman_function_nfp_uminus_single(rtl);

  FOR ALL : ohc_nl_boltzman_function_nfp_exp_single
    USE ENTITY work.ohc_nl_boltzman_function_nfp_exp_single(rtl);

  FOR ALL : ohc_nl_boltzman_function_nfp_add_single
    USE ENTITY work.ohc_nl_boltzman_function_nfp_add_single(rtl);

  FOR ALL : ohc_nl_boltzman_function_nfp_mul_single
    USE ENTITY work.ohc_nl_boltzman_function_nfp_mul_single(rtl);

  -- Signals
  SIGNAL Constant_out1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Subtract_out1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant3_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Subtract1_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant4_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide1_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Gain1_out1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Math_Function2_out1              : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant1_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Gain_out1                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Math_Function_out1               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant5_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add1_out1                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Product_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant6_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant2_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add4_out1                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide2_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant7_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL out1                             : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Subtract2_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL out_rsvd                         : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  -- Nonlinear Exponential Function
  -- 
  -- Nonlinear Exponential Function

  u_nfp_sub_comp : ohc_nl_boltzman_function_nfp_sub_single
    PORT MAP( nfp_in1 => ohc_nl_boltzman_in,  -- ufix32
              nfp_in2 => Constant_out1,  -- ufix32
              nfp_out => Subtract_out1  -- ufix32
              );

  u_nfp_sub_comp_1 : ohc_nl_boltzman_function_nfp_sub_single
    PORT MAP( nfp_in1 => ohc_nl_boltzman_in,  -- ufix32
              nfp_in2 => Constant3_out1,  -- ufix32
              nfp_out => Subtract1_out1  -- ufix32
              );

  u_nfp_div_comp : ohc_nl_boltzman_function_nfp_div_single
    PORT MAP( nfp_in1 => Subtract1_out1,  -- ufix32
              nfp_in2 => Constant4_out1,  -- ufix32
              nfp_out => Divide1_out1  -- ufix32
              );

  u_nfp_uminus_comp : ohc_nl_boltzman_function_nfp_uminus_single
    PORT MAP( nfp_in => Divide1_out1,  -- ufix32
              nfp_out => Gain1_out1  -- ufix32
              );

  u_nfp_exp_comp : ohc_nl_boltzman_function_nfp_exp_single
    PORT MAP( nfp_in => Gain1_out1,  -- ufix32
              nfp_out => Math_Function2_out1  -- ufix32
              );

  u_nfp_div_comp_1 : ohc_nl_boltzman_function_nfp_div_single
    PORT MAP( nfp_in1 => Subtract_out1,  -- ufix32
              nfp_in2 => Constant1_out1,  -- ufix32
              nfp_out => Divide_out1  -- ufix32
              );

  u_nfp_uminus_comp_1 : ohc_nl_boltzman_function_nfp_uminus_single
    PORT MAP( nfp_in => Divide_out1,  -- ufix32
              nfp_out => Gain_out1  -- ufix32
              );

  u_nfp_exp_comp_1 : ohc_nl_boltzman_function_nfp_exp_single
    PORT MAP( nfp_in => Gain_out1,  -- ufix32
              nfp_out => Math_Function_out1  -- ufix32
              );

  u_nfp_add_comp : ohc_nl_boltzman_function_nfp_add_single
    PORT MAP( nfp_in1 => Math_Function2_out1,  -- ufix32
              nfp_in2 => Constant5_out1,  -- ufix32
              nfp_out => Add1_out1  -- ufix32
              );

  u_nfp_mul_comp : ohc_nl_boltzman_function_nfp_mul_single
    PORT MAP( nfp_in1 => Math_Function_out1,  -- ufix32
              nfp_in2 => Add1_out1,  -- ufix32
              nfp_out => Product_out1  -- ufix32
              );

  u_nfp_add_comp_1 : ohc_nl_boltzman_function_nfp_add_single
    PORT MAP( nfp_in1 => Product_out1,  -- ufix32
              nfp_in2 => Constant2_out1,  -- ufix32
              nfp_out => Add4_out1  -- ufix32
              );

  u_nfp_div_comp_2 : ohc_nl_boltzman_function_nfp_div_single
    PORT MAP( nfp_in1 => Constant6_out1,  -- ufix32
              nfp_in2 => Add4_out1,  -- ufix32
              nfp_out => Divide2_out1  -- ufix32
              );

  u_nfp_sub_comp_2 : ohc_nl_boltzman_function_nfp_sub_single
    PORT MAP( nfp_in1 => Divide2_out1,  -- ufix32
              nfp_in2 => Constant7_out1,  -- ufix32
              nfp_out => out1  -- ufix32
              );

  u_nfp_div_comp_3 : ohc_nl_boltzman_function_nfp_div_single
    PORT MAP( nfp_in1 => out1,  -- ufix32
              nfp_in2 => Subtract2_out1,  -- ufix32
              nfp_out => out_rsvd  -- ufix32
              );

  Constant_out1 <= X"40f2efe0";

  Constant3_out1 <= X"40a00000";

  Constant4_out1 <= X"40a00000";

  Constant1_out1 <= X"41400000";

  Constant5_out1 <= X"3f800000";

  Constant6_out1 <= X"3f800000";

  Constant2_out1 <= X"3f800000";

  Constant7_out1 <= X"3e000000";

  Subtract2_out1 <= X"3f600000";

  ohc_nl_boltzman_out <= out_rsvd;

END rtl;

