open_system('gm_HA_sys8');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left', 0, 1, 'cp : 57.38 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1', 1, 1, 'cp : 57.38 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Add1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Add1', 0, 1, 'cp : 57.38 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_in0_dtc', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_in0_dtc', 0, 1, 'cp : 5.807 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/bitslice01', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/bitslice01', 0, 1, 'cp : 5.807 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_mul', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_mul', 0, 1, 'cp : 10.378 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_mul_out_dtc', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_mul_out_dtc', 0, 1, 'cp : 10.378 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_shift', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_shift', 0, 1, 'cp : 10.378 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_add', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_add', 0, 1, 'cp : 22.865 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_add2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_add2', 0, 1, 'cp : 35.352 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_add_out_dtc', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_add_out_dtc', 0, 1, 'cp : 50.045 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_add_out_dtc1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_add_out_dtc1', 0, 1, 'cp : 48.004 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_in0_dtc_in_abs', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_in0_dtc_in_abs', 0, 1, 'cp : 5.807 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/Product1_split_add_out_dtc2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/Product1_split_add_out_dtc2', 0, 1, 'cp : 35.352 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/SwitchComp', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/SwitchComp', 0, 1, 'cp : 48.004 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/SwitchComp_in2_uminus', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/SwitchComp_in2_uminus', 0, 1, 'cp : 47.839 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/delayMatch6', 'user1');
annotate_port('gm_HA_sys8/HA_LR/HA_left/delayMatch6', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1/FIRInterpolator1', 'user1');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1/FIRInterpolator1', 1, 1, 'cp : 57.38 ns');
