vlib work
vcom  HA_LR_pkg.vhd
vcom  FIRDecimator1.vhd
vcom  FIRBandPass4.vhd
vcom  FIRDecimator2.vhd
vcom  FIRBandPass3.vhd
vcom  FIRDecimator3.vhd
vcom  FIRBandPass2.vhd
vcom  FIRDecimator4.vhd
vcom  FIRBandPass1.vhd
vcom  FIRInterpolator4.vhd
vcom  FIRInterpolator3.vhd
vcom  FIRInterpolator2.vhd
vcom  FIRInterpolator1.vhd
vcom  FIRDecimator1_block.vhd
vcom  FIRBandPass4_block.vhd
vcom  FIRDecimator2_block.vhd
vcom  FIRBandPass3_block.vhd
vcom  FIRDecimator3_block.vhd
vcom  FIRBandPass2_block.vhd
vcom  FIRDecimator4_block.vhd
vcom  FIRBandPass1_block.vhd
vcom  FIRInterpolator4_block.vhd
vcom  FIRInterpolator3_block.vhd
vcom  FIRInterpolator2_block.vhd
vcom  FIRInterpolator1_block.vhd
vcom  HA_left.vhd
vcom  HA_right.vhd
vcom  HA_LR_tc.vhd
vcom  HA_LR.vhd
