open_system('HA_sys8');
open_system('gm_HA_sys8');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRDecimator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRDecimator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRDecimator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRDecimator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1/FIRBandPass1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1/FIRBandPass1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2/FIRBandPass2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2/FIRBandPass2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3/FIRBandPass3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3/FIRBandPass3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4/FIRBandPass4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4/FIRBandPass4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRBandPass4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRBandPass4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_left/FIRDecimator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRDecimator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1/FIRInterpolator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator1/FIRInterpolator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2/FIRInterpolator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2/FIRInterpolator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3/FIRInterpolator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3/FIRInterpolator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4/FIRInterpolator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4/FIRInterpolator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_left/FIRInterpolator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left/FIRInterpolator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1/FIRBandPass1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1/FIRBandPass1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2/FIRBandPass2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2/FIRBandPass2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3/FIRBandPass3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3/FIRBandPass3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4/FIRBandPass4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4/FIRBandPass4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRBandPass4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRBandPass4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('HA_sys8/HA_LR/HA_right/FIRDecimator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRDecimator4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator1/FIRInterpolator1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator1/FIRInterpolator1', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator1', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2/FIRInterpolator2', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2/FIRInterpolator2', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator2', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3/FIRInterpolator3', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3/FIRInterpolator3', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator3', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4/FIRInterpolator4', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4/FIRInterpolator4', 1, 1, 'Block not characterized');
hilite_system('HA_sys8/HA_LR/HA_right/FIRInterpolator4', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right/FIRInterpolator4', 1, 1, 'Block not characterized');
