open_system('HA_sys8');
open_system('gm_HA_sys8');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('HA_sys8/HA_LR/HA_left', 'user2');
annotate_port('HA_sys8/HA_LR/HA_left', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('HA_sys8/HA_LR/HA_right', 'user2');
annotate_port('HA_sys8/HA_LR/HA_right', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass1_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass2_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass3_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRBandPass4_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator2_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator3_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_left/FIRInterpolator4_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass1_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass2_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass3_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRBandPass4_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator2_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator3_reg', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4_reg', 'user2');
annotate_port('gm_HA_sys8/HA_LR/HA_right/FIRInterpolator4_reg', 1, 1, 'Obstacle to clock-rate pipelining');
