open_system('gm_HA_sys8');
open_system('HA_sys8');
clearhighlighting;
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/Gain_left_split_mul', 'user1');
annotate_port('gm_HA_sys8/HA_LR/Gain_left_split_mul', 0, 1, 'Sharing Group 1');
hilite_system('HA_sys8/HA_LR/Gain_left', 'user1');
annotate_port('HA_sys8/HA_LR/Gain_left', 0, 1, 'Sharing Group 1');
hilite_system('HA_sys8/HA_LR/Gain_left', 'user1');
annotate_port('HA_sys8/HA_LR/Gain_left', 0, 1, 'Sharing Group 1');
hilite_system('HA_sys8/HA_LR/Gain_right', 'user1');
annotate_port('HA_sys8/HA_LR/Gain_right', 0, 1, 'Sharing Group 1');
hilite_system('HA_sys8/HA_LR/Gain_right', 'user1');
annotate_port('HA_sys8/HA_LR/Gain_right', 0, 1, 'Sharing Group 1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/Gain_left_split_mul1', 'user2');
annotate_port('gm_HA_sys8/HA_LR/Gain_left_split_mul1', 0, 1, 'Sharing Group 2');
hilite_system('HA_sys8/HA_LR/Gain_left', 'user2');
annotate_port('HA_sys8/HA_LR/Gain_left', 0, 1, 'Sharing Group 2');
hilite_system('HA_sys8/HA_LR/Gain_right', 'user2');
annotate_port('HA_sys8/HA_LR/Gain_right', 0, 1, 'Sharing Group 2');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_HA_sys8/HA_LR/Gain_left_split_mul2', 'user3');
annotate_port('gm_HA_sys8/HA_LR/Gain_left_split_mul2', 0, 1, 'Sharing Group 3');
hilite_system('HA_sys8/HA_LR/Gain_left', 'user3');
annotate_port('HA_sys8/HA_LR/Gain_left', 0, 1, 'Sharing Group 3');
hilite_system('HA_sys8/HA_LR/Gain_right', 'user3');
annotate_port('HA_sys8/HA_LR/Gain_right', 0, 1, 'Sharing Group 3');
