vmap work ../work

vmap -c
vcom  ur_ear_fpga_sim_spike_generator_nfp_abs_double.vhd
vcom  ur_ear_fpga_sim_spike_generator_nfp_convert_fix_10_En0_to_single.vhd
vcom  ur_ear_fpga_sim_spike_generator_nfp_mul_single.vhd
vcom  ur_ear_fpga_sim_spike_generator_nfp_add_single.vhd
vcom  ur_ear_fpga_sim_spike_generator_Current_Redock_Component.vhd
vcom  ur_ear_fpga_sim_spike_generator_nfp_div_single.vhd
vcom  ur_ear_fpga_sim_spike_generator_nfp_sub_single.vhd
vcom  ur_ear_fpga_sim_spike_generator_Correct_Redocking_Period.vhd
vcom  ur_ear_fpga_sim_spike_generator_nfp_convert_double2single.vhd
vcom  ur_ear_fpga_sim_spike_generator_Redocking_Calculation.vhd
vcom  ur_ear_fpga_sim_spike_generator_spike_generator.vhd
