SLStudio.Utils.RemoveHighlighting(get_param('calc_tau', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_calc_tau', 'handle'));
annotate_port('gm_calc_tau/Delay1', 1, 1, '');
annotate_port('calc_tau/Delay1', 1, 1, '');
annotate_port('gm_calc_tau/read address generator', 0, 1, '');
annotate_port('calc_tau/read address generator', 0, 1, '');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, '');
annotate_port('gm_calc_tau/Calculate tauc1', 0, 1, '');
annotate_port('gm_calc_tau/Subtract', 0, 1, '');
annotate_port('gm_calc_tau/Reciprocal_recip', 0, 1, '');
annotate_port('gm_calc_tau/Calculate tauc1/Add', 0, 1, '');
annotate_port('gm_calc_tau/Calculate tauc1/Subtract', 0, 1, '');
annotate_port('gm_calc_tau/Calculate tauc1/Product_to_gain', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('cp_wideband_gammatone_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_cp_wideband_gammatone_filter', 'handle'));
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Complex to Real-Imag', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Product_ReIm2Complex', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Product1_C2ReIm_1', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Product1_ReIm2Complex', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Product', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Product11', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Product1_AC_minus_BD', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/MATLAB Function1', 1, 1, '');
annotate_port('cp_wideband_gammatone_filter/MATLAB Function1', 1, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout/Product1', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout/Product', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout/Gain', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, '');
annotate_port('cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8_C2ReIm', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8_ReIm2Complex', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7_C2ReIm', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7_ReIm2Complex', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4_C2ReIm', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4_ReIm2Complex', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum6', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum6_outbuff', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum5', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum4', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum4_outbuff', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum3', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum2', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum2_outbuff', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum1', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7', 0, 1, '');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('ohc_lowpass_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ohc_lowpass_filter', 'handle'));
annotate_port('gm_ohc_lowpass_filter/Unit Delay', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay', 1, 1, '');
annotate_port('gm_ohc_lowpass_filter/Unit Delay1', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay1', 1, 1, '');
annotate_port('gm_ohc_lowpass_filter/Unit Delay3', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay3', 1, 1, '');
annotate_port('gm_ohc_lowpass_filter/Unit Delay5', 1, 1, '');
annotate_port('ohc_lowpass_filter/Unit Delay5', 1, 1, '');
annotate_port('gm_ohc_lowpass_filter/Sum7', 0, 1, '');
annotate_port('gm_ohc_lowpass_filter/Sum7_outbuff', 0, 1, '');
annotate_port('gm_ohc_lowpass_filter/Sum6', 0, 1, '');
annotate_port('gm_ohc_lowpass_filter/Product8', 0, 1, '');
annotate_port('gm_ohc_lowpass_filter/Sum3', 0, 1, '');
annotate_port('gm_ohc_lowpass_filter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_ohc_lowpass_filter/Product3', 0, 1, '');
annotate_port('gm_ohc_lowpass_filter/Sum2', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('ohc_nl_boltzman_function', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ohc_nl_boltzman_function', 'handle'));
annotate_port('gm_ohc_nl_boltzman_function/Gain1_unaryminus', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Divide3', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Subtract3', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Divide2', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Add4', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Product', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Subtract1', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Divide1', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Math Function2', 0, 1, '');
annotate_port('gm_ohc_nl_boltzman_function/Add1', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('ohc_nonlinear_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ohc_nonlinear_filter', 'handle'));
annotate_port('gm_ohc_nonlinear_filter/Saturation_Switch1', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Saturation_Switch2', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Gain2_unaryminus', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Saturation_UpperRelop', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Product4', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Product4_outbuff', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Add3', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Product3', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Exp', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Divide1', 0, 1, '');
annotate_port('gm_ohc_nonlinear_filter/Abs', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('outer_hair_cell', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_outer_hair_cell', 'handle'));
annotate_port('gm_outer_hair_cell/Model', 0, 1, '');
annotate_port('gm_outer_hair_cell/Model1', 0, 1, '');
annotate_port('gm_outer_hair_cell/Model1', 1, 1, '');
annotate_port('outer_hair_cell/Model1', 1, 1, '');
annotate_port('gm_outer_hair_cell/Model2', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('control_path', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_control_path', 'handle'));
annotate_port('gm_control_path/Model', 0, 1, '');
annotate_port('gm_control_path/Model', 1, 1, '');
annotate_port('control_path/Model', 1, 1, '');
annotate_port('gm_control_path/Model1', 0, 1, '');
annotate_port('gm_control_path/Model2', 0, 1, '');
annotate_port('gm_control_path/Model2', 1, 1, '');
annotate_port('control_path/Model2', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('calc_coeff', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_calc_coeff', 'handle'));
annotate_port('gm_calc_coeff/Multiply1_unaryminus', 0, 1, '');
annotate_port('gm_calc_coeff/Divide2', 0, 1, '');
annotate_port('gm_calc_coeff/Add', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('calc_phase_temp', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_calc_phase_temp', 'handle'));
annotate_port('gm_calc_phase_temp/Multiply_unaryminus', 0, 1, '');
annotate_port('gm_calc_phase_temp/Multiply_unaryminus_outbuff', 0, 1, '');
annotate_port('gm_calc_phase_temp/Divide', 0, 1, '');
annotate_port('gm_calc_phase_temp/Atan', 0, 1, '');
annotate_port('gm_calc_phase_temp/Subtract1', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('calc_temp', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_calc_temp', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('calc_c1_coefficients', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_calc_c1_coefficients', 'handle'));
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=1', 1, 1, '');
annotate_port('calc_c1_coefficients/Phase Calc - i=1', 1, 1, '');
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=2', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=2', 1, 1, '');
annotate_port('calc_c1_coefficients/Phase Calc - i=2', 1, 1, '');
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=3', 1, 1, '');
annotate_port('calc_c1_coefficients/Phase Calc - i=3', 1, 1, '');
annotate_port('gm_calc_c1_coefficients/calc_coeff', 0, 3, '');
annotate_port('gm_calc_c1_coefficients/Multiply', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Multiply_outbuff', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Add2', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Add2_outbuff', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Subtract', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Subtract_outbuff', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Add', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Divide1', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Divide1_outbuff', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Sum1', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Sum2', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Sum3', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Sum4', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Sum5', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Divide', 0, 1, '');
annotate_port('gm_calc_c1_coefficients/Atan', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('iir_10th_order', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_iir_10th_order', 'handle'));
annotate_port('gm_iir_10th_order/Unit Delay', 1, 1, '');
annotate_port('iir_10th_order/Unit Delay', 1, 1, '');
annotate_port('gm_iir_10th_order/Unit Delay1', 1, 1, '');
annotate_port('iir_10th_order/Unit Delay1', 1, 1, '');
annotate_port('gm_iir_10th_order/Unit Delay3', 1, 1, '');
annotate_port('iir_10th_order/Unit Delay3', 1, 1, '');
annotate_port('gm_iir_10th_order/Unit Delay5', 1, 1, '');
annotate_port('iir_10th_order/Unit Delay5', 1, 1, '');
annotate_port('gm_iir_10th_order/Unit Delay7', 1, 1, '');
annotate_port('iir_10th_order/Unit Delay7', 1, 1, '');
annotate_port('gm_iir_10th_order/Unit Delay9', 1, 1, '');
annotate_port('iir_10th_order/Unit Delay9', 1, 1, '');
annotate_port('gm_iir_10th_order/Unit Delay11', 1, 1, '');
annotate_port('iir_10th_order/Unit Delay11', 1, 1, '');
annotate_port('gm_iir_10th_order/Sum17', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum17_outbuff', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum16', 0, 1, '');
annotate_port('gm_iir_10th_order/Product23', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum13', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum13_outbuff', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum12', 0, 1, '');
annotate_port('gm_iir_10th_order/Product18', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum11', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum11_outbuff', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum10', 0, 1, '');
annotate_port('gm_iir_10th_order/Product13', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum7', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum7_outbuff', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum6', 0, 1, '');
annotate_port('gm_iir_10th_order/Product8', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum3', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum3_outbuff', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum2', 0, 1, '');
annotate_port('gm_iir_10th_order/Sum1', 0, 1, '');
annotate_port('gm_iir_10th_order/Product', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('c1_chirp_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_c1_chirp_filter', 'handle'));
annotate_port('gm_c1_chirp_filter/10th Order IIR Filter', 0, 1, '');
annotate_port('gm_c1_chirp_filter/10th Order IIR Filter', 1, 1, '');
annotate_port('c1_chirp_filter/10th Order IIR Filter', 1, 1, '');
annotate_port('gm_c1_chirp_filter/Model', 0, 3, '');
annotate_port('gm_c1_chirp_filter/Model', 1, 1, '');
annotate_port('c1_chirp_filter/Model', 1, 1, '');
annotate_port('gm_c1_chirp_filter/Calculate C1filterout', 0, 1, '');
annotate_port('gm_c1_chirp_filter/Calculate C1filterout/Gain1_unary', 0, 1, '');
annotate_port('gm_c1_chirp_filter/Calculate C1filterout/Gain', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('c2_wideband_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_c2_wideband_filter', 'handle'));
annotate_port('gm_c2_wideband_filter/10th Order IIR Filter', 1, 1, '');
annotate_port('c2_wideband_filter/10th Order IIR Filter', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('ihc_lowpass_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ihc_lowpass_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('ihc_nl_log', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ihc_nl_log', 'handle'));
annotate_port('gm_ihc_nl_log/Subsystem', 1, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Product4_out1bypassMux', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Gain2_unaryminus', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Product4', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Divide1', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Subtract1', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Divide2', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Divide4', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Log10', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Product3', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Divide5', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Math Function1', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/Add3', 0, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/crp_out_delay', 1, 1, '');
annotate_port('gm_ihc_nl_log/Subsystem/in4_repeat', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('inner_hair_cell', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_inner_hair_cell', 'handle'));
annotate_port('gm_inner_hair_cell/C1 Chirp Nonlinear Log Path', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('filter_path', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_filter_path', 'handle'));
annotate_port('gm_filter_path/C1 Chirp Filter', 0, 1, '');
annotate_port('gm_filter_path/C2 Wideband Filter', 1, 1, '');
annotate_port('filter_path/C2 Wideband Filter', 1, 1, '');
annotate_port('gm_filter_path/Inner Hair Cell', 1, 1, '');
annotate_port('gm_filter_path/Inner Hair Cell', 1, 1, '');
annotate_port('filter_path/Inner Hair Cell', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('auditory_nerve', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_auditory_nerve', 'handle'));
annotate_port('gm_auditory_nerve/Control Path', 0, 1, '');
annotate_port('gm_auditory_nerve/Control Path', 1, 1, '');
annotate_port('auditory_nerve/Control Path', 1, 1, '');
annotate_port('gm_auditory_nerve/Filter Path', 1, 2, '');
SLStudio.Utils.RemoveHighlighting(get_param('middle_ear_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_middle_ear_filter', 'handle'));
annotate_port('gm_middle_ear_filter/Unit Delay', 0, 1, '');
annotate_port('gm_middle_ear_filter/Unit Delay', 1, 1, '');
annotate_port('middle_ear_filter/Unit Delay', 1, 1, '');
annotate_port('gm_middle_ear_filter/Unit Delay1', 1, 1, '');
annotate_port('middle_ear_filter/Unit Delay1', 1, 1, '');
annotate_port('gm_middle_ear_filter/Unit Delay3', 1, 1, '');
annotate_port('middle_ear_filter/Unit Delay3', 1, 1, '');
annotate_port('gm_middle_ear_filter/Unit Delay5', 1, 1, '');
annotate_port('middle_ear_filter/Unit Delay5', 1, 1, '');
annotate_port('gm_middle_ear_filter/Unit Delay7', 1, 1, '');
annotate_port('middle_ear_filter/Unit Delay7', 1, 1, '');
annotate_port('gm_middle_ear_filter/Sum11', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum11_outbuff', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum10', 0, 1, '');
annotate_port('gm_middle_ear_filter/Product13', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum7', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum7_outbuff', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum6', 0, 1, '');
annotate_port('gm_middle_ear_filter/Product8', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum3', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum3_outbuff', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum2', 0, 1, '');
annotate_port('gm_middle_ear_filter/Product2', 0, 1, '');
annotate_port('gm_middle_ear_filter/Sum1', 0, 1, '');
annotate_port('gm_middle_ear_filter/Product15_to_gain', 0, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('accumulator', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_accumulator', 'handle'));
annotate_port('gm_accumulator/HDL Counter1', 1, 1, '');
annotate_port('accumulator/HDL Counter1', 1, 1, '');
annotate_port('gm_accumulator/HDL Counter2', 1, 1, '');
annotate_port('accumulator/HDL Counter2', 1, 1, '');
annotate_port('gm_accumulator/HDL Counter3', 1, 1, '');
annotate_port('accumulator/HDL Counter3', 1, 1, '');
annotate_port('gm_accumulator/HDL Counter4', 1, 1, '');
annotate_port('accumulator/HDL Counter4', 1, 1, '');
annotate_port('gm_accumulator/Add', 1, 1, '');
annotate_port('accumulator/Add', 1, 1, '');
annotate_port('gm_accumulator/HDL Counter', 1, 1, '');
annotate_port('accumulator/HDL Counter', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('initialize_signal', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_initialize_signal', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('redocking_site', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_redocking_site', 'handle'));
annotate_port('gm_redocking_site/Delay2', 1, 1, '');
annotate_port('redocking_site/Delay2', 1, 1, '');
annotate_port('gm_redocking_site/Redock Component', 1, 1, '');
annotate_port('redocking_site/Redock Component', 1, 1, '');
annotate_port('gm_redocking_site/Elapsed Time Component', 1, 1, '');
annotate_port('redocking_site/Elapsed Time Component', 1, 1, '');
annotate_port('gm_redocking_site/Xsum Component', 1, 1, '');
annotate_port('redocking_site/Xsum Component', 1, 1, '');
annotate_port('gm_redocking_site/unitRateInterval Component', 1, 1, '');
annotate_port('redocking_site/unitRateInterval Component', 1, 1, '');
annotate_port('gm_redocking_site/Current Release Component', 1, 1, '');
annotate_port('redocking_site/Current Release Component', 1, 1, '');
annotate_port('gm_redocking_site/Current Refactory Component', 1, 1, '');
annotate_port('redocking_site/Current Refactory Component', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('spike_generator', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_spike_generator', 'handle'));
annotate_port('gm_spike_generator/Redocking Site 4', 1, 1, '');
annotate_port('spike_generator/Redocking Site 4', 1, 1, '');
annotate_port('gm_spike_generator/From48', 1, 1, '');
annotate_port('spike_generator/From48', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Site 3', 1, 1, '');
annotate_port('spike_generator/Redocking Site 3', 1, 1, '');
annotate_port('gm_spike_generator/From47', 1, 1, '');
annotate_port('spike_generator/From47', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Site 2', 1, 1, '');
annotate_port('spike_generator/Redocking Site 2', 1, 1, '');
annotate_port('gm_spike_generator/From46', 1, 1, '');
annotate_port('spike_generator/From46', 1, 1, '');
annotate_port('gm_spike_generator/From2', 1, 1, '');
annotate_port('spike_generator/From2', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Site 1', 1, 1, '');
annotate_port('spike_generator/Redocking Site 1', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/HDL Counter', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/HDL Counter', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, '');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, '');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('nl_pla_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_nl_pla_filter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('power_law_adapter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_power_law_adapter', 'handle'));
annotate_port('gm_power_law_adapter/Slow Power Law', 1, 1, '');
annotate_port('power_law_adapter/Slow Power Law', 1, 1, '');
annotate_port('gm_power_law_adapter/Fast Power Law', 1, 1, '');
annotate_port('power_law_adapter/Fast Power Law', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('synapse_model', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_synapse_model', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('synapse_spike_generator', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_synapse_spike_generator', 'handle'));
annotate_port('gm_synapse_spike_generator/Spike Generator', 1, 1, '');
annotate_port('synapse_spike_generator/Spike Generator', 1, 1, '');
SLStudio.Utils.RemoveHighlighting(get_param('ur_ear_fpga_sim', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ur_ear_fpga_sim', 'handle'));
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing', 0, 1, '');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA', 0, 1, '');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Auditory Nerve Model', 1, 1, '');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 0, 1, '');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 1, 1, '');
annotate_port('ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 1, 1, '');
