open_system('gm_calc_tau');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Calculate tauc1', 'user2');
annotate_port('gm_calc_tau/Calculate tauc1', 0, 1, 'cp : 301.414 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Subtract', 'user2');
annotate_port('gm_calc_tau/Subtract', 0, 1, 'cp : 323.364 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Reciprocal_recip', 'user2');
annotate_port('gm_calc_tau/Reciprocal_recip', 0, 1, 'cp : 318.358 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Calculate tauc1/Add', 'user2');
annotate_port('gm_calc_tau/Calculate tauc1/Add', 0, 1, 'cp : 301.414 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Calculate tauc1/Subtract', 'user2');
annotate_port('gm_calc_tau/Calculate tauc1/Subtract', 0, 1, 'cp : 295.793 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Calculate tauc1/Product_to_gain', 'user2');
annotate_port('gm_calc_tau/Calculate tauc1/Product_to_gain', 0, 1, 'cp : 296.408 ns');
open_system('gm_cp_wideband_gammatone_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter', 0, 1, 'cp : 93.57 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Calculate wbout', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout', 0, 1, 'cp : 114.201 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Complex to Real-Imag', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Complex to Real-Imag', 0, 1, 'cp : 102.422 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Product_ReIm2Complex', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Product_ReIm2Complex', 0, 1, 'cp : 51.996 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Product1_C2ReIm_1', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Product1_C2ReIm_1', 0, 1, 'cp : 93.57 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Product1_ReIm2Complex', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Product1_ReIm2Complex', 0, 1, 'cp : 102.422 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Product', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Product', 0, 1, 'cp : 51.996 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Product11', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Product11', 0, 1, 'cp : 97.416 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Product1_AC_minus_BD', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Product1_AC_minus_BD', 0, 1, 'cp : 102.422 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Calculate wbout/Product1', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout/Product1', 0, 1, 'cp : 114.201 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Calculate wbout/Product', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout/Product', 0, 1, 'cp : 106.268 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Calculate wbout/Gain', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Calculate wbout/Gain', 0, 1, 'cp : 110.355 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8_C2ReIm', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8_C2ReIm', 0, 1, 'cp : 84.718 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8_ReIm2Complex', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8_ReIm2Complex', 0, 1, 'cp : 88.564 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7_C2ReIm', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7_C2ReIm', 0, 1, 'cp : 70.86 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7_ReIm2Complex', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7_ReIm2Complex', 0, 1, 'cp : 74.706 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4_C2ReIm', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4_C2ReIm', 0, 1, 'cp : 57.002 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4_ReIm2Complex', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4_ReIm2Complex', 0, 1, 'cp : 60.848 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum6', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum6', 0, 1, 'cp : 93.57 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum6_outbuff', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum6_outbuff', 0, 1, 'cp : 93.57 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum5', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum5', 0, 1, 'cp : 84.718 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum4', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum4', 0, 1, 'cp : 79.712 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum4_outbuff', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum4_outbuff', 0, 1, 'cp : 79.712 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum3', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum3', 0, 1, 'cp : 70.86 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum2', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum2', 0, 1, 'cp : 65.854 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum2_outbuff', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum2_outbuff', 0, 1, 'cp : 65.854 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum1', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Sum1', 0, 1, 'cp : 57.002 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product8', 0, 1, 'cp : 88.564 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product7', 0, 1, 'cp : 74.706 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Product4', 0, 1, 'cp : 60.848 ns');
open_system('gm_ohc_lowpass_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Sum7', 'user2');
annotate_port('gm_ohc_lowpass_filter/Sum7', 0, 1, 'cp : 238.971 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Sum7_outbuff', 'user2');
annotate_port('gm_ohc_lowpass_filter/Sum7_outbuff', 0, 1, 'cp : 238.971 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Sum6', 'user2');
annotate_port('gm_ohc_lowpass_filter/Sum6', 0, 1, 'cp : 233.965 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Product8', 'user2');
annotate_port('gm_ohc_lowpass_filter/Product8', 0, 1, 'cp : 228.959 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Sum3', 'user2');
annotate_port('gm_ohc_lowpass_filter/Sum3', 0, 1, 'cp : 224.872 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Sum3_outbuff', 'user2');
annotate_port('gm_ohc_lowpass_filter/Sum3_outbuff', 0, 1, 'cp : 224.872 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Product3', 'user2');
annotate_port('gm_ohc_lowpass_filter/Product3', 0, 1, 'cp : 214.86 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Sum2', 'user2');
annotate_port('gm_ohc_lowpass_filter/Sum2', 0, 1, 'cp : 219.866 ns');
open_system('gm_ohc_nl_boltzman_function');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Gain1_unaryminus', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Gain1_unaryminus', 0, 1, 'cp : 137.123 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Divide3', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Divide3', 0, 1, 'cp : 210.773 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Subtract3', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Subtract3', 0, 1, 'cp : 192.857 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Divide2', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Divide2', 0, 1, 'cp : 187.851 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Add4', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Add4', 0, 1, 'cp : 170.417 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Product', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Product', 0, 1, 'cp : 165.411 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Subtract1', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Subtract1', 0, 1, 'cp : 119.207 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Divide1', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Divide1', 0, 1, 'cp : 137.123 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Math Function2', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Math Function2', 0, 1, 'cp : 156.318 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nl_boltzman_function/Add1', 'user2');
annotate_port('gm_ohc_nl_boltzman_function/Add1', 0, 1, 'cp : 161.324 ns');
open_system('gm_ohc_nonlinear_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Saturation_Switch1', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Saturation_Switch1', 0, 1, 'cp : 290.474 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Saturation_Switch2', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Saturation_Switch2', 0, 1, 'cp : 290.787 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Gain2_unaryminus', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Gain2_unaryminus', 0, 1, 'cp : 256.887 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Saturation_UpperRelop', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Saturation_UpperRelop', 0, 1, 'cp : 290.113 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Product4', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Product4', 0, 1, 'cp : 289.253 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Product4_outbuff', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Product4_outbuff', 0, 1, 'cp : 289.253 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Add3', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Add3', 0, 1, 'cp : 285.166 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Product3', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Product3', 0, 1, 'cp : 280.169 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Exp', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Exp', 0, 1, 'cp : 276.082 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Divide1', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Divide1', 0, 1, 'cp : 256.887 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_nonlinear_filter/Abs', 'user2');
annotate_port('gm_ohc_nonlinear_filter/Abs', 0, 1, 'cp : 238.971 ns');
open_system('gm_outer_hair_cell');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_outer_hair_cell/Model', 'user2');
annotate_port('gm_outer_hair_cell/Model', 0, 1, 'cp : 210.773 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_outer_hair_cell/Model1', 'user2');
annotate_port('gm_outer_hair_cell/Model1', 0, 1, 'cp : 238.971 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_outer_hair_cell/Model2', 'user2');
annotate_port('gm_outer_hair_cell/Model2', 0, 1, 'cp : 290.787 ns');
open_system('gm_control_path');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model', 'user2');
annotate_port('gm_control_path/Model', 0, 1, 'cp : 114.201 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model1', 'user2');
annotate_port('gm_control_path/Model1', 0, 1, 'cp : 290.787 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model2', 'user2');
annotate_port('gm_control_path/Model2', 0, 1, 'cp : 323.364 ns');
open_system('gm_calc_coeff');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_coeff/Multiply1_unaryminus', 'user2');
annotate_port('gm_calc_coeff/Multiply1_unaryminus', 0, 1, 'cp : 475.53 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_coeff/Divide2', 'user2');
annotate_port('gm_calc_coeff/Divide2', 0, 1, 'cp : 493.446 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_coeff/Add', 'user2');
annotate_port('gm_calc_coeff/Add', 0, 1, 'cp : 475.53 ns');
open_system('gm_calc_phase_temp');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_phase_temp/Multiply_unaryminus', 'user2');
annotate_port('gm_calc_phase_temp/Multiply_unaryminus', 0, 1, 'cp : 338.979 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_phase_temp/Multiply_unaryminus_outbuff', 'user2');
annotate_port('gm_calc_phase_temp/Multiply_unaryminus_outbuff', 0, 1, 'cp : 338.979 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_phase_temp/Divide', 'user2');
annotate_port('gm_calc_phase_temp/Divide', 0, 1, 'cp : 356.413 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_phase_temp/Atan', 'user2');
annotate_port('gm_calc_phase_temp/Atan', 0, 1, 'cp : 378.993 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_phase_temp/Subtract1', 'user2');
annotate_port('gm_calc_phase_temp/Subtract1', 0, 1, 'cp : 383.999 ns');
open_system('gm_calc_temp');
open_system('gm_calc_c1_coefficients');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Phase Calc - i=2', 'user2');
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=2', 0, 1, 'cp : 383.999 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/calc_coeff', 'user2');
annotate_port('gm_calc_c1_coefficients/calc_coeff', 0, 3, 'cp : 493.446 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Multiply', 'user2');
annotate_port('gm_calc_c1_coefficients/Multiply', 0, 1, 'cp : 338.979 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Multiply_outbuff', 'user2');
annotate_port('gm_calc_c1_coefficients/Multiply_outbuff', 0, 1, 'cp : 338.979 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Add2', 'user2');
annotate_port('gm_calc_c1_coefficients/Add2', 0, 1, 'cp : 333.367 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Add2_outbuff', 'user2');
annotate_port('gm_calc_c1_coefficients/Add2_outbuff', 0, 1, 'cp : 333.367 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Subtract', 'user2');
annotate_port('gm_calc_c1_coefficients/Subtract', 0, 1, 'cp : 328.361 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Subtract_outbuff', 'user2');
annotate_port('gm_calc_c1_coefficients/Subtract_outbuff', 0, 1, 'cp : 328.361 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Add', 'user2');
annotate_port('gm_calc_c1_coefficients/Add', 0, 1, 'cp : 338.364 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Divide1', 'user2');
annotate_port('gm_calc_c1_coefficients/Divide1', 0, 1, 'cp : 470.533 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Divide1_outbuff', 'user2');
annotate_port('gm_calc_c1_coefficients/Divide1_outbuff', 0, 1, 'cp : 470.533 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Sum1', 'user2');
annotate_port('gm_calc_c1_coefficients/Sum1', 0, 1, 'cp : 388.996 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Sum2', 'user2');
annotate_port('gm_calc_c1_coefficients/Sum2', 0, 1, 'cp : 394.002 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Sum3', 'user2');
annotate_port('gm_calc_c1_coefficients/Sum3', 0, 1, 'cp : 399.008 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Sum4', 'user2');
annotate_port('gm_calc_c1_coefficients/Sum4', 0, 1, 'cp : 404.014 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Sum5', 'user2');
annotate_port('gm_calc_c1_coefficients/Sum5', 0, 1, 'cp : 409.011 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Divide', 'user2');
annotate_port('gm_calc_c1_coefficients/Divide', 0, 1, 'cp : 426.927 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Atan', 'user2');
annotate_port('gm_calc_c1_coefficients/Atan', 0, 1, 'cp : 453.099 ns');
open_system('gm_iir_10th_order');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum17', 'user2');
annotate_port('gm_iir_10th_order/Sum17', 0, 1, 'cp : 568.688 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum17_outbuff', 'user2');
annotate_port('gm_iir_10th_order/Sum17_outbuff', 0, 1, 'cp : 568.688 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum16', 'user2');
annotate_port('gm_iir_10th_order/Sum16', 0, 1, 'cp : 563.682 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Product23', 'user2');
annotate_port('gm_iir_10th_order/Product23', 0, 1, 'cp : 558.676 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum13', 'user2');
annotate_port('gm_iir_10th_order/Sum13', 0, 1, 'cp : 554.589 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum13_outbuff', 'user2');
annotate_port('gm_iir_10th_order/Sum13_outbuff', 0, 1, 'cp : 554.589 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum12', 'user2');
annotate_port('gm_iir_10th_order/Sum12', 0, 1, 'cp : 549.583 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Product18', 'user2');
annotate_port('gm_iir_10th_order/Product18', 0, 1, 'cp : 544.577 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum11', 'user2');
annotate_port('gm_iir_10th_order/Sum11', 0, 1, 'cp : 540.49 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum11_outbuff', 'user2');
annotate_port('gm_iir_10th_order/Sum11_outbuff', 0, 1, 'cp : 540.49 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum10', 'user2');
annotate_port('gm_iir_10th_order/Sum10', 0, 1, 'cp : 535.484 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Product13', 'user2');
annotate_port('gm_iir_10th_order/Product13', 0, 1, 'cp : 530.478 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum7', 'user2');
annotate_port('gm_iir_10th_order/Sum7', 0, 1, 'cp : 526.391 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum7_outbuff', 'user2');
annotate_port('gm_iir_10th_order/Sum7_outbuff', 0, 1, 'cp : 526.391 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum6', 'user2');
annotate_port('gm_iir_10th_order/Sum6', 0, 1, 'cp : 521.385 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Product8', 'user2');
annotate_port('gm_iir_10th_order/Product8', 0, 1, 'cp : 516.379 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum3', 'user2');
annotate_port('gm_iir_10th_order/Sum3', 0, 1, 'cp : 512.292 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum3_outbuff', 'user2');
annotate_port('gm_iir_10th_order/Sum3_outbuff', 0, 1, 'cp : 512.292 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum2', 'user2');
annotate_port('gm_iir_10th_order/Sum2', 0, 1, 'cp : 507.286 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Sum1', 'user2');
annotate_port('gm_iir_10th_order/Sum1', 0, 1, 'cp : 502.289 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Product', 'user2');
annotate_port('gm_iir_10th_order/Product', 0, 1, 'cp : 497.292 ns');
open_system('gm_c1_chirp_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c1_chirp_filter/10th Order IIR Filter', 'user2');
annotate_port('gm_c1_chirp_filter/10th Order IIR Filter', 0, 1, 'cp : 568.688 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c1_chirp_filter/Model', 'user2');
annotate_port('gm_c1_chirp_filter/Model', 0, 3, 'cp : 493.446 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c1_chirp_filter/Calculate C1filterout', 'user2');
annotate_port('gm_c1_chirp_filter/Calculate C1filterout', 0, 1, 'cp : 572.775 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c1_chirp_filter/Calculate C1filterout/Gain1_unary', 'user2');
annotate_port('gm_c1_chirp_filter/Calculate C1filterout/Gain1_unary', 0, 1, 'cp : 572.775 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c1_chirp_filter/Calculate C1filterout/Gain', 'user2');
annotate_port('gm_c1_chirp_filter/Calculate C1filterout/Gain', 0, 1, 'cp : 572.775 ns');
open_system('gm_c2_wideband_filter');
open_system('gm_ihc_lowpass_filter');
open_system('gm_ihc_nl_log');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem', 1, 1, 'cp : 697.839 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Product4_out1bypassMux', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Product4_out1bypassMux', 0, 1, 'cp : 697.629 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Gain2_unaryminus', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Gain2_unaryminus', 0, 1, 'cp : 590.691 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Product4', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Product4', 0, 1, 'cp : 697.508 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Divide1', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Divide1', 0, 1, 'cp : 693.421 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Subtract1', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Subtract1', 0, 1, 'cp : 675.987 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Divide2', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Divide2', 0, 1, 'cp : 670.99 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Divide4', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Divide4', 0, 1, 'cp : 590.691 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Log10', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Log10', 0, 1, 'cp : 607.352 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Product3', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Product3', 0, 1, 'cp : 611.439 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Divide5', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Divide5', 0, 1, 'cp : 629.355 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Math Function1', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Math Function1', 0, 1, 'cp : 648.55 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/Add3', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/Add3', 0, 1, 'cp : 653.556 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/crp_out_delay', 'user1');
annotate_port('gm_ihc_nl_log/Subsystem/crp_out_delay', 1, 1, 'cp : 697.839 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ihc_nl_log/Subsystem/in4_repeat', 'user2');
annotate_port('gm_ihc_nl_log/Subsystem/in4_repeat', 0, 1, 'cp : 572.775 ns');
open_system('gm_inner_hair_cell');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_inner_hair_cell/C1 Chirp Nonlinear Log Path', 'user2');
annotate_port('gm_inner_hair_cell/C1 Chirp Nonlinear Log Path', 1, 1, 'cp : 697.839 ns');
open_system('gm_filter_path');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_filter_path/C1 Chirp Filter', 'user2');
annotate_port('gm_filter_path/C1 Chirp Filter', 0, 1, 'cp : 572.775 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_filter_path/Inner Hair Cell', 'user2');
annotate_port('gm_filter_path/Inner Hair Cell', 1, 1, 'cp : 697.839 ns');
open_system('gm_auditory_nerve');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_auditory_nerve/Control Path', 'user2');
annotate_port('gm_auditory_nerve/Control Path', 0, 1, 'cp : 323.364 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_auditory_nerve/Filter Path', 'user2');
annotate_port('gm_auditory_nerve/Filter Path', 1, 2, 'cp : 697.839 ns');
open_system('gm_middle_ear_filter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay', 'user1');
annotate_port('gm_middle_ear_filter/Unit Delay', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum11', 'user2');
annotate_port('gm_middle_ear_filter/Sum11', 0, 1, 'cp : 47.294 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum11_outbuff', 'user2');
annotate_port('gm_middle_ear_filter/Sum11_outbuff', 0, 1, 'cp : 47.294 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum10', 'user2');
annotate_port('gm_middle_ear_filter/Sum10', 0, 1, 'cp : 42.288 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Product13', 'user2');
annotate_port('gm_middle_ear_filter/Product13', 0, 1, 'cp : 37.282 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum7', 'user2');
annotate_port('gm_middle_ear_filter/Sum7', 0, 1, 'cp : 33.195 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum7_outbuff', 'user2');
annotate_port('gm_middle_ear_filter/Sum7_outbuff', 0, 1, 'cp : 33.195 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum6', 'user2');
annotate_port('gm_middle_ear_filter/Sum6', 0, 1, 'cp : 28.189 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Product8', 'user2');
annotate_port('gm_middle_ear_filter/Product8', 0, 1, 'cp : 23.183 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum3', 'user2');
annotate_port('gm_middle_ear_filter/Sum3', 0, 1, 'cp : 19.096 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum3_outbuff', 'user2');
annotate_port('gm_middle_ear_filter/Sum3_outbuff', 0, 1, 'cp : 19.096 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum2', 'user2');
annotate_port('gm_middle_ear_filter/Sum2', 0, 1, 'cp : 14.09 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Product2', 'user2');
annotate_port('gm_middle_ear_filter/Product2', 0, 1, 'cp : 4.087 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Sum1', 'user2');
annotate_port('gm_middle_ear_filter/Sum1', 0, 1, 'cp : 9.093 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Product15_to_gain', 'user2');
annotate_port('gm_middle_ear_filter/Product15_to_gain', 0, 1, 'cp : 47.909 ns');
open_system('gm_accumulator');
open_system('gm_initialize_signal');
open_system('gm_redocking_site');
open_system('gm_spike_generator');
open_system('gm_nl_pla_filter');
open_system('gm_power_law_adapter');
open_system('gm_synapse_model');
open_system('gm_synapse_spike_generator');
open_system('gm_ur_ear_fpga_sim');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing', 'user2');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing', 0, 1, 'cp : 697.839 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA', 'user2');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA', 0, 1, 'cp : 697.839 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Auditory Nerve Model', 'user2');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Auditory Nerve Model', 1, 1, 'cp : 697.839 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 'user2');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 0, 1, 'cp : 47.909 ns');
