open_system('calc_tau');
open_system('gm_calc_tau');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/Delay1', 'user2');
annotate_port('gm_calc_tau/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/Delay1', 'user2');
annotate_port('calc_tau/Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/read address generator', 'user2');
annotate_port('gm_calc_tau/read address generator', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/read address generator', 'user2');
annotate_port('calc_tau/read address generator', 0, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/integer delay DPRAM', 'user2');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/integer delay DPRAM', 'user2');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_tau/integer delay DPRAM', 'user2');
annotate_port('gm_calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('calc_tau/integer delay DPRAM', 'user2');
annotate_port('calc_tau/integer delay DPRAM', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('cp_wideband_gammatone_filter');
open_system('gm_cp_wideband_gammatone_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/MATLAB Function1', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/MATLAB Function1', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('cp_wideband_gammatone_filter/MATLAB Function1', 'user2');
annotate_port('cp_wideband_gammatone_filter/MATLAB Function1', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 'user2');
annotate_port('gm_cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 'user2');
annotate_port('cp_wideband_gammatone_filter/Third Order IIR Filter/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('ohc_lowpass_filter');
open_system('gm_ohc_lowpass_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay1', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay1', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay3', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay3', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay5', 'user2');
annotate_port('gm_ohc_lowpass_filter/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('ohc_lowpass_filter/Unit Delay5', 'user2');
annotate_port('ohc_lowpass_filter/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('ohc_nl_boltzman_function');
open_system('gm_ohc_nl_boltzman_function');
open_system('ohc_nonlinear_filter');
open_system('gm_ohc_nonlinear_filter');
open_system('outer_hair_cell');
open_system('gm_outer_hair_cell');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_outer_hair_cell/Model1', 'user2');
annotate_port('gm_outer_hair_cell/Model1', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('outer_hair_cell/Model1', 'user2');
annotate_port('outer_hair_cell/Model1', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('control_path');
open_system('gm_control_path');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model', 'user2');
annotate_port('gm_control_path/Model', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('control_path/Model', 'user2');
annotate_port('control_path/Model', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_control_path/Model2', 'user2');
annotate_port('gm_control_path/Model2', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('control_path/Model2', 'user2');
annotate_port('control_path/Model2', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('calc_coeff');
open_system('gm_calc_coeff');
open_system('calc_phase_temp');
open_system('gm_calc_phase_temp');
open_system('calc_temp');
open_system('gm_calc_temp');
open_system('calc_c1_coefficients');
open_system('gm_calc_c1_coefficients');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Phase Calc - i=1', 'user2');
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=1', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('calc_c1_coefficients/Phase Calc - i=1', 'user2');
annotate_port('calc_c1_coefficients/Phase Calc - i=1', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Phase Calc - i=2', 'user2');
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=2', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('calc_c1_coefficients/Phase Calc - i=2', 'user2');
annotate_port('calc_c1_coefficients/Phase Calc - i=2', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_calc_c1_coefficients/Phase Calc - i=3', 'user2');
annotate_port('gm_calc_c1_coefficients/Phase Calc - i=3', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('calc_c1_coefficients/Phase Calc - i=3', 'user2');
annotate_port('calc_c1_coefficients/Phase Calc - i=3', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('iir_10th_order');
open_system('gm_iir_10th_order');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay', 'user2');
annotate_port('gm_iir_10th_order/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('iir_10th_order/Unit Delay', 'user2');
annotate_port('iir_10th_order/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay1', 'user2');
annotate_port('gm_iir_10th_order/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('iir_10th_order/Unit Delay1', 'user2');
annotate_port('iir_10th_order/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay3', 'user2');
annotate_port('gm_iir_10th_order/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('iir_10th_order/Unit Delay3', 'user2');
annotate_port('iir_10th_order/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay5', 'user2');
annotate_port('gm_iir_10th_order/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('iir_10th_order/Unit Delay5', 'user2');
annotate_port('iir_10th_order/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay7', 'user2');
annotate_port('gm_iir_10th_order/Unit Delay7', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('iir_10th_order/Unit Delay7', 'user2');
annotate_port('iir_10th_order/Unit Delay7', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay9', 'user2');
annotate_port('gm_iir_10th_order/Unit Delay9', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('iir_10th_order/Unit Delay9', 'user2');
annotate_port('iir_10th_order/Unit Delay9', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay11', 'user2');
annotate_port('gm_iir_10th_order/Unit Delay11', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('iir_10th_order/Unit Delay11', 'user2');
annotate_port('iir_10th_order/Unit Delay11', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('c1_chirp_filter');
open_system('gm_c1_chirp_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c1_chirp_filter/10th Order IIR Filter', 'user2');
annotate_port('gm_c1_chirp_filter/10th Order IIR Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('c1_chirp_filter/10th Order IIR Filter', 'user2');
annotate_port('c1_chirp_filter/10th Order IIR Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c1_chirp_filter/Model', 'user2');
annotate_port('gm_c1_chirp_filter/Model', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('c1_chirp_filter/Model', 'user2');
annotate_port('c1_chirp_filter/Model', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('c2_wideband_filter');
open_system('gm_c2_wideband_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_c2_wideband_filter/10th Order IIR Filter', 'user2');
annotate_port('gm_c2_wideband_filter/10th Order IIR Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('c2_wideband_filter/10th Order IIR Filter', 'user2');
annotate_port('c2_wideband_filter/10th Order IIR Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('ihc_lowpass_filter');
open_system('gm_ihc_lowpass_filter');
open_system('ihc_nl_log');
open_system('gm_ihc_nl_log');
open_system('inner_hair_cell');
open_system('gm_inner_hair_cell');
open_system('filter_path');
open_system('gm_filter_path');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_filter_path/C2 Wideband Filter', 'user2');
annotate_port('gm_filter_path/C2 Wideband Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('filter_path/C2 Wideband Filter', 'user2');
annotate_port('filter_path/C2 Wideband Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_filter_path/Inner Hair Cell', 'user2');
annotate_port('gm_filter_path/Inner Hair Cell', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('filter_path/Inner Hair Cell', 'user2');
annotate_port('filter_path/Inner Hair Cell', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('auditory_nerve');
open_system('gm_auditory_nerve');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_auditory_nerve/Control Path', 'user2');
annotate_port('gm_auditory_nerve/Control Path', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('auditory_nerve/Control Path', 'user2');
annotate_port('auditory_nerve/Control Path', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('middle_ear_filter');
open_system('gm_middle_ear_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay', 'user2');
annotate_port('gm_middle_ear_filter/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('middle_ear_filter/Unit Delay', 'user2');
annotate_port('middle_ear_filter/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay1', 'user2');
annotate_port('gm_middle_ear_filter/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('middle_ear_filter/Unit Delay1', 'user2');
annotate_port('middle_ear_filter/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay3', 'user2');
annotate_port('gm_middle_ear_filter/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('middle_ear_filter/Unit Delay3', 'user2');
annotate_port('middle_ear_filter/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay5', 'user2');
annotate_port('gm_middle_ear_filter/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('middle_ear_filter/Unit Delay5', 'user2');
annotate_port('middle_ear_filter/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay7', 'user2');
annotate_port('gm_middle_ear_filter/Unit Delay7', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('middle_ear_filter/Unit Delay7', 'user2');
annotate_port('middle_ear_filter/Unit Delay7', 1, 1, 'Obstacle to clock-rate pipelining');
open_system('accumulator');
open_system('gm_accumulator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_accumulator/HDL Counter1', 'user2');
annotate_port('gm_accumulator/HDL Counter1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('accumulator/HDL Counter1', 'user2');
annotate_port('accumulator/HDL Counter1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_accumulator/HDL Counter2', 'user2');
annotate_port('gm_accumulator/HDL Counter2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('accumulator/HDL Counter2', 'user2');
annotate_port('accumulator/HDL Counter2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_accumulator/HDL Counter3', 'user2');
annotate_port('gm_accumulator/HDL Counter3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('accumulator/HDL Counter3', 'user2');
annotate_port('accumulator/HDL Counter3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_accumulator/HDL Counter4', 'user2');
annotate_port('gm_accumulator/HDL Counter4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('accumulator/HDL Counter4', 'user2');
annotate_port('accumulator/HDL Counter4', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_accumulator/HDL Counter', 'user2');
annotate_port('gm_accumulator/HDL Counter', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('accumulator/HDL Counter', 'user2');
annotate_port('accumulator/HDL Counter', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
open_system('initialize_signal');
open_system('gm_initialize_signal');
open_system('redocking_site');
open_system('gm_redocking_site');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Delay2', 'user2');
annotate_port('gm_redocking_site/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('redocking_site/Delay2', 'user2');
annotate_port('redocking_site/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Redock Component', 'user2');
annotate_port('gm_redocking_site/Redock Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Redock Component', 'user2');
annotate_port('redocking_site/Redock Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Elapsed Time Component', 'user2');
annotate_port('gm_redocking_site/Elapsed Time Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Elapsed Time Component', 'user2');
annotate_port('redocking_site/Elapsed Time Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Xsum Component', 'user2');
annotate_port('gm_redocking_site/Xsum Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Xsum Component', 'user2');
annotate_port('redocking_site/Xsum Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/unitRateInterval Component', 'user2');
annotate_port('gm_redocking_site/unitRateInterval Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/unitRateInterval Component', 'user2');
annotate_port('redocking_site/unitRateInterval Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Release Component', 'user2');
annotate_port('gm_redocking_site/Current Release Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Current Release Component', 'user2');
annotate_port('redocking_site/Current Release Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Refactory Component', 'user2');
annotate_port('gm_redocking_site/Current Refactory Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('redocking_site/Current Refactory Component', 'user2');
annotate_port('redocking_site/Current Refactory Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
open_system('spike_generator');
open_system('gm_spike_generator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 4', 'user2');
annotate_port('gm_spike_generator/Redocking Site 4', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('spike_generator/Redocking Site 4', 'user2');
annotate_port('spike_generator/Redocking Site 4', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From48', 'user2');
annotate_port('gm_spike_generator/From48', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From48', 'user2');
annotate_port('spike_generator/From48', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 3', 'user2');
annotate_port('gm_spike_generator/Redocking Site 3', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Site 3', 'user2');
annotate_port('spike_generator/Redocking Site 3', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From47', 'user2');
annotate_port('gm_spike_generator/From47', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From47', 'user2');
annotate_port('spike_generator/From47', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 2', 'user2');
annotate_port('gm_spike_generator/Redocking Site 2', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Site 2', 'user2');
annotate_port('spike_generator/Redocking Site 2', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From46', 'user2');
annotate_port('gm_spike_generator/From46', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From46', 'user2');
annotate_port('spike_generator/From46', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From2', 'user2');
annotate_port('gm_spike_generator/From2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/From2', 'user2');
annotate_port('spike_generator/From2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Calculation', 'user2');
annotate_port('spike_generator/Redocking Calculation', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 1', 'user2');
annotate_port('gm_spike_generator/Redocking Site 1', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Site 1', 'user2');
annotate_port('spike_generator/Redocking Site 1', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/HDL Counter', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/HDL Counter', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('spike_generator/Redocking Calculation/HDL Counter', 'user2');
annotate_port('spike_generator/Redocking Calculation/HDL Counter', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Current Redock Component', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Calculation/Current Redock Component', 'user2');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('spike_generator/Redocking Calculation/Correct Redocking Period', 'user2');
annotate_port('spike_generator/Redocking Calculation/Correct Redocking Period', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
open_system('nl_pla_filter');
open_system('gm_nl_pla_filter');
open_system('power_law_adapter');
open_system('gm_power_law_adapter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_power_law_adapter/Slow Power Law', 'user2');
annotate_port('gm_power_law_adapter/Slow Power Law', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('power_law_adapter/Slow Power Law', 'user2');
annotate_port('power_law_adapter/Slow Power Law', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_power_law_adapter/Fast Power Law', 'user2');
annotate_port('gm_power_law_adapter/Fast Power Law', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
hilite_system('power_law_adapter/Fast Power Law', 'user2');
annotate_port('power_law_adapter/Fast Power Law', 1, 1, 'Obstacle to clock-rate pipelining because the block is in a feedback loop');
open_system('synapse_model');
open_system('gm_synapse_model');
open_system('synapse_spike_generator');
open_system('gm_synapse_spike_generator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_synapse_spike_generator/Spike Generator', 'user2');
annotate_port('gm_synapse_spike_generator/Spike Generator', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('synapse_spike_generator/Spike Generator', 'user2');
annotate_port('synapse_spike_generator/Spike Generator', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
open_system('ur_ear_fpga_sim');
open_system('gm_ur_ear_fpga_sim');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 'user2');
annotate_port('gm_ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
hilite_system('ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 'user2');
annotate_port('ur_ear_fpga_sim/dataplane/Avalon Data Processing/UR EAR FPGA/Middle Ear Filter', 1, 1, 'This model-reference block is inhibiting clock-rate pipelining. Consider converting it to a subsystem and then turn on FlattenHierarchy option on it');
