open_system('calc_tau');
open_system('gm_calc_tau');
open_system('cp_wideband_gammatone_filter');
open_system('gm_cp_wideband_gammatone_filter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/Delay', 'user2');
hilite_system('cp_wideband_gammatone_filter/Delay', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_cp_wideband_gammatone_filter/MATLAB Function1', 'user2');
hilite_system('cp_wideband_gammatone_filter/MATLAB Function1', 'user2');
open_system('ohc_lowpass_filter');
open_system('gm_ohc_lowpass_filter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay3', 'user1');
hilite_system('ohc_lowpass_filter/Unit Delay3', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ohc_lowpass_filter/Unit Delay5', 'user1');
hilite_system('ohc_lowpass_filter/Unit Delay5', 'user1');
open_system('ohc_nl_boltzman_function');
open_system('gm_ohc_nl_boltzman_function');
open_system('ohc_nonlinear_filter');
open_system('gm_ohc_nonlinear_filter');
open_system('outer_hair_cell');
open_system('gm_outer_hair_cell');
open_system('control_path');
open_system('gm_control_path');
open_system('calc_coeff');
open_system('gm_calc_coeff');
open_system('calc_phase_temp');
open_system('gm_calc_phase_temp');
open_system('calc_temp');
open_system('gm_calc_temp');
open_system('calc_c1_coefficients');
open_system('gm_calc_c1_coefficients');
open_system('iir_10th_order');
open_system('gm_iir_10th_order');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay3', 'user1');
hilite_system('iir_10th_order/Unit Delay3', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay5', 'user1');
hilite_system('iir_10th_order/Unit Delay5', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay7', 'user1');
hilite_system('iir_10th_order/Unit Delay7', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay9', 'user1');
hilite_system('iir_10th_order/Unit Delay9', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_10th_order/Unit Delay11', 'user1');
hilite_system('iir_10th_order/Unit Delay11', 'user1');
open_system('c1_chirp_filter');
open_system('gm_c1_chirp_filter');
open_system('c2_wideband_filter');
open_system('gm_c2_wideband_filter');
open_system('ihc_lowpass_filter');
open_system('gm_ihc_lowpass_filter');
open_system('ihc_nl_log');
open_system('gm_ihc_nl_log');
open_system('inner_hair_cell');
open_system('gm_inner_hair_cell');
open_system('filter_path');
open_system('gm_filter_path');
open_system('auditory_nerve');
open_system('gm_auditory_nerve');
open_system('middle_ear_filter');
open_system('gm_middle_ear_filter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay3', 'user1');
hilite_system('middle_ear_filter/Unit Delay3', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay5', 'user1');
hilite_system('middle_ear_filter/Unit Delay5', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_middle_ear_filter/Unit Delay7', 'user1');
hilite_system('middle_ear_filter/Unit Delay7', 'user1');
open_system('accumulator');
open_system('gm_accumulator');
open_system('initialize_signal');
open_system('gm_initialize_signal');
open_system('redocking_site');
open_system('gm_redocking_site');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From8', 'user3');
hilite_system('redocking_site/From8', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Redock Component', 'user3');
hilite_system('redocking_site/Redock Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From5', 'user3');
hilite_system('redocking_site/From5', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Elapsed Time Component', 'user3');
hilite_system('redocking_site/Elapsed Time Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From7', 'user3');
hilite_system('redocking_site/From7', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Xsum Component', 'user3');
hilite_system('redocking_site/Xsum Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From3', 'user3');
hilite_system('redocking_site/From3', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/unitRateInterval Component', 'user3');
hilite_system('redocking_site/unitRateInterval Component', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/xsum_logic', 'user3');
hilite_system('redocking_site/xsum_logic', 'user3');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Release Component', 'user5');
hilite_system('redocking_site/Current Release Component', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Goto1', 'user5');
hilite_system('redocking_site/Goto1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/From6', 'user5');
hilite_system('redocking_site/From6', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_redocking_site/Current Refactory Component', 'user5');
hilite_system('redocking_site/Current Refactory Component', 'user5');
open_system('spike_generator');
open_system('gm_spike_generator');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From35', 'user5');
hilite_system('spike_generator/From35', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 4', 'user5');
hilite_system('spike_generator/Redocking Site 4', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto26', 'user5');
hilite_system('spike_generator/Goto26', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From48', 'user5');
hilite_system('spike_generator/From48', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From24', 'user5');
hilite_system('spike_generator/From24', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 3', 'user5');
hilite_system('spike_generator/Redocking Site 3', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto25', 'user5');
hilite_system('spike_generator/Goto25', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From47', 'user5');
hilite_system('spike_generator/From47', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From13', 'user5');
hilite_system('spike_generator/From13', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 2', 'user5');
hilite_system('spike_generator/Redocking Site 2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto4', 'user5');
hilite_system('spike_generator/Goto4', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From46', 'user5');
hilite_system('spike_generator/From46', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto2', 'user5');
hilite_system('spike_generator/Goto2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From2', 'user5');
hilite_system('spike_generator/From2', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation', 'user5');
hilite_system('spike_generator/Redocking Calculation', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Goto', 'user5');
hilite_system('spike_generator/Goto', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/From', 'user5');
hilite_system('spike_generator/From', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Site 1', 'user5');
hilite_system('spike_generator/Redocking Site 1', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Current Redock Component', 'user5');
hilite_system('spike_generator/Redocking Calculation/Current Redock Component', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Correct Redocking Period', 'user5');
hilite_system('spike_generator/Redocking Calculation/Correct Redocking Period', 'user5');
open_system('nl_pla_filter');
open_system('gm_nl_pla_filter');
open_system('power_law_adapter');
open_system('gm_power_law_adapter');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_power_law_adapter/Slow Power Law', 'user3');
hilite_system('power_law_adapter/Slow Power Law', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_power_law_adapter/Fast Power Law', 'user3');
hilite_system('power_law_adapter/Fast Power Law', 'user3');
open_system('synapse_model');
open_system('gm_synapse_model');
open_system('synapse_spike_generator');
open_system('gm_synapse_spike_generator');
open_system('ur_ear_fpga_sim');
open_system('gm_ur_ear_fpga_sim');
