open_system('calc_tau');
open_system('gm_calc_tau');
open_system('cp_wideband_gammatone_filter');
open_system('gm_cp_wideband_gammatone_filter');
open_system('ohc_lowpass_filter');
open_system('gm_ohc_lowpass_filter');
open_system('ohc_nl_boltzman_function');
open_system('gm_ohc_nl_boltzman_function');
open_system('ohc_nonlinear_filter');
open_system('gm_ohc_nonlinear_filter');
open_system('outer_hair_cell');
open_system('gm_outer_hair_cell');
open_system('control_path');
open_system('gm_control_path');
open_system('calc_coeff');
open_system('gm_calc_coeff');
open_system('calc_phase_temp');
open_system('gm_calc_phase_temp');
open_system('calc_temp');
open_system('gm_calc_temp');
open_system('calc_c1_coefficients');
open_system('gm_calc_c1_coefficients');
open_system('iir_10th_order');
open_system('gm_iir_10th_order');
open_system('c1_chirp_filter');
open_system('gm_c1_chirp_filter');
open_system('c2_wideband_filter');
open_system('gm_c2_wideband_filter');
open_system('ihc_lowpass_filter');
open_system('gm_ihc_lowpass_filter');
open_system('ihc_nl_log');
open_system('gm_ihc_nl_log');
open_system('inner_hair_cell');
open_system('gm_inner_hair_cell');
open_system('filter_path');
open_system('gm_filter_path');
open_system('auditory_nerve');
open_system('gm_auditory_nerve');
open_system('middle_ear_filter');
open_system('gm_middle_ear_filter');
open_system('accumulator');
open_system('gm_accumulator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_accumulator/Add', 'user2');
annotate_port('gm_accumulator/Add', 1, 1, 'Block not characterized');
hilite_system('accumulator/Add', 'user2');
annotate_port('accumulator/Add', 1, 1, 'Block not characterized');
open_system('initialize_signal');
open_system('gm_initialize_signal');
open_system('redocking_site');
open_system('gm_redocking_site');
open_system('spike_generator');
open_system('gm_spike_generator');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_spike_generator/Redocking Calculation/Current Redock Component/Add1', 'user2');
annotate_port('gm_spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, 'Block not characterized');
hilite_system('spike_generator/Redocking Calculation/Current Redock Component/Add1', 'user2');
annotate_port('spike_generator/Redocking Calculation/Current Redock Component/Add1', 1, 1, 'Block not characterized');
open_system('nl_pla_filter');
open_system('gm_nl_pla_filter');
open_system('power_law_adapter');
open_system('gm_power_law_adapter');
open_system('synapse_model');
open_system('gm_synapse_model');
open_system('synapse_spike_generator');
open_system('gm_synapse_spike_generator');
open_system('ur_ear_fpga_sim');
open_system('gm_ur_ear_fpga_sim');
