package require -exact qsys 16.1



set_module_property DESCRIPTION ""
set_module_property NAME "ur_ear_fpga_sim"
set_module_property VERSION 1.0
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Autogen"
set_module_property GROUP "FPGA Open Speech Tools/Autogen"
set_module_property DISPLAY_NAME "ur_ear_fpga_sim"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false



add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
add_fileset_file fixed_resize_pkg.vhd VHDL PATH fixed_resize_pkg.vhd
add_fileset_file ur_ear_fpga_sim_dataplane_pkg.vhd VHDL PATH ur_ear_fpga_sim_dataplane_pkg.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_Calculate_wbout.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_Calculate_wbout.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_cp_wideband_gammatone_filter.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_cp_wideband_gammatone_filter.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_MATLAB_Function1.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_MATLAB_Function1.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_add_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_add_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_div_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_div_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_gain_pow2_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_gain_pow2_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_mul_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_mul_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_pow_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_pow_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_relop_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_relop_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_relop_single_block.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_relop_single_block.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_sincos_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_sincos_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_sub_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_sub_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_uminus_single.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_nfp_uminus_single.vhd
add_fileset_file cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_Third_Order_IIR_Filter.vhd VHDL PATH cp_wideband_gammatone_filter\\ur_ear_fpga_sim_cp_wideband_gammatone_filter_Third_Order_IIR_Filter.vhd
add_fileset_file ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_add_single.vhd VHDL PATH ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_add_single.vhd
add_fileset_file ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_div_single.vhd VHDL PATH ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_div_single.vhd
add_fileset_file ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_exp_single.vhd VHDL PATH ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_exp_single.vhd
add_fileset_file ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_mul_single.vhd VHDL PATH ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_mul_single.vhd
add_fileset_file ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_sub_single.vhd VHDL PATH ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_sub_single.vhd
add_fileset_file ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_uminus_single.vhd VHDL PATH ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_nfp_uminus_single.vhd
add_fileset_file ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_ohc_nl_boltzman_function.vhd VHDL PATH ohc_nl_boltzman_function\\ur_ear_fpga_sim_ohc_nl_boltzman_function_ohc_nl_boltzman_function.vhd
add_fileset_file ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_nfp_add_single.vhd VHDL PATH ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_nfp_add_single.vhd
add_fileset_file ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_nfp_mul_single.vhd VHDL PATH ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_nfp_mul_single.vhd
add_fileset_file ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_nfp_uminus_single.vhd VHDL PATH ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_nfp_uminus_single.vhd
add_fileset_file ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_ohc_lowpass_filter.vhd VHDL PATH ohc_lowpass_filter\\ur_ear_fpga_sim_ohc_lowpass_filter_ohc_lowpass_filter.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_abs_single.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_abs_single.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_add_single.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_add_single.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_div_single.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_div_single.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_exp_single.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_exp_single.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_mul_single.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_mul_single.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_relop_single.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_relop_single.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_relop_single_block.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_relop_single_block.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_uminus_single.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_nfp_uminus_single.vhd
add_fileset_file ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_ohc_nonlinear_filter.vhd VHDL PATH ohc_nonlinear_filter\\ur_ear_fpga_sim_ohc_nonlinear_filter_ohc_nonlinear_filter.vhd
add_fileset_file outer_hair_cell\\ur_ear_fpga_sim_outer_hair_cell_outer_hair_cell.vhd VHDL PATH outer_hair_cell\\ur_ear_fpga_sim_outer_hair_cell_outer_hair_cell.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_Calculate_tauc1.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_Calculate_tauc1.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_Calculate_tauwb.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_Calculate_tauwb.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_calc_tau.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_calc_tau.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_gain_groupdelay.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_gain_groupdelay.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_add_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_add_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_convert_single_to_fix_16_En5.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_convert_single_to_fix_16_En5.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_cos_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_cos_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_div_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_div_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_floor_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_floor_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_gain_pow2_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_gain_pow2_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_mul_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_mul_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_recip_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_recip_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_relop_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_relop_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_sqrt_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_sqrt_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_sub_single.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_nfp_sub_single.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_SimpleDualPortRAM_generic.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_SimpleDualPortRAM_generic.vhd
add_fileset_file calc_tau\\ur_ear_fpga_sim_calc_tau_write_address_generator.vhd VHDL PATH calc_tau\\ur_ear_fpga_sim_calc_tau_write_address_generator.vhd
add_fileset_file control_path\\ur_ear_fpga_sim_control_path_control_path.vhd VHDL PATH control_path\\ur_ear_fpga_sim_control_path_control_path.vhd
add_fileset_file iir_10th_order\\ur_ear_fpga_sim_iir_10th_order_iir_10th_order.vhd VHDL PATH iir_10th_order\\ur_ear_fpga_sim_iir_10th_order_iir_10th_order.vhd
add_fileset_file iir_10th_order\\ur_ear_fpga_sim_iir_10th_order_nfp_add_single.vhd VHDL PATH iir_10th_order\\ur_ear_fpga_sim_iir_10th_order_nfp_add_single.vhd
add_fileset_file iir_10th_order\\ur_ear_fpga_sim_iir_10th_order_nfp_mul_single.vhd VHDL PATH iir_10th_order\\ur_ear_fpga_sim_iir_10th_order_nfp_mul_single.vhd
add_fileset_file calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp.vhd VHDL PATH calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp.vhd
add_fileset_file calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_add2_single.vhd VHDL PATH calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_add2_single.vhd
add_fileset_file calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_add_single.vhd VHDL PATH calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_add_single.vhd
add_fileset_file calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single.vhd VHDL PATH calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single.vhd
add_fileset_file calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_div_single.vhd VHDL PATH calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_div_single.vhd
add_fileset_file calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_sub_single.vhd VHDL PATH calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_sub_single.vhd
add_fileset_file calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_uminus_single.vhd VHDL PATH calc_phase_temp\\ur_ear_fpga_sim_calc_phase_temp_nfp_uminus_single.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_calc_coeff.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_calc_coeff.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_add_single.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_add_single.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_convert_double2single.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_convert_double2single.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_div_single.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_div_single.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_gain_pow2_single.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_gain_pow2_single.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_pow_single.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_pow_single.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_sub_single.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_sub_single.vhd
add_fileset_file calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_uminus_single.vhd VHDL PATH calc_coeff\\ur_ear_fpga_sim_calc_coeff_nfp_uminus_single.vhd
add_fileset_file calc_temp\\ur_ear_fpga_sim_calc_temp_calc_temp.vhd VHDL PATH calc_temp\\ur_ear_fpga_sim_calc_temp_calc_temp.vhd
add_fileset_file calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_add_single.vhd VHDL PATH calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_add_single.vhd
add_fileset_file calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_convert_double2single.vhd VHDL PATH calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_convert_double2single.vhd
add_fileset_file calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_pow_single.vhd VHDL PATH calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_pow_single.vhd
add_fileset_file calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_sub_single.vhd VHDL PATH calc_temp\\ur_ear_fpga_sim_calc_temp_nfp_sub_single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_calc_c1_coefficients.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_calc_c1_coefficients.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_add2_single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_add2_single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_add_single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_add_single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_convert_double2single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_convert_double2single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_div_single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_div_single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_gain_pow2_single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_gain_pow2_single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_sub_single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_sub_single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_tan_single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_tan_single.vhd
add_fileset_file calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_uminus_single.vhd VHDL PATH calc_c1_coefficients\\ur_ear_fpga_sim_calc_c1_coefficients_nfp_uminus_single.vhd
add_fileset_file c1_chirp_filter\\ur_ear_fpga_sim_c1_chirp_filter_c1_chirp_filter.vhd VHDL PATH c1_chirp_filter\\ur_ear_fpga_sim_c1_chirp_filter_c1_chirp_filter.vhd
add_fileset_file c1_chirp_filter\\ur_ear_fpga_sim_c1_chirp_filter_Calculate_C1filterout.vhd VHDL PATH c1_chirp_filter\\ur_ear_fpga_sim_c1_chirp_filter_Calculate_C1filterout.vhd
add_fileset_file c1_chirp_filter\\ur_ear_fpga_sim_c1_chirp_filter_nfp_mul_single.vhd VHDL PATH c1_chirp_filter\\ur_ear_fpga_sim_c1_chirp_filter_nfp_mul_single.vhd
add_fileset_file c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_c2_wideband_filter.vhd VHDL PATH c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_c2_wideband_filter.vhd
add_fileset_file c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_Calculate_C2filterout.vhd VHDL PATH c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_Calculate_C2filterout.vhd
add_fileset_file c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_nfp_abs_single.vhd VHDL PATH c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_nfp_abs_single.vhd
add_fileset_file c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_nfp_div_single.vhd VHDL PATH c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_nfp_div_single.vhd
add_fileset_file c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_nfp_mul_single.vhd VHDL PATH c2_wideband_filter\\ur_ear_fpga_sim_c2_wideband_filter_nfp_mul_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_ihc_nl_log.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_ihc_nl_log.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_abs_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_abs_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_add_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_add_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_convert_double2single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_convert_double2single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_div_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_div_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_exp_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_exp_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_log10_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_log10_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_log_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_log_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_mul_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_mul_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_relop_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_relop_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_sub_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_sub_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_uminus_single.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_nfp_uminus_single.vhd
add_fileset_file ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_Subsystem.vhd VHDL PATH ihc_nl_log\\ur_ear_fpga_sim_ihc_nl_log_Subsystem.vhd
add_fileset_file ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_ihc_lowpass_filter.vhd VHDL PATH ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_ihc_lowpass_filter.vhd
add_fileset_file ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_add_single.vhd VHDL PATH ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_add_single.vhd
add_fileset_file ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_mul_single.vhd VHDL PATH ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_mul_single.vhd
add_fileset_file ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_sub_single.vhd VHDL PATH ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_sub_single.vhd
add_fileset_file ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_uminus_single.vhd VHDL PATH ihc_lowpass_filter\\ur_ear_fpga_sim_ihc_lowpass_filter_nfp_uminus_single.vhd
add_fileset_file inner_hair_cell\\ur_ear_fpga_sim_inner_hair_cell_inner_hair_cell.vhd VHDL PATH inner_hair_cell\\ur_ear_fpga_sim_inner_hair_cell_inner_hair_cell.vhd
add_fileset_file inner_hair_cell\\ur_ear_fpga_sim_inner_hair_cell_nfp_convert_double2single.vhd VHDL PATH inner_hair_cell\\ur_ear_fpga_sim_inner_hair_cell_nfp_convert_double2single.vhd
add_fileset_file filter_path\\ur_ear_fpga_sim_filter_path_filter_path.vhd VHDL PATH filter_path\\ur_ear_fpga_sim_filter_path_filter_path.vhd
add_fileset_file auditory_nerve\\ur_ear_fpga_sim_auditory_nerve_auditory_nerve.vhd VHDL PATH auditory_nerve\\ur_ear_fpga_sim_auditory_nerve_auditory_nerve.vhd
add_fileset_file middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_middle_ear_filter.vhd VHDL PATH middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_middle_ear_filter.vhd
add_fileset_file middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_add_single.vhd VHDL PATH middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_add_single.vhd
add_fileset_file middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_gain_pow2_single.vhd VHDL PATH middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_gain_pow2_single.vhd
add_fileset_file middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_mul_single.vhd VHDL PATH middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_mul_single.vhd
add_fileset_file middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_uminus_single.vhd VHDL PATH middle_ear_filter\\ur_ear_fpga_sim_middle_ear_filter_nfp_uminus_single.vhd
add_fileset_file accumulator\\ur_ear_fpga_sim_accumulator_accumulator.vhd VHDL PATH accumulator\\ur_ear_fpga_sim_accumulator_accumulator.vhd
add_fileset_file initialize_signal\\ur_ear_fpga_sim_initialize_signal_initialize_signal.vhd VHDL PATH initialize_signal\\ur_ear_fpga_sim_initialize_signal_initialize_signal.vhd
add_fileset_file initialize_signal\\ur_ear_fpga_sim_initialize_signal_nfp_wire_double.vhd VHDL PATH initialize_signal\\ur_ear_fpga_sim_initialize_signal_nfp_wire_double.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_calc_Tref.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_calc_Tref.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_cal_trel_k.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_cal_trel_k.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_Current_Refactory_Component.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_Current_Refactory_Component.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_Current_Release_Component.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_Current_Release_Component.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_Elapsed_Time_Component.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_Elapsed_Time_Component.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_abs_double.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_abs_double.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_add_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_add_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_convert_fix_10_En0_to_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_convert_fix_10_En0_to_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_convert_single_to_fix_32_En0.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_div_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_div_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_log10_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_log10_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_mul_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_mul_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_recip_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_recip_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_double.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_double.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_single_block.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_single_block.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_single_block1.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_relop_single_block1.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_round_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_round_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_sub_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_sub_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_uminus_single.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_nfp_uminus_single.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_redocking_site.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_redocking_site.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_Redock_Component.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_Redock_Component.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_unitRateInterval_Component.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_unitRateInterval_Component.vhd
add_fileset_file redocking_site\\ur_ear_fpga_sim_redocking_site_Xsum_Component.vhd VHDL PATH redocking_site\\ur_ear_fpga_sim_redocking_site_Xsum_Component.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_Correct_Redocking_Period.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_Correct_Redocking_Period.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_Current_Redock_Component.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_Current_Redock_Component.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_abs_double.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_abs_double.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_add_single.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_add_single.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_convert_double2single.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_convert_double2single.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_convert_fix_10_En0_to_single.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_convert_fix_10_En0_to_single.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_div_single.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_div_single.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_mul_single.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_mul_single.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_sub_single.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_nfp_sub_single.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_Redocking_Calculation.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_Redocking_Calculation.vhd
add_fileset_file spike_generator\\ur_ear_fpga_sim_spike_generator_spike_generator.vhd VHDL PATH spike_generator\\ur_ear_fpga_sim_spike_generator_spike_generator.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_abs_single.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_abs_single.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_add_single.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_add_single.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_log10_single.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_log10_single.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_mul_single.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_mul_single.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_pow10_single.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_pow10_single.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_relop_single.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_relop_single.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_signum_single.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nfp_signum_single.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nl_pla_filter.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_nl_pla_filter.vhd
add_fileset_file nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_Subsystem.vhd VHDL PATH nl_pla_filter\\ur_ear_fpga_sim_nl_pla_filter_Subsystem.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_Fast_Power_Law.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_Fast_Power_Law.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_add_single.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_add_single.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_gain_pow2_single.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_gain_pow2_single.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_mul_single.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_mul_single.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_relop_single.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_relop_single.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_sub_single.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_sub_single.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_uminus_single.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_nfp_uminus_single.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_power_law_adapter.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_power_law_adapter.vhd
add_fileset_file power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_Slow_Power_Law.vhd VHDL PATH power_law_adapter\\ur_ear_fpga_sim_power_law_adapter_Slow_Power_Law.vhd
add_fileset_file synapse_model\\ur_ear_fpga_sim_synapse_model_synapse_model.vhd VHDL PATH synapse_model\\ur_ear_fpga_sim_synapse_model_synapse_model.vhd
add_fileset_file synapse_spike_generator\\ur_ear_fpga_sim_synapse_spike_generator_synapse_spike_generator.vhd VHDL PATH synapse_spike_generator\\ur_ear_fpga_sim_synapse_spike_generator_synapse_spike_generator.vhd
add_fileset_file ur_ear_fpga_sim_Avalon_Data_Processing.vhd VHDL PATH ur_ear_fpga_sim_Avalon_Data_Processing.vhd
add_fileset_file ur_ear_fpga_sim_dataplane.vhd VHDL PATH ur_ear_fpga_sim_dataplane.vhd
add_fileset_file ur_ear_fpga_sim_dataplane_avalon.vhd VHDL PATH ur_ear_fpga_sim_dataplane_avalon.vhd
add_fileset_file ur_ear_fpga_sim_dataplane_tc.vhd VHDL PATH ur_ear_fpga_sim_dataplane_tc.vhd
add_fileset_file ur_ear_fpga_sim_nfp_convert_double2single.vhd VHDL PATH ur_ear_fpga_sim_nfp_convert_double2single.vhd
add_fileset_file ur_ear_fpga_sim_nfp_convert_sfix_32_En28_to_single.vhd VHDL PATH ur_ear_fpga_sim_nfp_convert_sfix_32_En28_to_single.vhd
add_fileset_file ur_ear_fpga_sim_UR_EAR_FPGA.vhd VHDL PATH ur_ear_fpga_sim_UR_EAR_FPGA.vhd
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ur_ear_fpga_sim_dataplane_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ur_ear_fpga_sim_dataplane_avalon.vhd VHDL PATH ur_ear_fpga_sim_dataplane_avalon.vhd TOP_LEVEL_FILE



set_module_assignment embeddedsw.dts.compatible dev,al-ur_ear_fpga_sim
set_module_assignment embeddedsw.dts.group autogen 
set_module_assignment embeddedsw.dts.vendor al



add_interface clock clock end
set_interface_property clock clockRate 98304000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
add_interface_port clock clk clk Input 1



add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF true
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
add_interface_port reset reset reset Input 1



add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 1
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_slave_address address Input 2
add_interface_port avalon_slave avalon_slave_read read Input 1
add_interface_port avalon_slave avalon_slave_readdata readdata Output 32
add_interface_port avalon_slave avalon_slave_write write Input 1
add_interface_port avalon_slave avalon_slave_writedata writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0



add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 32
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""
add_interface_port avalon_streaming_sink avalon_sink_valid valid Input 1
add_interface_port avalon_streaming_sink avalon_sink_data data Input 32
add_interface_port avalon_streaming_sink avalon_sink_channel channel Input 1
add_interface_port avalon_streaming_sink avalon_sink_error error Input 2



add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 32
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""
add_interface_port avalon_streaming_source avalon_source_valid valid Output 1
add_interface_port avalon_streaming_source avalon_source_data data Output 32
add_interface_port avalon_streaming_source avalon_source_channel channel Output 1
add_interface_port avalon_streaming_source avalon_source_error error Output 2



