vmap -c
vlib work
vmap work work

vcom  ur_ear_fpga_sim_dataplane_pkg.vhd
cd calc_tau
do calc_tau_compile.do
cd ..
cd cp_wideband_gammatone_filter
do cp_wideband_gammatone_filter_compile.do
cd ..
cd ohc_lowpass_filter
do ohc_lowpass_filter_compile.do
cd ..
cd ohc_nl_boltzman_function
do ohc_nl_boltzman_function_compile.do
cd ..
cd ohc_nonlinear_filter
do ohc_nonlinear_filter_compile.do
cd ..
cd outer_hair_cell
do outer_hair_cell_compile.do
cd ..
cd control_path
do control_path_compile.do
cd ..
cd calc_coeff
do calc_coeff_compile.do
cd ..
cd calc_phase_temp
do calc_phase_temp_compile.do
cd ..
cd calc_temp
do calc_temp_compile.do
cd ..
cd calc_c1_coefficients
do calc_c1_coefficients_compile.do
cd ..
cd iir_10th_order
do iir_10th_order_compile.do
cd ..
cd c1_chirp_filter
do c1_chirp_filter_compile.do
cd ..
cd c2_wideband_filter
do c2_wideband_filter_compile.do
cd ..
cd ihc_lowpass_filter
do ihc_lowpass_filter_compile.do
cd ..
cd ihc_nl_log
do ihc_nl_log_compile.do
cd ..
cd inner_hair_cell
do inner_hair_cell_compile.do
cd ..
cd filter_path
do filter_path_compile.do
cd ..
cd auditory_nerve
do auditory_nerve_compile.do
cd ..
cd middle_ear_filter
do middle_ear_filter_compile.do
cd ..
cd accumulator
do accumulator_compile.do
cd ..
cd initialize_signal
do initialize_signal_compile.do
cd ..
cd redocking_site
do redocking_site_compile.do
cd ..
cd spike_generator
do spike_generator_compile.do
cd ..
cd nl_pla_filter
do nl_pla_filter_compile.do
cd ..
cd power_law_adapter
do power_law_adapter_compile.do
cd ..
cd synapse_model
do synapse_model_compile.do
cd ..
cd synapse_spike_generator
do synapse_spike_generator_compile.do
cd ..
vcom  ur_ear_fpga_sim_UR_EAR_FPGA.vhd
vcom  ur_ear_fpga_sim_nfp_convert_sfix_32_En28_to_single.vhd
vcom  ur_ear_fpga_sim_nfp_convert_double2single.vhd
vcom  ur_ear_fpga_sim_Avalon_Data_Processing.vhd
vcom  ur_ear_fpga_sim_dataplane_tc.vhd
vcom  ur_ear_fpga_sim_dataplane.vhd
