vlib work
vcom  SG_DataPlane_src_Left_Channel_Processing.vhd
vcom  SG_DataPlane_src_Right_Channel_Processing.vhd
vcom  SG_DataPlane_src_Avalon_Data_Processing.vhd
vcom  SG_DataPlane_src_SG_DataPlane.vhd
