config audioblade_system_altera_mm_interconnect_180_l5dmrei_cfg;
		design audioblade_system_altera_mm_interconnect_180_l5dmrei;
		instance audioblade_system_altera_mm_interconnect_180_l5dmrei.ioaux_master_bridge_m0_translator use audioblade_system_altera_merlin_master_translator_180.altera_merlin_master_translator;
		instance audioblade_system_altera_mm_interconnect_180_l5dmrei.ioaux_soft_ram_s1_translator use audioblade_system_altera_merlin_slave_translator_180.altera_merlin_slave_translator;
endconfig

