config audioblade_system_altera_mm_interconnect_180_2zdh4ci_cfg;
		design audioblade_system_altera_mm_interconnect_180_2zdh4ci;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.arria10_hps_0_h2f_axi_master_agent use audioblade_system_altera_merlin_axi_master_ni_180.altera_merlin_axi_master_ni;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.mux_ddr_0_altera_axi_slave_agent use audioblade_system_altera_merlin_axi_slave_ni_180.altera_merlin_axi_slave_ni;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.router use audioblade_system_altera_merlin_router_180.audioblade_system_altera_merlin_router_180_iv666ga;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.router_001 use audioblade_system_altera_merlin_router_180.audioblade_system_altera_merlin_router_180_lxmadiq;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.router_002 use audioblade_system_altera_merlin_router_180.audioblade_system_altera_merlin_router_180_dqbhvfa;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.router_003 use audioblade_system_altera_merlin_router_180.audioblade_system_altera_merlin_router_180_goyglzq;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.mux_ddr_0_altera_axi_slave_wr_burst_adapter use audioblade_system_altera_merlin_burst_adapter_180.altera_merlin_burst_adapter;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.mux_ddr_0_altera_axi_slave_rd_burst_adapter use audioblade_system_altera_merlin_burst_adapter_180.altera_merlin_burst_adapter;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.cmd_demux use audioblade_system_altera_merlin_demultiplexer_180.audioblade_system_altera_merlin_demultiplexer_180_oh2yaqq;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.cmd_demux_001 use audioblade_system_altera_merlin_demultiplexer_180.audioblade_system_altera_merlin_demultiplexer_180_oh2yaqq;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.cmd_mux use audioblade_system_altera_merlin_multiplexer_180.audioblade_system_altera_merlin_multiplexer_180_zd5hm5y;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.cmd_mux_001 use audioblade_system_altera_merlin_multiplexer_180.audioblade_system_altera_merlin_multiplexer_180_zd5hm5y;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.rsp_demux use audioblade_system_altera_merlin_demultiplexer_180.audioblade_system_altera_merlin_demultiplexer_180_x2ejjsa;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.rsp_demux_001 use audioblade_system_altera_merlin_demultiplexer_180.audioblade_system_altera_merlin_demultiplexer_180_x2ejjsa;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.rsp_mux use audioblade_system_altera_merlin_multiplexer_180.audioblade_system_altera_merlin_multiplexer_180_ay6xe7y;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.rsp_mux_001 use audioblade_system_altera_merlin_multiplexer_180.audioblade_system_altera_merlin_multiplexer_180_ay6xe7y;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.mux_ddr_0_altera_axi_slave_wr_rsp_width_adapter use audioblade_system_altera_merlin_width_adapter_180.altera_merlin_width_adapter;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.mux_ddr_0_altera_axi_slave_rd_rsp_width_adapter use audioblade_system_altera_merlin_width_adapter_180.altera_merlin_width_adapter;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.mux_ddr_0_altera_axi_slave_wr_cmd_width_adapter use audioblade_system_altera_merlin_width_adapter_180.altera_merlin_width_adapter;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.mux_ddr_0_altera_axi_slave_rd_cmd_width_adapter use audioblade_system_altera_merlin_width_adapter_180.altera_merlin_width_adapter;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.crosser use audioblade_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.crosser_001 use audioblade_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.crosser_002 use audioblade_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance audioblade_system_altera_mm_interconnect_180_2zdh4ci.crosser_003 use audioblade_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
endconfig

