config audioblade_system_altera_arria10_hps_180_zmlrihi_cfg;
		design audioblade_system_altera_arria10_hps_180_zmlrihi;
		instance audioblade_system_altera_arria10_hps_180_zmlrihi.fpga_interfaces use audioblade_system_altera_arria10_interface_generator_140.audioblade_system_altera_arria10_interface_generator_140_hnufizi;
		instance audioblade_system_altera_arria10_hps_180_zmlrihi.hps_io use audioblade_system_altera_arria10_hps_io_180.audioblade_system_altera_arria10_hps_io_180_of6hmti;
endconfig

