open_system('sm_DynamicCompression');
open_system('gm_sm_DynamicCompression');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Unit Delay', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Unit Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Unit Delay_switch', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Compression_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Compression_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Compression_Envelope/Attack_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Compression_Envelope/Attack_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Compression_Envelope/Release_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_1/Compression_Envelope/Release_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Unit Delay', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Unit Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Unit Delay_switch', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Compression_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Compression_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Compression_Envelope/Attack_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Compression_Envelope/Attack_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Compression_Envelope/Release_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_2/Compression_Envelope/Release_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Unit Delay', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Unit Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Unit Delay_switch', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Compression_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Compression_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Compression_Envelope/Attack_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Compression_Envelope/Attack_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Compression_Envelope/Release_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_3/Compression_Envelope/Release_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Unit Delay', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Unit Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Unit Delay_switch', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Compression_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Compression_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Compression_Envelope/Attack_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Compression_Envelope/Attack_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Compression_Envelope/Release_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_4/Compression_Envelope/Release_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Unit Delay', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Unit Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Unit Delay_switch', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Compression_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Compression_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Compression_Envelope/Attack_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Compression_Envelope/Attack_Envelope', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Compression_Envelope/Release_Envelope', 'user4');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Compression_5/Compression_Envelope/Release_Envelope', 'user4');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR1/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR2/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR3/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Reset_Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Nchan_FbankAGC_AID/Static_pFIR4/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/Sum_memory', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/Sum_memory', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/Multiply-Add', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/convertB', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/convertB', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/Reset_Switch', 'user1');
hilite_system('sm_DynamicCompression/dataplane/Avalon Data Processing/Left Channel Processing/recalculate/Static_pFIR/Multiply_And_Sum/Reset_Switch', 'user1');
