-- -------------------------------------------------------------
-- 
-- File Name: /home/justin/Documents/FEI/simulink_models/models/dynamic_FIRFilter/hdlsrc/pFIR_HPF_testing_and_analysis/pFIR_HPF_testing_and_analysis_Right_Channel_Processing.vhd
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pFIR_HPF_testing_and_analysis_Right_Channel_Processing
-- Source Path: pFIR_HPF_testing_and_analysis/dataplane/Test FIR with Custom FIR Libraries Sample Based Filtering/Right 
-- Channel Processin
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.pFIR_HPF_testing_and_analysis_dataplane_pkg.ALL;

ENTITY pFIR_HPF_testing_and_analysis_Right_Channel_Processing IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_16_0                        :   IN    std_logic;
        enb_1_16_1                        :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        Right_Data_Sink                   :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        register_control_enable           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        right_data_valid                  :   IN    std_logic;
        Right_Data_Source                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En28
        );
END pFIR_HPF_testing_and_analysis_Right_Channel_Processing;


ARCHITECTURE rtl OF pFIR_HPF_testing_and_analysis_Right_Channel_Processing IS

  -- Component Declarations
  COMPONENT pFIR_HPF_testing_and_analysis_Static_Upclocked_FIR_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          enb_1_16_1                      :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          Data_In                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          Valid_in                        :   IN    std_logic;
          Data_out                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En28
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : pFIR_HPF_testing_and_analysis_Static_Upclocked_FIR_block
    USE ENTITY work.pFIR_HPF_testing_and_analysis_Static_Upclocked_FIR_block(rtl);

  -- Signals
  SIGNAL register_control_enable_signed   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL delayMatch_reg                   : vector_of_signed32(0 TO 15);  -- sfix32 [16]
  SIGNAL register_control_enable_1        : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Right_Data_Sink_signed           : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL delayMatch1_reg                  : vector_of_signed32(0 TO 15);  -- sfix32 [16]
  SIGNAL right_data_sinksource_passthrough : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL filter_data                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL filter_data_signed               : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Right_Data_Source_1              : signed(31 DOWNTO 0);  -- sfix32_En28

BEGIN
  -- An enabled subsystem
  -- This subsystem only runs when the data valid signal is enabled (asserted)

  u_Static_Upclocked_FIR : pFIR_HPF_testing_and_analysis_Static_Upclocked_FIR_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              enb_1_16_1 => enb_1_16_1,
              enb_1_2048_0 => enb_1_2048_0,
              Data_In => Right_Data_Sink,  -- sfix32_En28
              Valid_in => right_data_valid,
              Data_out => filter_data  -- sfix32_En28
              );

  register_control_enable_signed <= signed(register_control_enable);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_signed(0, 32));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= register_control_enable_signed;
        delayMatch_reg(1 TO 15) <= delayMatch_reg(0 TO 14);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  register_control_enable_1 <= delayMatch_reg(15);

  
  switch_compare_1 <= '1' WHEN register_control_enable_1 >= to_signed(268435456, 32) ELSE
      '0';

  Right_Data_Sink_signed <= signed(Right_Data_Sink);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch1_reg <= (OTHERS => to_signed(0, 32));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        delayMatch1_reg(0) <= Right_Data_Sink_signed;
        delayMatch1_reg(1 TO 15) <= delayMatch1_reg(0 TO 14);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  right_data_sinksource_passthrough <= delayMatch1_reg(15);

  filter_data_signed <= signed(filter_data);

  
  Right_Data_Source_1 <= right_data_sinksource_passthrough WHEN switch_compare_1 = '0' ELSE
      filter_data_signed;

  Right_Data_Source <= std_logic_vector(Right_Data_Source_1);

END rtl;

