vmap work ../work

vmap -c
vcom  ur_ear_fpga_sim_calc_coeff_nfp_uminus_single.vhd
vcom  ur_ear_fpga_sim_calc_coeff_nfp_gain_pow2_single.vhd
vcom  ur_ear_fpga_sim_calc_coeff_nfp_div_single.vhd
vcom  ur_ear_fpga_sim_calc_coeff_nfp_sub_single.vhd
vcom  ur_ear_fpga_sim_calc_coeff_nfp_add_single.vhd
vcom  ur_ear_fpga_sim_calc_coeff_nfp_pow_single.vhd
vcom  ur_ear_fpga_sim_calc_coeff_nfp_convert_double2single.vhd
vcom  ur_ear_fpga_sim_calc_coeff_calc_coeff.vhd
