-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/RAM_test/Static_pFIR_tc.vhd
-- Created: 2019-11-19 13:52:35
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Static_pFIR_tc
-- Source Path: Static_pFIR_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_1_1   : identical to clk_enable
-- enb_1_1024_0: 1024x slower than clk with last phase
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Static_pFIR_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic;
        enb_1_1024_0                      :   OUT   std_logic
        );
END Static_pFIR_tc;


ARCHITECTURE rtl OF Static_pFIR_tc IS

  -- Signals
  SIGNAL count1024                        : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;

BEGIN
  Counter1024 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count1024 <= to_unsigned(1, 10);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count1024 >= to_unsigned(1023, 10) THEN
          count1024 <= to_unsigned(0, 10);
        ELSE
          count1024 <= count1024 + to_unsigned(1, 10);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter1024;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count1024 = to_unsigned(1023, 10) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_1_1 <=  phase_all AND clk_enable;

  enb_1_1024_0 <=  phase_0 AND clk_enable;


END rtl;

