config audioblade_system_altera_emif_cal_slave_nf_180_5pbk77i_cfg;
		design audioblade_system_altera_emif_cal_slave_nf_180_5pbk77i;
		instance audioblade_system_altera_emif_cal_slave_nf_180_5pbk77i.ioaux_master_bridge use audioblade_system_altera_avalon_mm_bridge_180.altera_avalon_mm_bridge;
		instance audioblade_system_altera_emif_cal_slave_nf_180_5pbk77i.ioaux_soft_ram use audioblade_system_altera_avalon_onchip_memory2_180.audioblade_system_altera_avalon_onchip_memory2_180_m2wik5y;
		instance audioblade_system_altera_emif_cal_slave_nf_180_5pbk77i.mm_interconnect_0 use audioblade_system_altera_mm_interconnect_180.audioblade_system_altera_mm_interconnect_180_l5dmrei;
		instance audioblade_system_altera_emif_cal_slave_nf_180_5pbk77i.rst_controller use audioblade_system_altera_reset_controller_180.altera_reset_controller;
endconfig

