-- -------------------------------------------------------------
-- 
-- File Name: D:\NIH3Repo\simulink_models\models\ur_ear_fpga\hdlsrc\ur_ear_fpga_sim\c2_wideband_filter\ur_ear_fpga_sim_c2_wideband_filter_c2_wideband_filter.vhd
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ur_ear_fpga_sim_c2_wideband_filter_c2_wideband_filter
-- Source Path: c2_wideband_filter
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ur_ear_fpga_sim_c2_wideband_filter_c2_wideband_filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        c2_wideband_in                    :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        c2_wideband_out                   :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END ur_ear_fpga_sim_c2_wideband_filter_c2_wideband_filter;


ARCHITECTURE rtl OF ur_ear_fpga_sim_c2_wideband_filter_c2_wideband_filter IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT iir_10th_order
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          Sink_Data                       :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f1_c1                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f1_c2                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f1_c3                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f1_c5                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f1_c6                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f2_c1                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f2_c2                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f2_c3                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f2_c5                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f2_c6                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f3_c1                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f3_c2                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f3_c3                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f3_c5                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f3_c6                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f4_c1                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f4_c2                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f4_c3                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f4_c5                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f4_c6                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f5_c1                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f5_c2                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f5_c3                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f5_c5                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          f5_c6                           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Source_Data                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_c2_wideband_filter_nfp_mul_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_c2_wideband_filter_Calculate_C2filterout
    PORT( C2filterouttmp                  :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          C2filterout                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : iir_10th_order
    USE ENTITY work.ur_ear_fpga_sim_iir_10th_order_iir_10th_order(rtl);

  FOR ALL : ur_ear_fpga_sim_c2_wideband_filter_nfp_mul_single
    USE ENTITY work.ur_ear_fpga_sim_c2_wideband_filter_nfp_mul_single(rtl);

  FOR ALL : ur_ear_fpga_sim_c2_wideband_filter_Calculate_C2filterout
    USE ENTITY work.ur_ear_fpga_sim_c2_wideband_filter_Calculate_C2filterout(rtl);

  -- Signals
  SIGNAL Constant2_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant26_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant3_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant4_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant5_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant6_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant27_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant28_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant29_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant30_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant10_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant1_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant7_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant8_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant9_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant12_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant11_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant13_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant14_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant15_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant17_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant16_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant18_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant19_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant20_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL alpha10th_Order_IIR_Filter_out1  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL kconst                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Gain2_out1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL C2filterout                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_alpha10th_Order_IIR_Filter : iir_10th_order
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              Sink_Data => c2_wideband_in,  -- single
              f1_c1 => Constant2_out1,  -- single
              f1_c2 => Constant26_out1,  -- single
              f1_c3 => Constant3_out1,  -- single
              f1_c5 => Constant4_out1,  -- single
              f1_c6 => Constant5_out1,  -- single
              f2_c1 => Constant6_out1,  -- single
              f2_c2 => Constant27_out1,  -- single
              f2_c3 => Constant28_out1,  -- single
              f2_c5 => Constant29_out1,  -- single
              f2_c6 => Constant30_out1,  -- single
              f3_c1 => Constant10_out1,  -- single
              f3_c2 => Constant1_out1,  -- single
              f3_c3 => Constant7_out1,  -- single
              f3_c5 => Constant8_out1,  -- single
              f3_c6 => Constant9_out1,  -- single
              f4_c1 => Constant12_out1,  -- single
              f4_c2 => Constant11_out1,  -- single
              f4_c3 => Constant13_out1,  -- single
              f4_c5 => Constant14_out1,  -- single
              f4_c6 => Constant15_out1,  -- single
              f5_c1 => Constant17_out1,  -- single
              f5_c2 => Constant16_out1,  -- single
              f5_c3 => Constant18_out1,  -- single
              f5_c5 => Constant19_out1,  -- single
              f5_c6 => Constant20_out1,  -- single
              Source_Data => alpha10th_Order_IIR_Filter_out1  -- single
              );

  u_nfp_mul_comp : ur_ear_fpga_sim_c2_wideband_filter_nfp_mul_single
    PORT MAP( nfp_in1 => kconst,  -- ufix32
              nfp_in2 => alpha10th_Order_IIR_Filter_out1,  -- ufix32
              nfp_out => Gain2_out1  -- ufix32
              );

  u_Calculate_C2filterout : ur_ear_fpga_sim_c2_wideband_filter_Calculate_C2filterout
    PORT MAP( C2filterouttmp => Gain2_out1,  -- single
              C2filterout => C2filterout  -- single
              );

  kconst <= X"59f1801e";

  Constant2_out1 <= X"380a704b";

  Constant26_out1 <= X"3750243a";

  Constant3_out1 <= X"b7acce79";

  Constant4_out1 <= X"3fcf1e9b";

  Constant5_out1 <= X"bf44bbcb";

  Constant6_out1 <= X"37f999a5";

  Constant27_out1 <= X"373ba2d3";

  Constant28_out1 <= X"b79bc83b";

  Constant29_out1 <= X"3fb8dd91";

  Constant30_out1 <= X"bf1bd484";

  Constant10_out1 <= X"37e214cc";

  Constant1_out1 <= X"3729f4ad";

  Constant7_out1 <= X"b78d1a75";

  Constant8_out1 <= X"3fa47e43";

  Constant9_out1 <= X"bef5dca7";

  Constant12_out1 <= X"380a704b";

  Constant11_out1 <= X"3750243a";

  Constant13_out1 <= X"b7acce79";

  Constant14_out1 <= X"3fcf1e9b";

  Constant15_out1 <= X"bf44bbcb";

  Constant17_out1 <= X"37e214cc";

  Constant16_out1 <= X"3729f4ad";

  Constant18_out1 <= X"b78d1a75";

  Constant19_out1 <= X"3fa47e43";

  Constant20_out1 <= X"bef5dca7";

  c2_wideband_out <= C2filterout;

END rtl;

