vmap work ../work

vmap -c
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_uminus_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_mul_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_div_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_sub_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_log10_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_exp_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_add_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_Subsystem.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_abs_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_convert_double2single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_log_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_nfp_relop_single.vhd
vcom  ur_ear_fpga_sim_ihc_nl_log_ihc_nl_log.vhd
