open_system('gm_simple_gain');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_simple_gain/dataplane/Avalon Data Processing', 'user2');
annotate_port('gm_simple_gain/dataplane/Avalon Data Processing', 0, 1, 'cp : 8.801 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp', 'user2');
annotate_port('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp', 0, 1, 'cp : 8.801 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp/Data Type Conversion', 'user2');
annotate_port('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp/Data Type Conversion', 0, 1, 'cp : 8.636 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp/Product1', 'user1');
annotate_port('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp/Product1', 0, 1, 'cp : 8.636 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp/Switch', 'user1');
annotate_port('gm_simple_gain/dataplane/Avalon Data Processing/controlss_temp/Switch', 0, 1, 'cp : 8.801 ns');
