vlib work
vmap -c
vcom  OHC_NL_Boltzman_Function_Singles_pkg.vhd
vcom  nfp_uminus_single.vhd
vcom  nfp_add_single.vhd
vcom  nfp_div_single.vhd
vcom  nfp_exp_single.vhd
vcom  nfp_mul_single.vhd
vcom  nfp_sub_single.vhd
vcom  OHC_NL_Boltzman_Function_Singles.vhd
