open_system('Subsystem');
open_system('gm_Subsystem');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay', 'user2');
annotate_port('gm_Subsystem/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('Subsystem/Unit Delay', 'user2');
annotate_port('Subsystem/Unit Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay1', 'user2');
annotate_port('gm_Subsystem/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('Subsystem/Unit Delay1', 'user2');
annotate_port('Subsystem/Unit Delay1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay3', 'user2');
annotate_port('gm_Subsystem/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('Subsystem/Unit Delay3', 'user2');
annotate_port('Subsystem/Unit Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay2', 'user2');
annotate_port('gm_Subsystem/Unit Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('Subsystem/Unit Delay2', 'user2');
annotate_port('Subsystem/Unit Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay5', 'user2');
annotate_port('gm_Subsystem/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('Subsystem/Unit Delay5', 'user2');
annotate_port('Subsystem/Unit Delay5', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay4', 'user2');
annotate_port('gm_Subsystem/Unit Delay4', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('Subsystem/Unit Delay4', 'user2');
annotate_port('Subsystem/Unit Delay4', 1, 1, 'Obstacle to clock-rate pipelining');
