open_system('Subsystem');
open_system('gm_Subsystem');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay3', 'user4');
hilite_system('Subsystem/Unit Delay3', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay2', 'user4');
hilite_system('Subsystem/Unit Delay2', 'user4');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay5', 'user5');
hilite_system('Subsystem/Unit Delay5', 'user5');
cs.HiliteType = 'user5';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'magenta';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Subsystem/Unit Delay4', 'user5');
hilite_system('Subsystem/Unit Delay4', 'user5');
