-- -------------------------------------------------------------
-- 
-- File Name: D:\NIH3Repo\simulink_models\models\ur_ear_fpga\hdlsrc\ur_ear_fpga_sim\calc_phase_temp\ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp.vhd
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp
-- Source Path: calc_phase_temp
-- Hierarchy Level: 7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp IS
  PORT( CF                                :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        preal                             :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        pimg1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        Out_rsvd                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp;


ARCHITECTURE rtl OF ur_ear_fpga_sim_calc_phase_temp_calc_phase_temp IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT ur_ear_fpga_sim_calc_phase_temp_nfp_sub_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_calc_phase_temp_nfp_uminus_single
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_calc_phase_temp_nfp_add_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_calc_phase_temp_nfp_div_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single
    PORT( nfp_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  COMPONENT ur_ear_fpga_sim_calc_phase_temp_nfp_add2_single
    PORT( nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ur_ear_fpga_sim_calc_phase_temp_nfp_sub_single
    USE ENTITY work.ur_ear_fpga_sim_calc_phase_temp_nfp_sub_single(rtl);

  FOR ALL : ur_ear_fpga_sim_calc_phase_temp_nfp_uminus_single
    USE ENTITY work.ur_ear_fpga_sim_calc_phase_temp_nfp_uminus_single(rtl);

  FOR ALL : ur_ear_fpga_sim_calc_phase_temp_nfp_add_single
    USE ENTITY work.ur_ear_fpga_sim_calc_phase_temp_nfp_add_single(rtl);

  FOR ALL : ur_ear_fpga_sim_calc_phase_temp_nfp_div_single
    USE ENTITY work.ur_ear_fpga_sim_calc_phase_temp_nfp_div_single(rtl);

  FOR ALL : ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single
    USE ENTITY work.ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single(rtl);

  FOR ALL : ur_ear_fpga_sim_calc_phase_temp_nfp_add2_single
    USE ENTITY work.ur_ear_fpga_sim_calc_phase_temp_nfp_add2_single(rtl);

  -- Signals
  SIGNAL Subtract_out1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Multiply_out1                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Add_out1                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide_out1                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Atan_out1                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Divide1_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Atan1_out1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Subtract1_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_nfp_sub_comp : ur_ear_fpga_sim_calc_phase_temp_nfp_sub_single
    PORT MAP( nfp_in1 => CF,  -- ufix32
              nfp_in2 => pimg1,  -- ufix32
              nfp_out => Subtract_out1  -- ufix32
              );

  u_nfp_uminus_comp : ur_ear_fpga_sim_calc_phase_temp_nfp_uminus_single
    PORT MAP( nfp_in => preal,  -- ufix32
              nfp_out => Multiply_out1  -- ufix32
              );

  u_nfp_add_comp : ur_ear_fpga_sim_calc_phase_temp_nfp_add_single
    PORT MAP( nfp_in1 => CF,  -- ufix32
              nfp_in2 => pimg1,  -- ufix32
              nfp_out => Add_out1  -- ufix32
              );

  u_nfp_div_comp : ur_ear_fpga_sim_calc_phase_temp_nfp_div_single
    PORT MAP( nfp_in1 => Subtract_out1,  -- ufix32
              nfp_in2 => Multiply_out1,  -- ufix32
              nfp_out => Divide_out1  -- ufix32
              );

  u_nfp_atan_comp : ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single
    PORT MAP( nfp_in => Divide_out1,  -- ufix32
              nfp_out => Atan_out1  -- ufix32
              );

  u_nfp_div_comp_1 : ur_ear_fpga_sim_calc_phase_temp_nfp_div_single
    PORT MAP( nfp_in1 => Add_out1,  -- ufix32
              nfp_in2 => Multiply_out1,  -- ufix32
              nfp_out => Divide1_out1  -- ufix32
              );

  u_nfp_atan_comp_1 : ur_ear_fpga_sim_calc_phase_temp_nfp_atan_single
    PORT MAP( nfp_in => Divide1_out1,  -- ufix32
              nfp_out => Atan1_out1  -- ufix32
              );

  u_nfp_add2_comp : ur_ear_fpga_sim_calc_phase_temp_nfp_add2_single
    PORT MAP( nfp_in1 => Atan_out1,  -- ufix32
              nfp_in2 => Atan1_out1,  -- ufix32
              nfp_out => Subtract1_out1  -- ufix32
              );

  Out_rsvd <= Subtract1_out1;

END rtl;

