-- -------------------------------------------------------------
-- 
-- File Name: /home/justin/Documents/Flat Earth Inc/simulink_models/simulink_models/models/wiener_noise_reduction/hdlsrc/wiener/wiener_wienFilter1.vhd
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: wiener_wienFilter1
-- Source Path: wiener/dataplane/Adaptive_Wiener_Filter Sample Based Filtering/Left Channel Processing/Subsystem/wienFilter1
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY wiener_wienFilter1 IS
  PORT( winMean                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        left_source_data                  :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En28
        );
END wiener_wienFilter1;


ARCHITECTURE rtl OF wiener_wienFilter1 IS

BEGIN
  -- NOTE: This has not been tested with different instances of noise being inserted. 
  -- 
  -- It seems that replacing the samples with the mean of the short look-behind window allows it to be sounding pretty 
  -- decent




  left_source_data <= winMean;

END rtl;

